ig.module('game.entities.pinball.ball').requires('cm.entity').defines(function()
{entPinballBall=ig.Entity.extend({name:'ball',pos:{x:714,y:220},size:{x:50,y:44},offset:{x:0.5,y:0.5},isHidden:false,teleportThreshold:2,_teleportTime:0,usedTeleport:false,shakeForce:6,shakeThreshold:1,_canShake:true,timeoutId:0,tween:null,soundIncrement:10000,_soundIncrementScore:0,soundHighScore:new ig.Sound('media/audio/sfx2/high_score.*'),soundWhat:new ig.Sound('media/audio/sfx2/what.*'),sound1:new ig.Sound('media/audio/sfx2/grunt_1.*'),sound2:new ig.Sound('media/audio/sfx2/grunt_2.*'),soundHit1:new ig.Sound('media/audio/sfx2/GeneralHit1.*'),soundHit2:new ig.Sound('media/audio/sfx2/GeneralHit2.*'),soundHit3:new ig.Sound('media/audio/sfx2/GeneralHit3.*'),soundHit4:new ig.Sound('media/audio/sfx2/GeneralHit4.*'),soundGutter:new ig.Sound('media/audio/sfx2/gutter.*'),init:function()
{this.parent();this.startPos={x:this.pos.x,y:this.pos.y};var ta=ig.game.getTextureAtlas('pinball_sprites');this.addTextureAtlasAnim(ta,'idle',0.1,['crash.png'],true,true);this.addTextureAtlasAnim(ta,'scream1',0.1,['crash_scream1.png'],true,true);this.addTextureAtlasAnim(ta,'scream2',0.1,['crash_scream2.png'],true,true);this.addTextureAtlasAnim(ta,'scream3',0.1,['crash_scream3.png'],true,true);if(ig.gameTank.data.room=='living_room')
this.addTextureAtlasAnim(ta,'electric',0.15,['crash_electric.png','crash.png'],false,true);var b2BodyDef=new Box2D.Dynamics.b2BodyDef;b2BodyDef.position.Set(this.pos.x/Box2D.SCALE,this.pos.y/Box2D.SCALE);var fixture=new Box2D.Dynamics.b2FixtureDef;fixture.shape=new Box2D.Collision.Shapes.b2CircleShape;fixture.shape.SetRadius(20/Box2D.SCALE);fixture.density=10;fixture.friction=0.2;fixture.restitution=0.4;this.b2Body=ig.game.b2World.CreateBody(b2BodyDef);this.b2Body.CreateFixture(fixture);this.b2Body.SetFixedRotation(false);this.b2Body.SetUserData(this);this.b2Body.SetBullet(true);this.b2Body.SetType(ig.game.controlBall?0:2);},update:function()
{this.parent();this.currentAnim.angle=this.b2Body.GetAngle();var p=this.b2Body.GetPosition();this.pos.x=(p.x*Box2D.SCALE)-ig.game.shakePos.x;this.pos.y=(p.y*Box2D.SCALE)-ig.game.shakePos.y;var y=(this.pos.y-ig.system.realHeight*0.5).limit(-ig.game.bgImg.height*0.5,0);ig.game.screen.y=Math.lerp(ig.game.screen.y,y,0.08);this.b2Body.SetAwake(true);if(ig.input.pressed('keyX')||ig.input.pressed('keyC')||ig.input.pressed('keyZ'))
this.doShake();if(ig.Debug)
{if(ig.game.controlBall)
{if(ig.input.state('keyA'))
p.x-=8/Box2D.SCALE;if(ig.input.state('keyD'))
p.x+=8/Box2D.SCALE;if(ig.input.state('keyW'))
p.y-=8/Box2D.SCALE;if(ig.input.state('keyS'))
p.y+=8/Box2D.SCALE;this.b2Body.SetPosition(p);}}
if(this.pos.y+this.size.y*0.5>=ig.system.realHeight)
{this.soundGutter.play();if(ig.ua.android)
ig.gameTank.soundJockey.playSound('soundeffects','gutter');ig.game.lostBall(this);}},draw:function()
{if(!this.isHidden)
this.parent();},doShake:function()
{if(this._canShake&&!ig.gameTank.data.instructions)
{this._canShake=false;var vel=this.b2Body.GetLinearVelocity();if(ig.input.pressed('keyZ'))
vel.Add(new Box2D.Common.Math.b2Vec2(0,-20));else if(ig.input.pressed('keyX')||ig.input.pressed('keyC'))
vel.Add(new Box2D.Common.Math.b2Vec2(ig.input.pressed('keyX')?-this.shakeForce:this.shakeForce,Math.rand(-4,4,true)));else
vel.Add(new Box2D.Common.Math.b2Vec2(Math.rand(0,1)?-this.shakeForce:this.shakeForce,Math.rand(-4,4,true)));this.b2Body.SetAwake(true);this.b2Body.SetLinearVelocity(vel);ig.game.shake(this.shakeThreshold);setTimeout(function(){this._canShake=true}.bind(this),this.shakeThreshold*1000);}},scream:function(name)
{if(this.currentAnim==this.anims.electric)
return;this.currentAnim=this.anims[name||'scream'+Math.rand(1,3)];if(name=='electric')
this.b2Body.SetType(0);clearTimeout(this.timeoutId);this.timeoutId=setTimeout(function()
{if(name=='electric')
this.b2Body.SetType(2);this.currentAnim=this.anims.idle}.bind(this),1000)},canTeleport:function(){return Date.now()>this._teleportTime+(this.teleportThreshold*1000)},startTeleport:function(pos)
{this.usedTeleport=true;this._teleportTime=Date.now();this.b2Body.SetType(0);var v=this.b2Body.GetPosition();this.tween=TweenMax.to(v,0.25,{x:pos.x,y:pos.y,ease:Linear.easeNone,onUpdate:function()
{this.b2Body.SetPosition(v)}.bind(this)})},hide:function(){this.b2Body.SetType(0);this.isHidden=true},show:function(){this.b2Body.SetType(2);this.isHidden=false},beginContact:function()
{if(ig.gameTank.data.instructions)
return;var points=~~(ig.game.pointsTotal/this.soundIncrement)*this.soundIncrement;if(points>this._soundIncrementScore)
{this.soundHighScore.play();if(ig.ua.android)
ig.gameTank.soundJockey.playSound('soundeffects','highScore');this._soundIncrementScore=points;}
else
{if(Math.rand(0,10)>=1)
this['soundHit'+Math.rand(1,4)].play()
else
this['sound'+Math.rand(1,2)].play();if(ig.ua.android)
{if(Math.rand(0,10)>=1)
ig.gameTank.soundJockey.playSound('soundeffects','generalHit'+Math.rand(1,4));else
ig.gameTank.soundJockey.playSound('soundeffects','grunt'+Math.rand(1,2));}}}})})