ig.module('game.entities.pinball.teleport').requires('cm.entity').defines(function()
{entPinballTeleport=ig.Entity.extend({init:function(x,y,settings)
{var to=ig.game.tableOffset;this.parent(to.x+x,to.y+y,settings);if(this.radius)
{this.b2Body=ig.game._b2CreateCircle(this.pos.x-to.x,this.pos.y-to.y,this.radius);this.size.x=this.radius*2,this.size.y=this.radius*2;}
else
this.b2Body=ig.game._b2CreateBox(this.pos.x-to.x,this.pos.y-to.y,this.size.x,this.size.y);this.b2Body.GetFixtureList().SetSensor(true);this.b2Body.SetUserData(this);if(ig.Debug)
ig.input.on('mousedown',function(){this.selected=ig.game.controlBall&&this.inFocus()}.bind(this))},update:function()
{if(ig.Debug)
{if(this.b2Body)
{if(this.selected)
{var p=this.b2Body.GetPosition();if(ig.input.state('keyLeft'))
p.x-=1/Box2D.SCALE;if(ig.input.state('keyRight'))
p.x+=1/Box2D.SCALE;if(ig.input.state('keyUp'))
p.y-=1/Box2D.SCALE;if(ig.input.state('keyDown'))
p.y+=1/Box2D.SCALE;ig.show('x',((p.x*Box2D.SCALE)-ig.game.tableOffset.x).toFixed(1));ig.show('y',((p.y*Box2D.SCALE)-ig.game.tableOffset.y).toFixed(1));this.b2Body.SetPosition(p);}}}},beginContact:function(obj,objData)
{if(objData.name!='ball')
return;if(!objData.canTeleport())
return;var p=this.b2Body.GetPosition(),x=p.x,y=p.y;if(this.name=='teleport_counter')
y-=1;else if(this.name=='teleport_fridge')
x+=0.2,y-=1;objData.startTeleport(new Box2D.Common.Math.b2Vec2(x,y));setTimeout(function()
{var ent=ig.game.getEntityByName(this.goto);x=Math.rand(this.dirx[0],this.dirx[1]);y=Math.rand(this.diry[0],this.diry[1]);objData.show();obj.SetPosition(ent.b2Body.GetPosition());obj.SetLinearVelocity(new Box2D.Common.Math.b2Vec2(x,y));}.bind(this),1000);}})})