ig.module('game.entities.pinball.trigger').requires('cm.entity').defines(function()
{entPinballTrigger=ig.Entity.extend({crashObj:null,count:-1,onCrash:function(){},destruction:false,comboGroup:false,b2Body:null,init:function(x,y,settings)
{var to=ig.game.tableOffset;this.parent(to.x+x,to.y+y,settings);if(this.radius)
{this.b2Body=ig.game._b2CreateCircle(this.pos.x-to.x,this.pos.y-to.y,this.radius);this.size={x:this.radius*2,y:this.radius*2};}
else
this.b2Body=ig.game._b2CreateBox(this.pos.x-to.x,this.pos.y-to.y,this.size.x,this.size.y,this.angle||0);this.b2Body.GetFixtureList().SetSensor(true);this.b2Body.SetUserData(this);if(this.destruction)
ig.game.destructionTotal++;if(this.comboGroup)
ig.game.addComboGroup(this);if(ig.Debug)
ig.input.on('mousedown',function(){this.selected=ig.game.controlBall&&this.inFocus()}.bind(this))},update:function()
{if(ig.Debug)
{if(this.b2Body)
{if(this.selected)
{var p=this.b2Body.GetPosition();if(ig.input.state('keyLeft'))
p.x-=1/Box2D.SCALE;if(ig.input.state('keyRight'))
p.x+=1/Box2D.SCALE;if(ig.input.state('keyUp'))
p.y-=1/Box2D.SCALE;if(ig.input.state('keyDown'))
p.y+=1/Box2D.SCALE;ig.show('x',((p.x*Box2D.SCALE)-ig.game.tableOffset.x).toFixed(1));ig.show('y',((p.y*Box2D.SCALE)-ig.game.tableOffset.y).toFixed(1));this.b2Body.SetPosition(p);}}}
if(this.crashObj)
{this.onCrash(this.crashObj);this.crashObj=null;if(this.destruction)
ig.game.destructionCheck(this);if(this.comboGroup)
ig.game.checkComboGroup(this);this.count--;if(this.count==0)
{ig.game.b2World.DestroyBody(this.b2Body);ig.game.removeEntity(this);}}},beginContact:function(obj,objData)
{if(objData.name!='ball')
return;this.crashObj=obj;},endContact:function(){}})})