var TEXT_GAMEOVER   = "GAME OVER!";
var TEXT_SCORE      = "SCORE";
var TEXT_STAGE      = "STAGE";
var TEXT_BEST_SCORE = "BEST SCORE";
var TEXT_BEST = "BEST";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_SELECT_TEAM = "SELECT A TEAM";

var TEXT_WIDE_RIGHT = "WIDE RIGHT!";
var TEXT_WIDE_LEFT = "WIDE LEFT!";
var TEXT_CENTER_NULL = "POLE HIT!";
var TEXT_CENTER_RED = "NOT BAD!";
var TEXT_CENTER_YELLOW = "GOOD!";
var TEXT_CENTER_GREEN = "SUPER!";
var TEXT_LOADING = "LOADING...";

var TEXT_HELP1     = "PRESS SPACEBAR TO CHOOSE THE POINT WHERE KICKING THE BALL";
var TEXT_HELP1_MOB = "TAP ON THE SCREEN TO CHOOSE THE POINT WHERE KICKING THE BALL";

var TEXT_HELP2     = "CENTER THE GREEN AREA TO GET THE TOP SCORE!";
var TEXT_PRELOADER_CONTINUE = "START";

var TEAM_NAMES = new Array();
TEAM_NAMES[0] = "ARGENTINA";
TEAM_NAMES[1] = "AUSTRALIA";
TEAM_NAMES[2] = "FIJI";
TEAM_NAMES[3] = "FRANCE";
TEAM_NAMES[4] = "WALES";
TEAM_NAMES[5] = "JAPAN";
TEAM_NAMES[6] = "ENGLAND";
TEAM_NAMES[7] = "IRELAND";
TEAM_NAMES[8] = "NEW ZEALAND";
TEAM_NAMES[9] = "SCOTLAND";
TEAM_NAMES[10] = "SOUTH AFRICA";
TEAM_NAMES[11] = "URUGUAY";

var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";