var CANVAS_WIDTH = 640;
var CANVAS_HEIGHT = 1024;

var EDGEBOARD_X = 16;
var EDGEBOARD_Y = 110;

var FPS           = 30;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var PREFIX_LOCAL_STORAGE = "rugby_kicks_";

var PRIMARY_FONT = "impact";

var SPACE_BAR = 32;
var LEFT      = 37;
var RIGHT     = 39;
var UP        = 38;
var DOWN      = 40;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_SELECT_TEAM = 2;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_END_SELECT_ANIM = 6;
var ON_END_LOADING = 7;
var ON_BUT_NO_DOWN = 8;
var ON_BUT_YES_DOWN = 9;

var HORIZONTAL_SELECTION_STATE = 0;
var VERTICAL_SELECTION_STATE = 1;
var SHOT_SELECTION_STATE = 2;

var NULL_TARGET_RIGHT = -3;
var NULL_TARGET_LEFT = -2;
var NULL_TARGET_POLE = -1;
var RED_TARGET = 0;
var YELLOW_TARGET = 1;
var GREEN_TARGET = 2;

var NUM_STAGES = 5;
var NUM_TEAMS = 12;
var BALL_FLYTIME = 2500;
var BALL_MAX_ROTATION = 30;

var SHOT_INDICATOR_SPEED;
var DECREASE_SHOT_INDICATOR_SPEED;

var SHOTS_PER_STAGE;

var RED_AREA_POINTS;
var YELLOW_AREA_POINTS;
var GREEN_AREA_POINTS;

var SOUNDTRACK_VOLUME_IN_GAME = 0.1;
var AD_SHOW_COUNTER;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;