ig.module('cm.button').requires('cm.input','cm.entity').defines(function()
{ig.Button=ig.Entity.extend({isFocused:false,isActive:true,isMouseDown:false,init:function(x,y,settings)
{this.parent(x,y,settings);ig.input.on('mousemove',this._onMouseMove.bind(this));ig.input.on('mousedown',this._onMouseDown.bind(this));ig.input.on('mouseup',this._onMouseUp.bind(this));},kill:function()
{this.isFocused=false;this.isActive=false;this.isMouseDown=false;this.parent();},_onMouseMove:function()
{if(!this.isActive)
return;var flag=this.inFocus();if(flag&&!this.isFocused)
this.onMouseOver();if(!flag&&this.isFocused)
this.onMouseOut();if(flag&&this.isMouseDown)
this.onHold();this.isFocused=flag;},_onMouseDown:function()
{if(!this.isActive)
return;if(this.inFocus())
{this.isMouseDown=true;this.onPressed();}},_onMouseUp:function()
{if(!this.isActive)
return;this.isMouseDown=false;if(this.inFocus())
this.onReleased();},onPressed:function(){},onHold:function(){},onReleased:function(){},onMouseOver:function(){},onMouseOut:function(){}})})