AvalancheSnowboarding.PlayerObject=function(){}
Utils.extend(AvalancheSnowboarding.PlayerObject,AbstractGameObject);AvalancheSnowboarding.PlayerObject.prototype.init=function(data){this.constructor.superclass.init.call(this,data);this.gameScene=data.gameScene;this.distanceTotal=data.distanceTotal;this.distance=0;this.xDirection=0;this.xStep=0;this.xStepMax=2;this.xStepMin=-2;this.xStepAcceleration=this.xStepMax/10;this.xPreviousStep=0;this.previousFrameIndex=0;this.isShiftEnabled=false;this.leftBound=new Phaser.Point(230,317);this.rightBound=new Phaser.Point(316,140);this.isHitByAvalanche=false;this.isBlinking=false;this.isJumpingFromPlatform=false;this.isFinishLineCrossed=false;this.isWinAnimationStarted=false;this.speed=null;this.speedFastFrameCounter=0;this.setSpeed(AvalancheSnowboarding.C.speedNormal);this.animationAnchors={stand:{x:64/106,y:72/96},impulse:{x:68/174,y:116/136},goE:{x:73/144,y:75/103},goEtoN:{x:45/114,y:62/84},goNtoE:{x:45/114,y:62/84},goN:{x:49/118,y:65/89},goEtoS:{x:30/88,y:75/114},goStoE:{x:30/88,y:75/114},goS:{x:42/107,y:71/126},stumble:{x:50/117,y:95/120},fall:{x:58/151,y:129/174},jumpWhenRespawn:{x:56/88,y:80/103},jumpWhenHitPlatform:{x:56/88,y:80/103},jumpAfterAction:{x:56/88,y:80/103},badFall:{x:40/93,y:69/101},badLand:{x:34/127,y:70/126},twisterWithShadow:{x:26/130,y:68/124},twister1:{x:43/130,y:69/107},twister2:{x:43/130,y:69/107},action1:{x:39/111,y:81/111},action2:{x:39/84,y:78/101},action3:{x:39/135,y:73/96},action4:{x:78/172,y:68/97},arrive:{x:100/174,y:111/136},win:{x:127/123,y:111/130},};this.view.anchor.setTo(0.5,1);this.view.body.setSize(30,27,-1,5);this.playerStand=this.view.animations.add('stand',Phaser.Animation.generateFrameNames('M_Player_Stand',1,8,'.png',4),30,true);this.playerImpulse=this.view.animations.add('impulse',Phaser.Animation.generateFrameNames('M_Player_Impulse',1,15,'.png',4),30,false);this.playerImpulse.onStart.add(function(){if(!this.game.sound.mute)
this.audioTaz1.play();},this);this.playerImpulse.onComplete.add(function(){this.switchAnimation('goE');this.isShiftEnabled=true;},this);this.playerGoE=this.view.animations.add('goE',Phaser.Animation.generateFrameNames('M_Player_GoE',1,12,'.png',4),30,true);this.playerGoEtoN=this.view.animations.add('goEtoN',Phaser.Animation.generateFrameNames('M_Player_GoEtoN',1,3,'.png',4),30,false);this.playerGoEtoN.onComplete.add(function(){this.switchAnimation('goN');},this);this.playerGoN=this.view.animations.add('goN',Phaser.Animation.generateFrameNames('M_Player_GoN',1,12,'.png',4),30,true);this.playerGoNtoE=this.view.animations.add('goNtoE',Phaser.Animation.generateFrameNames('M_Player_GoEtoN',3,1,'.png',4),30,false);this.playerGoNtoE.onComplete.add(function(){this.switchAnimation('goE');},this);this.playerGoEtoS=this.view.animations.add('goEtoS',Phaser.Animation.generateFrameNames('M_Player_GoEtoS',1,3,'.png',4),30,false);this.playerGoEtoS.onComplete.add(function(){this.switchAnimation('goS');},this);this.playerGoS=this.view.animations.add('goS',Phaser.Animation.generateFrameNames('M_Player_GoS',1,12,'.png',4),30,true);this.playerGoStoE=this.view.animations.add('goStoE',Phaser.Animation.generateFrameNames('M_Player_GoEtoS',3,1,'.png',4),30,false);this.playerGoStoE.onComplete.add(function(){this.switchAnimation('goE');},this);this.playerStumble=this.view.animations.add('stumble',Phaser.Animation.generateFrameNames('M_Player_Stumble',1,31,'.png',4),30,false);this.playerStumble.onStart.add(function(){this.setSpeed(AvalancheSnowboarding.C.speedStumble);this.isShiftEnabled=false;if(!this.game.sound.mute)
this.audioFall2.play();},this);this.playerStumble.onComplete.add(function(){this.switchAnimation('goE');this.setSpeed(AvalancheSnowboarding.C.speedNormal);this.isShiftEnabled=true;},this);this.playerFall=this.view.animations.add('fall',Phaser.Animation.generateFrameNames('M_Player_Fall',1,38,'.png',4),30,true);this.playerFall.enableUpdate=true;this.playerFall.updateCounter=0;this.playerFall.onUpdate.add(function(sprite,frame){this.playerFall.updateCounter++;if(this.playerFall.updateCounter==20){this.fallAnimationCompleteHandler();}},this);this.playerJumpWhenRespawn=this.view.animations.add('jumpWhenRespawn',Phaser.Animation.generateFrameNames('M_Player_Jump',1,14,'.png',4),30,false);this.playerJumpWhenRespawn.onComplete.add(function(sprite,animation){},this);this.playerJumpWhenHitPlatform=this.view.animations.add('jumpWhenHitPlatform',Phaser.Animation.generateFrameNames('M_Player_Jump',1,14,'.png',4),30,false);this.playerJumpWhenHitPlatform.onStart.add(function(){if(!this.game.sound.mute)
this.audioJump.play();},this);this.playerJumpAfterAction=this.view.animations.add('jumpAfterAction',Phaser.Animation.generateFrameNames('M_Player_Jump',1,14,'.png',4),30,false);this.playerBadFall=this.view.animations.add('badFall',Phaser.Animation.generateFrameNames('M_DDRPlayer_BadFall',1,19,'.png',4),30,false);this.playerBadFall.onComplete.add(function(){this.switchAnimation('badLand');},this);this.playerBadLand=this.view.animations.add('badLand',Phaser.Animation.generateFrameNames('M_DDRPlayer_BadLand',1,20,'.png',4),30,false);this.playerBadLand.onStart.add(function(){if(!this.game.sound.mute)
this.audioFall2.play();},this);this.playerBadLand.onComplete.add(function(){this.switchAnimation('twisterWithShadow');},this);this.playerTwisterWithShadow=this.view.animations.add('twisterWithShadow',Phaser.Animation.generateFrameNames('M_DDRPlayer_TwisterWithShadow',1,18,'.png',4),30,false);this.playerTwisterWithShadow.onStart.add(function(){if(!this.game.sound.mute)
this.audioTwister.play();},this);this.playerTwisterWithShadow.onComplete.add(function(){this.jumpDownAnimationCompleteHandler();},this);this.playerTwister1=this.view.animations.add('twister1',Phaser.Animation.generateFrameNames('M_DDRPlayer_Twister',1,18,'.png',4),30,false);this.playerTwister1.onStart.add(function(){if(!this.game.sound.mute)
this.audioTwister.play();},this);this.playerTwister1.onComplete.add(function(){var action='action'+String(Utils.getRand(1,4));this.switchAnimation(action);if(!this.game.sound.mute)
this['audioTaz'+Utils.getRand(1,3)].play();},this);this.playerTwister2=this.view.animations.add('twister2',Phaser.Animation.generateFrameNames('M_DDRPlayer_Twister',1,18,'.png',4),30,false);this.playerTwister2.onStart.add(function(){if(!this.game.sound.mute)
this.audioTwister.play();},this);this.playerTwister2.onComplete.add(function(){this.switchAnimation('jumpAfterAction');if(!this.game.sound.mute)
this.audioCheer.play();},this);this.playerAction1=this.view.animations.add('action1',Phaser.Animation.generateFrameNames('M_DDRPlayer_Action1',1,40,'.png',4),30,false);this.playerAction1.onComplete.add(function(){this.switchAnimation('twister2');},this);this.playerAction2=this.view.animations.add('action2',Phaser.Animation.generateFrameNames('M_DDRPlayer_Action2',1,40,'.png',4),30,false);this.playerAction2.onComplete.add(function(){this.switchAnimation('twister2');},this);this.playerAction3=this.view.animations.add('action3',Phaser.Animation.generateFrameNames('M_DDRPlayer_Action3',1,28,'.png',4),30,false);this.playerAction3.onComplete.add(function(){this.switchAnimation('twister2');},this);this.playerAction4=this.view.animations.add('action4',Phaser.Animation.generateFrameNames('M_DDRPlayer_Action4',1,65,'.png',4),30,false);this.playerAction4.onComplete.add(function(){this.switchAnimation('twister2');},this);this.playerArrive=this.view.animations.add('arrive',Phaser.Animation.generateFrameNames('M_Player_Arriving',1,15,'.png',4),30,false);this.playerArrive.onStart.add(function(){if(!this.game.sound.mute)
this.audioCheer.play();var timerTween=this.game.add.tween({}).to({},3000).start();timerTween.onComplete.addOnce(function(){this.gameScene.gotoWin();},this);},this);this.playerArrive.onComplete.add(function(){this.switchAnimation('win');},this);this.playerWin=this.view.animations.add('win',Phaser.Animation.generateFrameNames('M_Player_Win',1,15,'.png',4),30,true);this.playerWin.onComplete.add(function(){},this);this.audioDoubleJolt=this.game.add.audio('doublejolt');this.audioFall2=this.game.add.audio('fall2');this.audioJolt=this.game.add.audio('jolt');this.audioJump=this.game.add.audio('jump');this.audioTwister=this.game.add.audio('twister');this.audioTaz1=this.game.add.audio('taz1');this.audioTaz2=this.game.add.audio('taz2');this.audioTaz3=this.game.add.audio('taz3');this.audioTurn=this.game.add.audio('turn');this.audioCheer=this.game.add.audio('cheer');this.switchAnimation('stand');},AvalancheSnowboarding.PlayerObject.prototype.run=function(){this.switchAnimation('impulse');},AvalancheSnowboarding.PlayerObject.prototype.setSpeed=function(speed){if(speed==AvalancheSnowboarding.C.speedFast){this.speedFastFrameCounter=0;}
if(speed!=this.speed){this.speed=speed;}}
AvalancheSnowboarding.PlayerObject.prototype.shiftLeft=function(){this.shift(-1);},AvalancheSnowboarding.PlayerObject.prototype.shiftRight=function(){this.shift(1);},AvalancheSnowboarding.PlayerObject.prototype.shift=function(xDirection){if(this.isShiftEnabled&&!this.isHitByAvalanche&&!this.isJumpingFromPlatform){if(Phaser.Math.sign(this.xDirection*xDirection)==-1){this.xStep/=2;}
this.xDirection=Phaser.Math.sign(xDirection);}},AvalancheSnowboarding.PlayerObject.prototype.jumpUp=function(){this.speedBeforeJump=this.speed;var avalancheSpeed=AvalancheSnowboarding.C.createSpeedObject(this.speed.linear+AvalancheSnowboarding.C.avalancheSpeedLinearDelta);this.gameScene.slope.avalanche.setSpeed(avalancheSpeed);this.isJumpingFromPlatform=true;this.isShiftEnabled=true;var playerFinalX=this.game.world.width*0.4;var playerFinalY=-this.game.world.height*0.75;this.jumpUpTweenData={target:this.view,xInitial:this.view.x,yInitial:this.view.y,xBy:playerFinalX-this.view.x,yBy:playerFinalY-this.view.y,ease:AvalancheSnowboarding.C.easeOut,framesTotal:0.4*60,context:this,onComplete:function(that){that.jumpUpTweenData=null;},}}
AvalancheSnowboarding.PlayerObject.prototype.jumpDown=function(){this.jumpDownTweenData={target:this.view,xInitial:this.view.x,yInitial:this.view.y,xBy:this.data.x-this.view.x,yBy:this.data.y-this.view.y,ease:AvalancheSnowboarding.C.easeIn,framesTotal:0.4*60,context:this,onComplete:function(that){that.jumpDownTweenData=null;if(AvalancheSnowboarding.Model.wasPreviousArrowGameWon){that.jumpDownAnimationCompleteHandler();var extraScore=200*AvalancheSnowboarding.Model.numArrowsInPreviousArrowGame;that.gameScene.hud.addScore(extraScore,that.view.x+40,that.view.y);that.blink();}else{that.setSpeed(AvalancheSnowboarding.C.speedNone);that.gameScene.slope.avalanche.setSpeed(AvalancheSnowboarding.C.speedNone);if(that.speedBeforeJump!=AvalancheSnowboarding.C.speedFast){that.gameScene.slope.avalanche.setSpeed(AvalancheSnowboarding.C.avalancheSpeedNormal);}}},}}
AvalancheSnowboarding.PlayerObject.prototype.jumpDownAnimationCompleteHandler=function(){this.switchAnimation('goE');this.setSpeed(AvalancheSnowboarding.C.speedNormal);this.gameScene.slope.avalanche.setSpeed(AvalancheSnowboarding.C.avalancheSpeedNormal);this.isJumpingFromPlatform=false;this.speedBeforeJump=null;}
AvalancheSnowboarding.PlayerObject.prototype.move=function(){var anim=this.view.animations.currentAnim;this.distance+=this.speed.linear;if(this.isHitByAvalanche){if(this.fallTweenData!=null){AvalancheSnowboarding.C.processTween(this.fallTweenData);}else if(this.respawnTweenData1!=null){AvalancheSnowboarding.C.processTween(this.respawnTweenData1);}else if(this.respawnTweenData2!=null){AvalancheSnowboarding.C.processTween(this.respawnTweenData2);}}else if(this.isJumpingFromPlatform){if(this.jumpUpTweenData!=null){AvalancheSnowboarding.C.processTween(this.jumpUpTweenData);}else if(this.jumpDownTweenData!=null){AvalancheSnowboarding.C.processTween(this.jumpDownTweenData);}}
var isKeyPressed=this.xDirection!=0;var isDirectionChanged=Phaser.Math.sign(this.xPreviousDirection*this.xDirection)<0;var canMoveBasedOnAnimation=(this.xDirection<0&&anim!=this.playerGoEtoN&&anim!=this.playerGoN)||(this.xDirection>0&&anim!=this.playerGoEtoS&&anim!=this.playerGoS);var canMoveBasedOnPosition=(this.xDirection<0&&this.view.x>this.leftBound.x)||(this.xDirection>0&&this.view.x<this.rightBound.x);if(!this.isHitByAvalanche&&!this.isJumpingFromPlatform&&!this.isFinishLineCrossed){if(isKeyPressed&&canMoveBasedOnAnimation&&canMoveBasedOnPosition){this.xStep+=this.xStepAcceleration*this.xDirection;this.xStep=Phaser.Math.max(this.xStepMin,Phaser.Math.min(this.xStep,this.xStepMax));}else{var xLastStep=this.xStep;this.xStep-=Phaser.Math.sign(this.xStep)*this.xStepAcceleration;if(Phaser.Math.sign(xLastStep*this.xStep)==-1){this.xStep=0;}}
var isStepIncreasing=(this.xPreviousStep<this.xStep&&this.xStep>0)||(this.xPreviousStep>this.xStep&&this.xStep<0);if(anim==this.playerGoE&&((this.xPreviousStep==0&&this.xStep!=0)||Phaser.Math.sign(this.xPreviousStep*this.xStep)>0)){if(isStepIncreasing){this.switchAnimation(this.xStep>0?'goEtoN':'goEtoS');if(!this.game.sound.mute&&(!this.audioTurn.isPlaying||this.audioTurn.currentTime>=this.audioTurn.durationMS/3))
this.audioTurn.play();}}else if(!isKeyPressed||!canMoveBasedOnPosition){if((anim==this.playerGoEtoN||anim==this.playerGoEtoS)&&(anim.currentFrame.index>=this.previousFrameIndex+2)){this.switchAnimation('goE');}else if(anim==this.playerGoN){this.switchAnimation('goNtoE');}else if(anim==this.playerGoS){this.switchAnimation('goStoE');}}else if(isKeyPressed){if(anim==this.playerGoN&&this.xDirection<0){this.switchAnimation('goNtoE');}else if(anim==this.playerGoS&&this.xDirection>0){this.switchAnimation('goStoE');}}
this.view.x+=this.xStep;this.view.x=this.view.x<this.leftBound.x?this.leftBound.x:this.view.x;this.view.x=this.view.x>this.rightBound.x?this.rightBound.x:this.view.x;this.view.y=this.calculateY(this.view.x);}
if(this.speed==AvalancheSnowboarding.C.speedFast){this.speedFastFrameCounter++;if(this.speedFastFrameCounter>AvalancheSnowboarding.C.speedFastDurationInFrames){this.setSpeed(AvalancheSnowboarding.C.speedNormal);}}
this.xPreviousStep=this.xStep;this.previousFrameIndex=anim.currentFrame.index;this.xDirectionPrevious=this.xDirection;this.xDirection=0;},AvalancheSnowboarding.PlayerObject.prototype.fall=function(){this.isHitByAvalanche=true;if(this.speed!=AvalancheSnowboarding.C.speedNone){this.switchAnimation('fall');}else{this.fallAnimationCompleteHandler();}
if(!this.game.sound.mute){this.audioFall2.play();this.audioDoubleJolt.play();}},AvalancheSnowboarding.PlayerObject.prototype.fallAnimationCompleteHandler=function(){this.view.parent.swap(this.view,this.view.parent.avalanche);var horizontal=this.view.x+this.view.width;this.fallTweenData={target:this.view,xInitial:this.view.x,yInitial:this.view.y,xBy:AvalancheSnowboarding.C.speedVector.x*horizontal,yBy:AvalancheSnowboarding.C.speedVector.y*horizontal,ease:AvalancheSnowboarding.C.easeIn,framesTotal:1.2*60,context:this,onComplete:function(that){that.fallTweenData=null;var hasUsedHeart=that.gameScene.hud.useHeart();if(!hasUsedHeart){that.gameScene.gotoLose();return;}
that.view.x=that.data.x+150*AvalancheSnowboarding.C.speedVector.x;that.view.y=that.data.y+150*AvalancheSnowboarding.C.speedVector.y;var avalancheSpeed=AvalancheSnowboarding.C.createSpeedObject(that.speed.linear+AvalancheSnowboarding.C.avalancheSpeedLinearDelta);that.gameScene.slope.avalanche.setSpeed(avalancheSpeed);that.view.parent.swap(that.view,that.view.parent.avalanche);that.switchAnimation('jumpWhenRespawn');that.setSpeed(AvalancheSnowboarding.C.speedFast);that.respawnTweenData1={target:that.view,xInitial:that.view.x,yInitial:that.view.y,xBy:that.data.x+90-that.view.x,yBy:that.data.y-200-that.view.y,ease:AvalancheSnowboarding.C.easeOut,framesTotal:0.6*60,context:that,onComplete:function(that){that.respawnTweenData1=null;that.respawnTweenData2={target:that.view,xInitial:that.view.x,yInitial:that.view.y,xBy:that.data.x-that.view.x,yBy:that.data.y-that.view.y,ease:AvalancheSnowboarding.C.easeIn,framesTotal:0.3*60,context:that,onComplete:function(that){that.respawnTweenData2=null;that.switchAnimation('goE');that.isHitByAvalanche=false;that.isShiftEnabled=true;that.setSpeed(AvalancheSnowboarding.C.speedNormal);that.gameScene.slope.avalanche.setSpeed(AvalancheSnowboarding.C.avalancheSpeedNormal);that.blink();},};},};},};}
AvalancheSnowboarding.PlayerObject.prototype.blink=function(){this.isBlinking=true;this.blinkTween=this.game.add.tween(this.view).to({},300,'Linear',true,0,12);this.blinkTween.onLoop.add(function(){this.view.visible=!this.view.visible;},this);this.blinkTween.onComplete.addOnce(function(){this.blinkTween.onLoop.removeAll();this.blinkTween.onComplete.removeAll();this.blinkTween=null;this.isBlinking=false;},this);}
AvalancheSnowboarding.PlayerObject.prototype.switchAnimation=function(animationName){if(animationName=='fall'){this.playerFall.updateCounter=0;}
this.view.play(animationName);if(!this.animationAnchors.hasOwnProperty(animationName)){console.error('No animation anchors defined for animationName='+animationName);}else{var anchor=this.animationAnchors[animationName];this.view.anchor.setTo(anchor.x,anchor.y);}},AvalancheSnowboarding.PlayerObject.prototype.calculateY=function(x){var a=this.leftBound;var b=this.rightBound;return(b.y-a.y)/(b.x-a.x)*(x-a.x)+a.y;},AvalancheSnowboarding.PlayerObject.prototype.destroy=function(){if(this.audioDoubleJolt!=null){this.audioDoubleJolt.stop();this.audioDoubleJolt=null;}
if(this.audioFall2!=null){this.audioFall2.stop();this.audioFall2=null;}
if(this.audioJolt!=null){this.audioJolt.stop();this.audioJolt=null;}
if(this.audioJump!=null){this.audioJump.stop();this.audioJump=null;}
if(this.audioTwister!=null){this.audioTwister.stop();this.audioTwister=null;}
if(this.audioTaz1!=null){this.audioTaz1.stop();this.audioTaz1=null;}
if(this.audioTaz2!=null){this.audioTaz2.stop();this.audioTaz2=null;}
if(this.audioTaz3!=null){this.audioTaz3.stop();this.audioTaz3=null;}
if(this.audioTurn!=null){this.audioTurn.stop();this.audioTurn=null;}
if(this.audioCheer!=null){this.audioCheer.stop();this.audioCheer=null;}
if(this.fallTween){this.fallTween.onComplete.removeAll();this.fallTween.stop();this.fallTween=null;}
if(this.blinkTween){this.blinkTween.onLoop.removeAll();this.blinkTween.onComplete.removeAll();this.blinkTween.stop();this.blinkTween=null;}
AbstractGameObject.prototype.destroy.call(this);}