var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_GAMEOVER  = "GAME OVER";
var TEXT_SCORE     = "SCORE";
var TEXT_TOTAL_SCORE = "TOTAL SCORE";
var TEXT_ARE_SURE = "ARE YOU SURE?";

var TEXT_SELECT_WORLD = "PICK A BODY PART TO DEFEND";
var TEXT_SELECT_STAGE = "SELECT A STAGE";

var TEXT_VIRUS_TYPE = "VIRUS TYPE";
var TEXT_STAGE = "STAGE";

var TEXT_CONGRATULATION = "CONGRATULATIONS!";
var TEXT_DEFEATED = "YOU PASSED LEVEL";
var TEXT_INSTAGE = "IN STAGE";

var TEXT_DEFEATED_ALL = "YOU DEFEATED ALL VIRUSES!";


var TEXT_HELP1_MOB = "SWIPE TO MOVE IN FROM THE EDGE, AND BACK";
var TEXT_HELP2_MOB = "BEEN TOO BRAVE? TAP TO RETREAT!";
var TEXT_HELP1     = "MOVE BRAINY IN FROM THE EDGE, AND BACK";
var TEXT_HELP2     = "PRESS SPACE TO CAPTURE TERRITORY";
var TEXT_HELP3     = "THE AREAS YOU RECLAIM WILL TURN HEALTHY AGAIN!";
var TEXT_HELP4     = "DON'T LET THE BUGS TOUCH YOU OR YOUR LINE!";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";