var CANVAS_WIDTH = 640;
var CANVAS_HEIGHT = 1024; 

var EDGEBOARD_X = 16;
var EDGEBOARD_Y = 110;

var FPS = 30;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "walibi";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_CONTROLLER_END    = 8;
var ON_CONTROLLER_REMOVE = 9;
var ON_CONTROLLER_ROLL = 10;

var LEFT_DIRECTION = 0;
var UP_DIRECTION = 1;
var RIGHT_DIRECTION = 2;
var DOWN_DIRECTION = 3;

var MOVEMENT_STOP = -1;
var MOVEMENT_RANDOM = 0;
var MOVEMENT_LINEAR = 1;
var MOVEMENT_DISCRETE = 2;
var MOVEMENT_CIRCULAR = 3;

var STAGE_PER_WORLD = 3;
var STAGE_ANIM_COLOR = ["#ec297b", "#ec1c24", "#c1e401", "#f9ec31"];

var BORDER_LINE_DIM = 3;
var BORDER_WIDTH = 600;
var BORDER_HEIGHT = 600;
var BORDER_HEIGHT_OFFSET = 50;

var HERO_SPEED = [6,8,10];

var SPAWN_START_TIME = 9000; 
var SPAWN_TIMER = 40000;

var BOSS_MOVEMENT = new Array();
BOSS_MOVEMENT = [MOVEMENT_LINEAR, MOVEMENT_RANDOM, MOVEMENT_DISCRETE, MOVEMENT_CIRCULAR];

var SELECTED_SPEED;
var HERO_LIFE;

var WIN_QUOTE;

var VIRUS_SPEED = new Array();
var MAX_NUM_VIRUS_MINIONS = new Array();

var MINION_SCORE;

var SCORE_FIRST_STAR;
var SCORE_SECOND_STAR;
var SCORE_THIRD_STAR;

var AD_SHOW_COUNTER;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;