{
	"version": 1557417429,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/dragon-sheet0.png",
		"images/dragon-sheet1.png",
		"images/dragon-sheet2.png",
		"images/tile-sheet0.png",
		"images/gnashmeba-sheet0.png",
		"images/gnashimal-sheet0.png",
		"images/gnipper-sheet0.png",
		"images/sabretoothedgnasher-sheet0.png",
		"images/gnasher-sheet0.png",
		"images/egnormognash-sheet0.png",
		"images/gnashzilla-sheet0.png",
		"images/gnashizen-sheet0.png",
		"images/gnashraa-sheet0.png",
		"images/50stepsbutton-sheet0.png",
		"images/challengebutton-sheet0.png",
		"images/endlessbutton-sheet0.png",
		"images/clockicon-sheet0.png",
		"images/footicon-sheet0.png",
		"images/fbbutton-sheet0.png",
		"images/gnasherpediabutton-sheet0.png",
		"images/menubutton-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/soundbutton-sheet0.png",
		"images/soundbutton-sheet1.png",
		"images/twbutton-sheet0.png",
		"images/bg-sheet0.png",
		"images/bg-sheet1.png",
		"images/blackbg.png",
		"images/smoke-sheet0.png",
		"images/rotate-sheet0.png",
		"images/foottext.png",
		"images/gameoverpanel-sheet0.png",
		"images/highscoretext-sheet0.png",
		"images/score-sheet0.png",
		"images/title-sheet0.png",
		"images/latesttext-sheet0.png",
		"images/handicon-sheet0.png",
		"images/flag-sheet0.png",
		"images/loadicon-sheet0.png",
		"images/gnasherpediasprite-sheet0.png",
		"images/gnasherpediasprite-sheet1.png",
		"images/gnasherpediasprite-sheet2.png",
		"images/padlocksprite-sheet0.png",
		"images/speakericonsprite-sheet0.png",
		"images/upsprite-sheet0.png",
		"images/downsprite-sheet0.png",
		"images/bggame-sheet0.png",
		"images/gnashipediascroll-sheet0.png",
		"images/arrowkeysprite-sheet0.png",
		"images/tutorialbackdropboxsprite-sheet0.png",
		"images/yesimsurebutton-sheet0.png",
		"images/noimnotsurebutton-sheet0.png",
		"images/bone-sheet0.png",
		"images/backgroundsheet-sheet0.png",
		"images/instructionbackground-sheet0.png",
		"images/mutebutton-sheet0.png",
		"images/gnashevolutiontree-sheet0.png",
		"images/gameoverscroll-sheet0.png",
		"images/retrybutton-sheet0.png",
		"media/win.m4a",
		"media/win.ogg",
		"media/plop1.m4a",
		"media/plop1.ogg",
		"media/plop7.m4a",
		"media/plop7.ogg",
		"media/1 - gnashmoeba es_suction plop 1 - sfx producer.m4a",
		"media/1 - gnashmoeba es_suction plop 1 - sfx producer.ogg",
		"media/10 - gnashizen es_percussion accent 2 - sfx producer.m4a",
		"media/10 - gnashizen es_percussion accent 2 - sfx producer.ogg",
		"media/11 - gnashra es_prel shimmer swell 14 - sfx producer.m4a",
		"media/11 - gnashra es_prel shimmer swell 14 - sfx producer.ogg",
		"media/2 - gnish es_water splash throw 2 - sfx producer.m4a",
		"media/2 - gnish es_water splash throw 2 - sfx producer.ogg",
		"media/3 - gnizard es_dirt sand scrape - sfx producer.m4a",
		"media/3 - gnizard es_dirt sand scrape - sfx producer.ogg",
		"media/4 - gnashmal es_monster small animal 1 - sfx producer.m4a",
		"media/4 - gnashmal es_monster small animal 1 - sfx producer.ogg",
		"media/5 - sabretooth gnash es_lion growl short - sfx producer.m4a",
		"media/5 - sabretooth gnash es_lion growl short - sfx producer.ogg",
		"media/6 - gnipper es_squeaky toy single 3 - sfx producer.m4a",
		"media/6 - gnipper es_squeaky toy single 3 - sfx producer.ogg",
		"media/7 - gnasher es_dog bark 1 - sfx producer.m4a",
		"media/7 - gnasher es_dog bark 1 - sfx producer.ogg",
		"media/8 - enormognash es_timpani hit 10 - sfx producer.m4a",
		"media/8 - enormognash es_timpani hit 10 - sfx producer.ogg",
		"media/9 - gnashzilla es_monster growl 2 - sfx producer.m4a",
		"media/9 - gnashzilla es_monster growl 2 - sfx producer.ogg",
		"media/soundtrack - es_the odyssey ahead - dream cave.m4a",
		"media/soundtrack - es_the odyssey ahead - dream cave.ogg",
		"media/game over sound.m4a",
		"media/game over sound.ogg",
		"media/gnizard 2.m4a",
		"media/gnizard 2.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"config.json",
		"penumbra.png"
	]
}