window['switStrings'] = {
	"STR_REP_LOADING_PRELOAD_FONT_4": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_3": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_2": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_1": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PERCENT": {"value": "N%", "locID": ""},
	"STR_REP_POPUP_PAUSE_TITLE": {"value": "PAUSE", "locID": "STR_REP_POPUP_PAUSE_TITLE"},
	"STR_REP_POPUP_RESET_TITLE": {"value": "RESET", "locID": "STR_REP_POPUP_RESET_TITLE"},
	"STR_REP_POPUP_QUIT_TITLE": {"value": "QUIT GAME", "locID": "STR_REP_POPUP_RESET_TITLE"},
	"STR_REP_POPUP_CONFIRM_TITLE": {"value": "CONFIRM", "locID": "STR_REP_POPUP_RESET_TITLE"},
	"STR_REP_POPUP_CONFIRM_INFO": {"value": "Are you sure?", "locID": ""},
	"STR_REP_MESSAGE_START": {"value": "START!", "locID": "STR_REP_MESSAGE_LEVEL_COMPLETE"},
	"STR_REP_MESSAGE_TIMEUP": {"value": "TIME UP", "locID": "STR_REP_MESSAGE_LEVEL_COMPLETE"},
	"STR_REP_MESSAGE_MISSION": {"value": "MISSION #", "locID": "STR_REP_MESSAGE_LEVEL_COMPLETE"},
	"STR_REP_MESSAGE_MISSIONCOMPLETE": {"value": "MISSION COMPLETE", "locID": "STR_REP_MESSAGE_LEVEL_COMPLETE"},
	"STR_REP_MESSAGE_LEVEL": {"value": "LEVEL #", "locID": "STR_REP_MESSAGE_LEVEL_COMPLETE"},
	"STR_REP_HUD_TIME": {"value": "00:00", "locID": "STR_REP_HUD_TIME"},
	"STR_REP_METAMAP_TITLE": {"value": "LEVEL SELECTION", "locID": "STR_REP_METAMAP_TITLE"},
	"STR_REP_ENDLEVEL_TITLE": {"value": "MISSION COMPLETE", "locID": "STR_REP_ENDLEVEL_TITLE"},
	"STR_REP_ENDLEVEL_TOKEN_COUNTER": {"value": "# / %", "locID": "STR_REP_ENDLEVEL_TOKEN_COUNTER"},
	"STR_ENDLEVEL_TIMER_COUNTER": {"value": "00:00", "locID": ""},
	"STR_REP_METAMAP_LVL_01": {"value": "01", "locID": "STR_REP_METAMAP_LVL_01"},
	"STR_REP_TRYAGAIN_TITLE": {"value": "DON'T GIVE UP!", "locID": ""},
	"STR_REP_ACHIEVEMENTS_TITLE": {"value": "ACHIEVEMENTS", "locID": "STR_REP_ACHIEVEMENTS_TITLE"},
	"STR_REP_ENDGAME_TITLE": {"value": "MISSION COMPLETE", "locID": ""},
	"STR_REP_ENDGAME_MESSAGE": {"value": "CONGRATULATIONS!", "locID": "STR_REP_ENDGAME_MESSAGE"},
	"STR_REP_ENDGAME_TOKEN_COUNTER": {"value": "# / %", "locID": "STR_REP_ENDGAME_TOKEN_COUNTER"},
	"STR_REP_SCREEN_TITLE_TROPHY01": {"value": "MARTIAL ARTIST", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_TITLE_TROPHY02": {"value": "ROCKIN' RUFUS", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_TITLE_TROPHY03": {"value": "COMBAT EXPERT", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_TITLE_TROPHY04": {"value": "ATHENA BLITZ", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_TITLE_TROPHY05": {"value": "MISSION COMPLETE", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_TITLE_TROPHY06": {"value": "WHAT'S THE SITCH?", "locID": "STR_REP_SCREEN_TITLE_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY01": {"value": "Defeat # enemies", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY02": {"value": "Hack # times with Rufus", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY03": {"value": "Defeat # enemies", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY04": {"value": "Defeat Athena", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY05": {"value": "Beat the game", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_SCREEN_DESCRIPTION_TROPHY06": {"value": "Get all tokens", "locID": "STR_REP_SCREEN_DESCRIPTION_TROPHY01"},
	"STR_REP_DIALOG_CHARACTER_NAME01": {"value": "KIM", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME01_S": {"value": "KIM", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME02": {"value": "RON", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME02_S": {"value": "RON", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME03": {"value": "ATHENA", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME03_S": {"value": "ATHENA", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME04": {"value": "SHEGO", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME04_S": {"value": "SHEGO", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION01_1": {"value": "To move", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION01_1"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION01_2": {"value": "To jump", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION01_2"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION01": {"value": "Move with the left and right keys, jump with the up key", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION01"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION02_1": {"value": "To jump", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION02_1"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION02": {"value": "Defeat enemies by jumping over them", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION02"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION03_1": {"value": "To switch characters", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION03_1"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION03": {"value": "Press the spacebar to switch character", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION03"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION04_1": {"value": "To walljump", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION04_1"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION04": {"value": "Press jump while next to a wall as Kim to walljump", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION04"},
	"STR_REP_POPUP_HELP_PC_INSTRUCTION05_1": {"value": "To double jump", "locID": "STR_REP_POPUP_HELP_PC_INSTRUCTION05_1"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION05": {"value": "Press jump while in midair as Ron to double jump", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION05"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION06": {"value": "Press Z as Kim to use her grappling hook", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION06"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION07": {"value": "Press Z as Ron to hack into panels with Rufus", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION07"},
	"STR_REP_POPUP_HELP_PC_DESCRIPTION08": {"value": "Cut the correct wire before time runs out!", "locID": "STR_REP_POPUP_HELP_PC_DESCRIPTION08"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_1": {"value": "To move", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_1"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_2": {"value": "To jump", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_2"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION01": {"value": "Move by dragging across the left side of the screen", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION01"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION01_2": {"value": "jump by tapping the right side of the screen", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION01"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION02_1": {"value": "To jump", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION03_1"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION02": {"value": "Defeat enemies by jumping over them", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION03"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION03_1": {"value": "To switch characters", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION02_1"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION03": {"value": "Tap on the character to switch", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION02"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION04_1": {"value": "To walljump", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION04_1"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION04": {"value": "Press jump while next to a wall as Kim to walljump", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION04"},
	"STR_REP_POPUP_HELP_MOBILE_INSTRUCTION05_1": {"value": "To double jump", "locID": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION05_1"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION05": {"value": "Press jump while in midair as Ron to double jump", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION05"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION06": {"value": "Press the action button as Kim to use her grappling hook", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION06"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION07": {"value": "Press the action button as Ron to hack into panels with Rufus", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION07"},
	"STR_REP_POPUP_HELP_MOBILE_DESCRIPTION08": {"value": "Cut the correct wire before time runs out!", "locID": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION08"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01": {"value": "Press left & right to move around.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION02": {"value": "Press up to jump.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION03": {"value": "Press the spacebar to switch character.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION04": {"value": "Take down enemies by jumping over them.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION05": {"value": "Ron can boost using his jetpack. Try double jumping!", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION06": {"value": "Kim can walljump. Just jump next to a wall!", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION07": {"value": "Press Z as Kim to use her grappling hook.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION08": {"value": "Press Z as Ron to hack into panels with Rufus.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION09": {"value": "Press Z as Kim to attack.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_INSTRUCTION10": {"value": "Hold jump as Ron to glide.", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_PC_LETTER": {"value": "Z", "locID": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01": {"value": "Drag to move around.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION02": {"value": "Tap to jump", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION03": {"value": "Tap on the character's portrait to switch.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION04": {"value": "Take down enemies by jumping over them.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION05": {"value": "Ron can boost using his jetpack. Try double jumping!", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION06": {"value": "Kim can walljump. Just jump next to a wall!", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION07": {"value": "Press the action button as Kim to use her grappling hook.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION08": {"value": "Press the action button as Ron to hack into panels with Rufus.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION09": {"value": "Press the action button as Kim to attack.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION10": {"value": "Hold jump as Ron to glide.", "locID": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01"},
	"STR_REP_DIALOG_CHARACTER_NAME05": {"value": "RUFUS", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME05_S": {"value": "RUFUS", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME06": {"value": "DR. KRAKEN", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME06_S": {"value": "DR. KRAKEN", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME07": {"value": "WADE", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIALOG_CHARACTER_NAME07_S": {"value": "WADE", "locID": "STR_REP_DIALOG_CHARACTER_NAME01"},
	"STR_REP_DIAG_INTRO_1": {"value": "Athena hid slime bombs throughout Middleton! This is not like here...", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_INTRO_2": {"value": "I'll work on a fix!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_INTRO_3": {"value": "I feel like she’s hiding somewhere in the highschool, we have to stop her before it’s too late!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_INTRO_4": {"value": "This has to be our most improbable mission yet. Hang on tight, Rufus!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_INTRO_5": {"value": "Eeeeek!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_1_1": {"value": "Can’t believe you found me. Welp, there’s only one way out from here", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_2_1": {"value": "How cute. You still think you can beat me. Well... LET'S FINISH THIS! ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_SHEGO_1_1": {"value": "YOU AGAIN? Let's do this! ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_1_1_AFTER": {"value": "I’ll let you have this one KP... Looks like I still have what you need, if you want it to have to come find me.", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_2_1_AFTER": {"value": "Wow... What happened? ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_2_2_AFTER": {"value": "Shego rewired your software, but you’re ok now. She also ran off with the controller before we could stop her.", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_KIM_VS_ATHENA_2_3_AFTER": {"value": "All of this is my fault, Kim! I'm really sorry! I have something here that could help you stop Shego. Take it please, stop her!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_ENDING_1": {"value": "Middleton is safe guys! We did it, Team Possible! Woohoo!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_ENDING_2": {"value": "I hope you can forgive me, Kim. I'll find a way to make sure that this never happens again. ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_ENDING_3": {"value": "Shego took over, it wasn't you. Team Possible is back together!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_ENDING_4": {"value": "Eeeeek! ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_1": {"value": "Ugh, Team Possible won again...", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_2": {"value": "Don't worry, we have a chance! My drone is recovering all the bombs.", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_3": {"value": "That doesn't sound like a good idea. What if Kim finds the controller and pushes the button?", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_4": {"value": "No way! I don't think that she had the control...", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_5": {"value": "Oops! Hehe. It seems that there were some bombs around here. ", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_6": {"value": "Now they aren't a threat anymore. Let's get back home!", "locID": "STR_REP_DIAG_INTRO_1"},
	"STR_REP_DIAG_SECRET_7": {"value": "Eeeeek!", "locID": "STR_REP_DIAG_INTRO_1"}
};
