window['swt_ui'] = window['swt_ui'].concat([
	{
		"string": "STR_REP_SCREEN_DESCRIPTION_TROPHY01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenAchievements",
		"control": "mcGuiTxtADescription",
		"type": "text"
	},
	{
		"string": "STR_REP_SCREEN_TITLE_TROPHY01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "550",
		"height": "40",
		"size_ltr": "32",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenAchievements",
		"control": "mcGuiTxtATitle",
		"type": "text"
	},
	{
		"string": "STR_REP_ACHIEVEMENTS_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "800",
		"height": "60",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenAchievements",
		"control": "mcGuiTxtTitle_S",
		"type": "text"
	},
	{
		"string": "STR_REP_ACHIEVEMENTS_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "800",
		"height": "60",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenAchievements",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_INFO",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "400",
		"height": "50",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiPopupConfirm",
		"control": "mcGuiTxtInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupConfirm",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupConfirm",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_TIMEUP",
		"color": "#eb0949",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "150",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageTimeup",
		"control": "mcGuiText_s1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_TIMEUP",
		"color": "#021002",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "150",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageTimeup",
		"control": "mcGuiText_s2",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_TIMEUP",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "150",
		"size_ltr": "84",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "84",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageTimeup",
		"control": "mcGuiText",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_MISSION",
		"color": "#021002",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "125",
		"size_ltr": "54",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "54",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageMissionName",
		"control": "mcGuiText_s1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_MISSION",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "125",
		"size_ltr": "54",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "54",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageMissionName",
		"control": "mcGuiText",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_MISSIONCOMPLETE",
		"color": "#021002",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "1000",
		"height": "100",
		"size_ltr": "68",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "68",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageMissionComplete",
		"control": "mcGuiText_s1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_MISSIONCOMPLETE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "1000",
		"height": "100",
		"size_ltr": "68",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "68",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageMissionComplete",
		"control": "mcGuiText",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_START",
		"color": "#021002",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "125",
		"size_ltr": "90",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "90",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageGame",
		"control": "mcGuiText_s1",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_START",
		"color": "#c6ff00",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "850",
		"height": "125",
		"size_ltr": "90",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "90",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiMessageGame",
		"control": "mcGuiText",
		"type": "text"
	},
	{
		"string": "STR_REP_DIAG_KIM_VS_ATHENA_2_3_AFTER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "750",
		"height": "125",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiCutscene",
		"control": "mcGuiTxtScript",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME01_S",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "400",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "left",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "left",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiCutscene",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "400",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "left",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "left",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiCutscene",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_4_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_4",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_3_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_3",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_2_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_2",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_1_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_1",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_4_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_3_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_2_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl4",
		"control": "mcGuiTextLevel_1_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_3_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_3",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_2_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_2",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_1_s",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_1",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_3_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_2_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_LVL_01",
		"color": "#ffff33",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "44",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "44",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenMetamapLvl3",
		"control": "mcGuiTextLevel_1_over",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "800",
		"height": "60",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenMetamap",
		"control": "mcGuiTxtTitle_S",
		"type": "text"
	},
	{
		"string": "STR_REP_METAMAP_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "800",
		"height": "60",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenMetamap",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDGAME_TOKEN_COUNTER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "45",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenialGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenialGordis",
		"gui": "mcGuiScreenEndgame",
		"control": "mcGuiTxtToken",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDGAME_MESSAGE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "750",
		"height": "70",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenEndgame",
		"control": "mcGuiTxtMessage_S",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDGAME_MESSAGE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "750",
		"height": "70",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenEndgame",
		"control": "mcGuiTxtMessage",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDGAME_TITLE",
		"color": "#c6ff00",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "750",
		"height": "60",
		"size_ltr": "32",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenEndgame",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_PC_INSTRUCTION01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "325",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialPc",
		"control": "mcGuiTxtDescription01",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_PC_LETTER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "80",
		"height": "50",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialPc",
		"control": "mcGuiTxtLetter",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "325",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription01",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION02",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "325",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription02",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION03",
		"color": "#002b47",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription03",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION04",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription04",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION05",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "125",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription05",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION06",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "280",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription06",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION07",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription07",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TUTORIAL_MOBILE_INSTRUCTION08",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "280",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiTutorialMobile",
		"control": "mcGuiTxtDescription08",
		"type": "text"
	},
	{
		"string": "STR_ENDLEVEL_TIMER_COUNTER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "30",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "30",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreensEndlevel",
		"control": "mcGuiTxtTimer",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_TOKEN_COUNTER",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "75",
		"size_ltr": "54",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "54",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreensEndlevel",
		"control": "mcGuiTxtTokenCounter_s",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_TOKEN_COUNTER",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "75",
		"size_ltr": "54",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "54",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreensEndlevel",
		"control": "mcGuiTxtTokenCounter",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "500",
		"height": "180",
		"size_ltr": "58",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "58",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreensEndlevel",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDLEVEL_TITLE",
		"color": "#c6ff00",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "500",
		"height": "180",
		"size_ltr": "58",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "58",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreensEndlevel",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_TRYAGAIN_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "250",
		"size_ltr": "62",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "62",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupTryAgain",
		"control": "mcGuiTxtTitle_s1",
		"type": "text"
	},
	{
		"string": "STR_REP_TRYAGAIN_TITLE",
		"color": "#eb0848",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "250",
		"size_ltr": "62",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "62",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupTryAgain",
		"control": "mcGuiTxtTitle_s2",
		"type": "text"
	},
	{
		"string": "STR_REP_TRYAGAIN_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "250",
		"size_ltr": "62",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "62",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupTryAgain",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_PAUSE_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupPause",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_PAUSE_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "80",
		"size_ltr": "46",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "46",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiPopupPause",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION08",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "150",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_8_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION07",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_7_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION06",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_6_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION05",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_5_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION05_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "85",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_5_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION04",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_4_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION04_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "45",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_4_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION03",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "330",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_3_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION03_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "80",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_3_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION02",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_2_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION02_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_2_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_DESCRIPTION01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_1_3",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION01_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_1_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_PC_INSTRUCTION01_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_pc",
		"control": "mcGuiTextPage_1_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION08",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "150",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_8_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION07",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_7_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION06",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_6_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION05",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_5_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION05_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_5_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION04",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_4_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION04_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_4_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION03",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "300",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_3_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION03_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "85",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_3_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION02",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "320",
		"height": "100",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_2_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION02_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "80",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_2_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_DESCRIPTION01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "350",
		"height": "150",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_1_3",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_1_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_MOBILE_INSTRUCTION01_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHelpPage_mobile",
		"control": "mcGuiTextPage_1_1",
		"type": "text"
	},
	{
		"string": "STR_REP_DIAG_INTRO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "580",
		"height": "125",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHudDialog",
		"control": "mcGuiTxtDescription",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME01_S",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "400",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "left",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "left",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiHudDialog",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME01",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "400",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "left",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "32",
		"hAlign_rtl": "left",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiHudDialog",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME04",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHud",
		"control": "mcGuiTxtEnemyName_s",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOG_CHARACTER_NAME04",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "250",
		"height": "35",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHud",
		"control": "mcGuiTxtEnemyName",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TIME",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "22",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "22",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHud",
		"control": "mcGuiTxtTimer",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_TIME",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "22",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "22",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiHud",
		"control": "mcGuiTxtTimerCritical",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_4",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "ddt_rgbold_italic",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "ddt_rgbold_italic",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont4",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_3",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoGenialFajadita",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoGenialFajadita",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont3",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuanacoGenialGordis",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuanacoGenialGordis",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont2",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "arial",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "arial",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont1",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PERCENT",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "arial",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "arial",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiLoading",
		"type": "text"
	}
]);
