{
	"version": 1568284281,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/menubg-sheet0.png",
		"images/playbtn-sheet0.png",
		"images/playbtn-sheet1.png",
		"images/mutebtn-sheet0.png",
		"images/mutebtn-sheet1.png",
		"images/generatebtn-sheet0.png",
		"images/returnmenubtn-sheet0.png",
		"images/mouse_wand-sheet0.png",
		"images/gamebackground-sheet0.png",
		"images/interaction_sprite-sheet0.png",
		"images/answer_sprite-sheet0.png",
		"images/llama_sprite-sheet0.png",
		"images/llama_sprite-sheet1.png",
		"images/llama_sprite-sheet2.png",
		"images/bar_sprite-sheet0.png",
		"images/bar_sprite-sheet1.png",
		"images/bar_sprite-sheet2.png",
		"images/bar_sprite-sheet3.png",
		"images/bar_sprite-sheet4.png",
		"images/progress1_sprite-sheet0.png",
		"images/llama-sheet0.png",
		"images/results-sheet0.png",
		"images/results-sheet1.png",
		"images/questionsprte-sheet0.png",
		"images/answers-sheet0.png",
		"images/reveal-sheet0.png",
		"images/llamabg-sheet0.png",
		"media/es_bubble blip 1 - sfx producer.m4a",
		"media/es_bubble blip 1 - sfx producer.ogg",
		"media/roundsound_2.m4a",
		"media/roundsound_2.ogg",
		"media/randsound_1.m4a",
		"media/roundsound_1.ogg",
		"media/es_sheep baa 6 - sfx producer.m4a",
		"media/es_sheep baa 6 - sfx producer.ogg",
		"media/es_trumpet horse - sfx producer.m4a",
		"media/es_trumpet horse - sfx producer.ogg",
		"media/es_long morning coffee - medite.m4a",
		"media/es_long morning coffee - medite.ogg",
		"media/es_sheep baa 5 - sfx producer.m4a",
		"media/es_sheep baa 5 - sfx producer.ogg",
		"media/randsound_1.ogg",
		"media/randsound_2.m4a",
		"media/randsound_2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"readinfile.txt"
	]
}