{
	"gameWidth" : 1024,
	"gameHeight" : 576,
	"keyUp" : "38",
	"keyDown" : "40",
	"keyLeft" : "37",
	"keyRight" : "39",
	"scaleHeightToWidth" : 0.0,
	"speechMode" : "1",		
	"isLandscapeAllowed" : "1",
	"isPortraitAllowed" : "0",	
	"debugDraw" : "0",
	"debugCheats" : "1",
	"forceOrientation" : "NONE",
	"scaleToScreenOnDesktop" : "0",
	"isLandscapeAllowedIPad" : "1",
	"isPortraitAllowedIPad" : "0",
	"isLandscapeAllowedIPhone" : "1",
	"isPortraitAllowedIPhone" : "0"
}