{
	"version": 1570108739,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/menubg-sheet0.png",
		"images/playbtn-sheet0.png",
		"images/playbtn-sheet1.png",
		"images/mutebtn-sheet0.png",
		"images/mutebtn-sheet1.png",
		"images/gamebg-sheet0.png",
		"images/scroll-sheet0.png",
		"images/returnmenubtn-sheet0.png",
		"images/spell_sprite-sheet0.png",
		"images/points-sheet0.png",
		"images/points-sheet1.png",
		"images/wand-sheet0.png",
		"images/mouse_wand-sheet0.png",
		"images/spell_t2-sheet0.png",
		"images/spell_circle-sheet0.png",
		"images/spell_heart-sheet0.png",
		"images/spell_moon-sheet0.png",
		"images/start_pulse-sheet0.png",
		"images/start_pulse-sheet1.png",
		"images/overlay-sheet0.png",
		"images/particles.png",
		"images/creature_sprite-sheet0.png",
		"images/creature_sprite-sheet1.png",
		"images/creature_sprite-sheet2.png",
		"images/animal_scroll-sheet0.png",
		"images/spell_partical.png",
		"images/preloader_sprite-sheet0.png",
		"images/twittercedit-sheet0.png",
		"media/es_magic chime - sfx producer.m4a",
		"media/es_magic chime - sfx producer.ogg",
		"media/soundtrack1.m4a",
		"media/soundtrack1.ogg",
		"media/animal_cat.m4a",
		"media/animal_cat.ogg",
		"media/animal_dog_fox.m4a",
		"media/animal_dog_fox.ogg",
		"media/animal_dragon.m4a",
		"media/animal_dragon.ogg",
		"media/animal_griffin.m4a",
		"media/animal_griffin.ogg",
		"media/animal_horse_unicorn.m4a",
		"media/animal_horse_unicorn.ogg",
		"media/animal_owl.m4a",
		"media/animal_owl.ogg",
		"media/animal_pigeon.m4a",
		"media/animal_pigeon.ogg",
		"media/animal_rat_bat.m4a",
		"media/animal_rat_bat.ogg",
		"media/animal_snake_basilisk_spider_scorpion.m4a",
		"media/animal_snake_basilisk_spider_scorpion.ogg",
		"media/animal_toad_tortoise.m4a",
		"media/animal_toad_tortoise.ogg",
		"media/casting complete1.m4a",
		"media/casting complete1.ogg",
		"media/casting complete2.m4a",
		"media/casting complete2.ogg",
		"media/shimmer1.m4a",
		"media/shimmer1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"all2.txt"
	]
}