function gzpLoader() { var t, e, i, a, s, n, o, r, h, d, l, u, c, p, g, m, y;
    this._init = function() { this._defaultValues(), this._appendStyle(), this._appendHtml(), this._appendPreload(), this._setEnableModifiers() }, this.loadProcess = function(t) { "block" == document.getElementsByTagName("canvas")[0].style.display && (document.getElementsByTagName("canvas")[0].style.display = "none"), this._moveFurther(t), t >= r.maxLoad && window.setTimeout(this._unload.bind(this), r.nextDelay) }, this.modify = function(t, e) { r.maxLoad = t, r.nextDelay = e }, this.enableMain = function() { document.getElementById("mainLoader").style.display = "block", document.getElementById("noGameHere").style.display = "none", this._resizeHandle() }, this.refreshHeight = function() { document.getElementById("mainLoader").style.height = window.innerHeight + "px" }, this.disableMain = function() { document.getElementById("mainLoader").style.display = "none", setTimeout(function() { var t = document.getElementById("noGameHere");
            t.style.display = "block", t.style.width = window.innerWidth, t.style.height = window.innerHeight }, 200) }, this.disablePre = function() { document.getElementById("preLoader").style.display = "none" }, this.getStyle = function() { return t }, this.getHtmlBlog = function() { return e + "\n" + a + "\n" + s + "\n" + i + "\n" + c + "\n" + h + "\n" + l + "\n" + u + "\n" + d }, this.unload = function() { this._unload(), document.getElementsByTagName("canvas")[0].style.display = "block" }, this._appendPreload = function() { n += 2; var t = document.getElementById("underPreload"),
            e = "rect(0px, " + n + "px, 100px, 0px)";
        t.style.clip = e, 1 == o && n < 42 && window.setTimeout(this._appendPreload.bind(this), 1e3) }, this._defaultValues = function() { y = !1, p = { width: 500, height: 131, hMod: 50, maxMask: 500, maskHeight: 131, totalImages: 3, loaded: 0 }, r = { maxLoad: 100, nextDelay: 200 }, n = 0, o = !0, g = !0, m = 0, window.addEventListener("resize", this._resizeHandle.bind(this)) }, this._postMessage = function(t) { if (1 != y) { var e = parseInt(t);
            window.top.postMessage({ type: "loading", gameCode: "SklMs63M_gZ", progress: e }, "*"), window.postMessage({ type: "loading", gameCode: "SklMs63M_gZ", progress: e }, "*") } }, this._moveFurther = function(t) { null != t && 0 !== t && (m = t); var e = document.getElementById("processbar"),
            i = e.offsetWidth;
        i = parseInt(i / 100 * m), this._postMessage(m); var a = "rect(0px, " + i + "px, " + 250 + "px, 0px)";
        e.style.clip = a }, this._resizeHandle = function() { var t = window.innerWidth,
            e = window.innerHeight,
            i = document.getElementById("processbar"),
            a = document.getElementById("sadProcessbar");
        this.refreshHeight(), t > e ? (a.style.width = "20%", i.style.width = "20%") : (a.style.width = "45%", i.style.width = "45%"), this._moveFurther(0) }, this._switchToMainLoader = function() { this.disablePre(), this.enableMain() }, this._onLoaded = function() { p.loaded++, p.loaded >= p.totalImages && this._switchToMainLoader() }, this._setEnableModifiers = function() { var t = document.getElementById("dummyImg"),
            e = document.getElementById("processbar"),
            i = document.getElementById("sadProcessbar");
        t.onload = this._onLoaded.bind(this), e.onload = this._onLoaded.bind(this), i.onload = this._onLoaded.bind(this) }, this._setProcessBegin = function() { h = '<div id="mainLoader">' }, this._setPreloadBegin = function() { e = '<div id="preLoader">' }, this._setPreloadEnd = function() { i = "</div>" }, this._setDummy = function() { c = '<img id="dummyImg" style="display:none" src="gzpAssets/loader-logo.png" />' }, this._setProcessEnd = function() { d = "</div>" }, this._setEmptyProcess = function() { l = '<img id="sadProcessbar" src="gzpAssets/loader-logo.png" />' }, this._setFilledProcess = function() { u = '<img id="processbar" src="gzpAssets/loader-fill.png"/>' }, this._setFilledPreload = function() { a = '<img id="underPreload" src="gzpAssets/filledPreload.png"/>' }, this._setEmptyPreload = function() { s = '<img id="overPreload" src="gzpAssets/preloader.png"/>' }, this._appendHtml = function() { var t;
        this._setPreloadBegin(), this._setPreloadEnd(), this._setFilledPreload(), this._setEmptyPreload(), this._setProcessBegin(), this._setProcessEnd(), this._setEmptyProcess(), this._setFilledProcess(), this._setDummy(), t = this.getHtmlBlog(), document.getElementById("noGameHere").insertAdjacentHTML("afterend", t) }, this._setStyle = function() { t = "<style>               #mainLoader{\n                  width:100%;\n                  height:100%;\n                  background-color:#ffffff;\n                  background-size: contain;\n                  z-index: 900;\n                  display:none\n              }\n              \n              \n              \n              #preLoader{\n                 width:100%;\n                 height:100%;\n                 background-color:#000000;\n                 background-size: contain;\n                 z-index: 800;\n                 display:block\n               }\n               \n               \n               \n               #sadProcessbar{\n                 width: 40%;\n                 margin: auto;\n                 position: absolute;\n                 top: 0;\n                 left: 0;\n                 bottom: 0;\n                 right: 0;\n                 align: middle\n               }\n               \n               \n               \n               #processbar{\n                 width: 40%;\n                 clip: rect(0px, 90px, 200px, 0px);\n                 margin: auto;\n                 position: absolute;\n                 top: 0;\n                 left: 0;\n                 bottom: 0;\n                 right: 0;\n                 align: middle\n               }\n               \n               \n               \n               #overPreload{\n                 width: 64px;\n                 margin: auto;\n                 position: absolute;\n                 top: 0;\n                 left: 0;\n                 bottom: 0;\n                 right: 0;\n                 align: middle\n               }\n               \n               \n               \n               #underPreload{\n                 width: 64px;\n                 clip: rect(0px, 0px, 200px, 0px);\n                 margin: auto;\n                 position: absolute;\n                 top: 0;\n                 left: 0;\n                 bottom: 0;\n                 right: 0;\n                 align: middle\n               }\n               </style>\n             " }, this._appendStyle = function() { this._setStyle(); var t = this.getStyle();
        document.querySelector("head").insertAdjacentHTML("afterbegin", t) }, this._unload = function() { 1 != y && (y = !0, this.disableMain(), this.disablePre()) }, this._init() }
var GZLOADER = new gzpLoader;