{
	"version": 1572521337,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/game_background-sheet0.png",
		"images/gnasers_flees-sheet0.png",
		"images/gnashers_fur-sheet0.png",
		"images/itchy_coo-sheet0.png",
		"images/cauldron-sheet0.png",
		"images/cauldron-sheet1.png",
		"images/cauldron-sheet2.png",
		"images/cauldron-sheet3.png",
		"images/cauldron-sheet4.png",
		"images/itchingpowder-sheet0.png",
		"images/puff_cloud-sheet0.png",
		"images/mouldy_cheese-sheet0.png",
		"images/sweat_socks-sheet0.png",
		"images/school_slop-sheet0.png",
		"images/stink_bomb-sheet0.png",
		"images/not_recipe-sheet0.png",
		"images/minniemenu-sheet0.png",
		"images/playbtn-sheet0.png",
		"images/playbtn-sheet1.png",
		"images/titlemenu-sheet0.png",
		"images/rotten_egg-sheet0.png",
		"images/garlic_bashed-sheet0.png",
		"images/bottled_farts-sheet0.png",
		"images/whoopie_cushion-sheet0.png",
		"images/scissors-sheet0.png",
		"images/dog_food-sheet0.png",
		"images/sisters_vomit-sheet0.png",
		"images/homework_remover-sheet0.png",
		"images/candle_wax-sheet0.png",
		"images/sticky_ink-sheet0.png",
		"images/glitter_glue-sheet0.png",
		"images/invisable_ink-sheet0.png",
		"images/toenails-sheet0.png",
		"images/fizzy_lemon-sheet0.png",
		"images/invisability_potion-sheet0.png",
		"images/rasher_bathwater-sheet0.png",
		"images/mud-sheet0.png",
		"images/dried_grass-sheet0.png",
		"images/mucky_mudpie-sheet0.png",
		"images/shelf-sheet0.png",
		"images/potionbook-sheet0.png",
		"images/potionbook-sheet1.png",
		"images/potion_list-sheet0.png",
		"images/mutebtn-sheet0.png",
		"images/mutebtn-sheet1.png",
		"images/almositch-sheet0.png",
		"images/almositch-sheet1.png",
		"images/tutorial-sheet0.png",
		"images/sprite-sheet0.png",
		"images/book2-sheet0.png",
		"images/play2-sheet0.png",
		"images/infobtn-sheet0.png",
		"images/infobtn-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/potions-sheet0.png",
		"images/cutaway-sheet0.png",
		"images/particles.png",
		"images/glow-sheet0.png",
		"images/arrow-sheet0.png",
		"images/arrow-sheet1.png",
		"media/bath.m4a",
		"media/bath.ogg",
		"media/chameleon.m4a",
		"media/chameleon.ogg",
		"media/cheese.m4a",
		"media/cheese.ogg",
		"media/dog bowl.m4a",
		"media/dog bowl.ogg",
		"media/dog.m4a",
		"media/dog.ogg",
		"media/egg.m4a",
		"media/egg.ogg",
		"media/fart.m4a",
		"media/fart.ogg",
		"media/flea.m4a",
		"media/flea.ogg",
		"media/garlic.m4a",
		"media/garlic.ogg",
		"media/glue.m4a",
		"media/glue.ogg",
		"media/grass.m4a",
		"media/grass.ogg",
		"media/itchy.m4a",
		"media/itchy.ogg",
		"media/lemon.m4a",
		"media/lemon.ogg",
		"media/mud.m4a",
		"media/mud.ogg",
		"media/scissor.m4a",
		"media/scissor.ogg",
		"media/slop.m4a",
		"media/slop.ogg",
		"media/socks.m4a",
		"media/socks.ogg",
		"media/sticky.m4a",
		"media/sticky.ogg",
		"media/wax.m4a",
		"media/wax.ogg",
		"media/vomit.m4a",
		"media/vomit.ogg",
		"media/whoopee cushion gold.m4a",
		"media/whoopee cushion gold.ogg",
		"media/whoopee cushion silver.m4a",
		"media/whoopee cushion silver.ogg",
		"media/soundtrack with bubbles.m4a",
		"media/soundtrack with bubbles.ogg",
		"media/pageturn.m4a",
		"media/pageturn.ogg",
		"media/flowers.m4a",
		"media/flowers.ogg",
		"media/hidden potion silver.m4a",
		"media/hidden potion silver.ogg",
		"media/hidden potion.m4a",
		"media/hidden potion.ogg",
		"media/hoover.m4a",
		"media/hoover.ogg",
		"media/ink bottle.m4a",
		"media/ink bottle.ogg",
		"media/ink silver.m4a",
		"media/ink silver.ogg",
		"media/itching powder silver.m4a",
		"media/itching powder silver.ogg",
		"media/itching powder.m4a",
		"media/itching powder.ogg",
		"media/mud pie silver.m4a",
		"media/mud pie silver.ogg",
		"media/mud pie.m4a",
		"media/mud pie.ogg",
		"media/politician.m4a",
		"media/politician.ogg",
		"media/pop1.m4a",
		"media/pop1.ogg",
		"media/pop2.m4a",
		"media/pop2.ogg",
		"media/pop3.m4a",
		"media/pop3.ogg",
		"media/pop4.m4a",
		"media/pop4.ogg",
		"media/spray bottle silver.m4a",
		"media/spray bottle silver.ogg",
		"media/spray bottle.m4a",
		"media/spray bottle.ogg",
		"media/stink bomb silver.m4a",
		"media/stink bomb silver.ogg",
		"media/stink bomb.m4a",
		"media/stink bomb.ogg",
		"media/whoopee cushion.m4a",
		"media/whoopee cushion.ogg",
		"media/zombie.m4a",
		"media/zombie.ogg",
		"media/splash.m4a",
		"media/splash.ogg",
		"media/splash2.m4a",
		"media/splash2.ogg",
		"media/splash3.m4a",
		"media/splash3.ogg",
		"media/splash4.m4a",
		"media/splash4.ogg",
		"media/es_prel hit sparkle 2 - sfx producer.m4a",
		"media/es_prel hit sparkle 2 - sfx producer.ogg",
		"media/es_steam burn 2 - sfx producer.m4a",
		"media/es_steam burn 2 - sfx producer.ogg",
		"media/soundtrack with bubbles2.m4a",
		"media/soundtrack with bubbles2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}