function ScrEnd(){PIXI.Container.call(this);this.init();}
ScrEnd.prototype=Object.create(PIXI.Container.prototype);ScrEnd.prototype.constructor=ScrEnd;ScrEnd.prototype.init=function(){this._arButtons=[];if(g.score==undefined){g.score=0;}
var bgEnd=addObj("bgIntro2",0,0,scG);bgEnd.setReg0();this.addChild(bgEnd);this.a=new PIXI.Container();this.a.x=_W/2;this.a.y=195*scG;this.addChild(this.a);var paper=addObj("paper3",-41*scG,14*scG,scG);this.a.addChild(paper);var lsp=addObj("lsppose1",-67*scG,29*scG);this.a.addChild(lsp);var tfTitle=addText(getText("the_end"),60,"#000000");tfTitle.x=42*scG;tfTitle.y=-110*scG-tfTitle.height/2;this.a.addChild(tfTitle);var tfScore=addText(getText("final_score"),30,"#000000");tfScore.x=114*scG;tfScore.y=-34*scG-tfScore.height/2;this.a.addChild(tfScore);this.tfScore=addText(String(g.score),50,"#000000");this.tfScore.x=113*scG;this.tfScore.y=4*scG-this.tfScore.height/2;this.a.addChild(this.tfScore);var tfBestScore=addText(getText("best_score"),30,"#000000");tfBestScore.x=112*scG;tfBestScore.y=53*scG-tfBestScore.height/2;this.a.addChild(tfBestScore);this.tfBestScore=addText(String(g.highscore),50,"#000000");this.tfBestScore.x=111*scG;this.tfBestScore.y=92*scG-this.tfBestScore.height/2;this.a.addChild(this.tfBestScore);if(g.score>g.highscore){g.highscore=g.score;saveData();}
this.d=40
commonclass.say(fox.getrandom("loseVO"));var btnRestart=addButton("btnLong",110,350,0.5);btnRestart.name="btnRestart";this.addChild(btnRestart);this._arButtons.push(btnRestart);var tfRestart=addText(getText("restart"),24,"#FFFFFF",undefined,undefined,200);tfRestart.y=-tfRestart.height/2;btnRestart.addChild(tfRestart);var btnContinue=addButton("btnLong",490,350,0.5);btnContinue.name="btnContinue";this.addChild(btnContinue);this._arButtons.push(btnContinue);var tfContinue=addText(getText("continue"),24,"#FFFFFF",undefined,undefined,200);tfContinue.y=-tfContinue.height/2;btnContinue.addChild(tfContinue);btnRestart.interactive=true;btnRestart.buttonMode=true;btnContinue.interactive=true;btnContinue.buttonMode=true;this.interactive=true;this.on('mousedown',this.touchHandler);this.on('mousemove',this.touchHandler);this.on('touchstart',this.touchHandler);this.on('touchmove',this.touchHandler);this.on('touchend',this.touchHandler);}
ScrEnd.prototype.update=function(diffTime){if(options_pause){return;}}
ScrEnd.prototype.clickObj=function(item_mc){var name=item_mc.name
if(name.indexOf("btn")==-1){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}}
if(name=="btnRestart"){g.score=0;this.removeAllListener();showGame();}else if(name=="btnContinue"){g.level=g.score=0;this.removeAllListener();showMenu();}}
ScrEnd.prototype.checkButtons=function(evt){var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(hit_test_rec(item_mc,item_mc.w,item_mc.h,mouseX,mouseY)){if(item_mc.visible&&item_mc.alpha==1){if(item_mc._selected==false){item_mc._selected=true;if(item_mc.over){item_mc.over.visible=true;}else if(item_mc.overSc){item_mc.scale.x=1.1*item_mc.vX;item_mc.scale.y=1.1;}}}}else{if(item_mc._selected){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}}}}}
ScrEnd.prototype.touchHandler=function(evt){var phase=evt.type;if(phase=='mousemove'||phase=='touchmove'||phase=='touchstart'){this.checkButtons(evt);}else{var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(item_mc._selected){this.clickObj(item_mc);item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}
return;}}}}
ScrEnd.prototype.removeAllListener=function(){clearClips();this.interactive=false;this.off('mousedown',this.touchHandler);this.off('mousemove',this.touchHandler);this.off('touchstart',this.touchHandler);this.off('touchmove',this.touchHandler);this.off('touchend',this.touchHandler);}