function ScrIntro2(value){PIXI.Container.call(this);this.init(value);}
ScrIntro2.prototype=Object.create(PIXI.Container.prototype);ScrIntro2.prototype.constructor=ScrIntro2;ScrIntro2.prototype.init=function(value){this._arButtons=[];this._prevScr=value;var bgMenu=addObj("bgIntro2",_W/2,_H/2,scG);this.addChild(bgMenu);this.a=new PIXI.Container();this.a.x=139*scG;this.a.y=161*scG;this.addChild(this.a);var book=addObj("book",161*scG,74*scG,scG);this.a.addChild(book);var tfTInstr2=addText(getText("how_to_play"),30/scG,"#000000",undefined,undefined,300/scG);tfTInstr2.rotation=fox.rad(7);tfTInstr2.x=110;tfTInstr2.y=-140-tfTInstr2.height/2;book.addChild(tfTInstr2);var tfInstr2=addText(getText("desc_instr_2"),20/scG,"#000000",undefined,undefined,300/scG);tfInstr2.rotation=fox.rad(8);tfInstr2.x=20;tfInstr2.y=100-tfInstr2.height/2;book.addChild(tfInstr2);if(options_mobile){var finger2=addObj("finger2",160,10,0.3);book.addChild(finger2);}
this.paper=new PIXI.Container();this.paper.x=61*scG;this.paper.y=82*scG;this.a.addChild(this.paper);var paper=addObj("paper",157*scG,0,scG);this.paper.addChild(paper);if(options_mobile){var finger1=addObj("finger1",240*scG,-80*scG,0.3*scG);this.paper.addChild(finger1);}
var tfTInstr1=addText(getText("how_to_play"),30,"#000000",undefined,undefined,300);tfTInstr1.rotation=fox.rad(7);tfTInstr1.x=200*scG;tfTInstr1.y=-150*scG-tfTInstr1.height/2;this.paper.addChild(tfTInstr1);var tfInstr1=addText(getText("desc_instr_1"),20,"#000000",undefined,undefined,300);tfInstr1.rotation=fox.rad(8);tfInstr1.x=120*scG;tfInstr1.y=70*scG-tfInstr1.height/2;this.paper.addChild(tfInstr1);this.paper2=new PIXI.Container();this.paper2.rotation=fox.rad(21);this.paper2.x=28*scG;this.paper2.y=102*scG;this.a.addChild(this.paper2);var paper2=addObj("paper2",-206*scG,-144*scG,scG);this.paper2.addChild(paper2);this.paper2.scale.x=0.1;this.paper2.visible=false;this.nopress=20;this.timePage=0;this.timePage2=0;this.x1=this.a.x;this.y1=this.a.y;this.a.x-=200*scG;this.a.y+=400*scG;this.a.scale.x=this.a.scale.y=1.5*0.625;var btnNext=addButton("btnDefault",524,350,0.5);btnNext.name="btnNext";this.addChild(btnNext);this._arButtons.push(btnNext);var tfStart=addText(getText("next"),24,"#FFFFFF",undefined,undefined,100);tfStart.y=-tfStart.height/2;btnNext.addChild(tfStart);this.btnNext=btnNext;this.tfStart=tfStart;btnNext.interactive=true;btnNext.buttonMode=true;this.interactive=true;this.on('mousedown',this.touchHandler);this.on('mousemove',this.touchHandler);this.on('touchstart',this.touchHandler);this.on('touchmove',this.touchHandler);this.on('touchend',this.touchHandler);}
ScrIntro2.prototype.update=function(item_mc){this.nopress=Math.max(0,this.nopress-1);this.a.x=this.a.x+(this.x1-this.a.x)/3;this.a.y=this.a.y+(this.y1-this.a.y)/3;if(this.timePage3>0){this.paper2.alpha-=0.33;this.timePage3--;if(this.timePage2==0){this.paper2.visible=false;}}
if(this.timePage2>0){this.paper2.scale.x+=0.038;this.paper2.scale.y-=0.035;this.paper2.x+=2.5*scG;this.paper2.y-=5.5*scG;this.paper2.rotation-=fox.rad(1.5);this.timePage2--;if(this.timePage2==0){this.timePage3=3;}}
if(this.timePage>0){this.paper.scale.x-=0.1;this.paper.scale.y+=0.01;this.paper.x-=3*scG;this.paper.rotation+=fox.rad(2.3);this.timePage--;if(this.timePage==0){this.paper2.visible=true;this.timePage2=10;}}}
ScrIntro2.prototype.nextPage=function(){this.timePage=10;}
ScrIntro2.prototype.clickObj=function(item_mc){var name=item_mc.name
if(name.indexOf("btn")==-1){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}}
if(name=="btnNext"){this.nextPage();if(this._prevScr=="menu"){this.btnNext.name="btnBack";this.tfStart.setText(getText("back"));}else{this.btnNext.name="btnPlay";this.tfStart.setText(getText("play"));}}else if(name=="btnPlay"){this.removeAllListener();showGame();}else if(name=="btnBack"){this.removeAllListener();showMainMenu();}}
ScrIntro2.prototype.checkButtons=function(evt){var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(hit_test_rec(item_mc,item_mc.w,item_mc.h,mouseX,mouseY)){if(item_mc.visible&&item_mc.alpha==1){if(item_mc._selected==false){item_mc._selected=true;if(item_mc.over){item_mc.over.visible=true;}else if(item_mc.overSc){item_mc.scale.x=1.1*item_mc.vX;item_mc.scale.y=1.1;}}}}else{if(item_mc._selected){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}}}}}
ScrIntro2.prototype.touchHandler=function(evt){var phase=evt.type;if(phase=='mousemove'||phase=='touchmove'||phase=='touchstart'){this.checkButtons(evt);}else{var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(item_mc._selected){this.clickObj(item_mc);item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}
return;}}}}
ScrIntro2.prototype.removeAllListener=function(){clearClips();this.interactive=false;this.off('mousedown',this.touchHandler);this.off('mousemove',this.touchHandler);this.off('touchstart',this.touchHandler);this.off('touchmove',this.touchHandler);this.off('touchend',this.touchHandler);}