function ScrMenu(){PIXI.Container.call(this);this.init();}
ScrMenu.prototype=Object.create(PIXI.Container.prototype);ScrMenu.prototype.constructor=ScrMenu;ScrMenu.prototype.init=function(){this.bg_mc=new PIXI.Container();this.addChild(this.bg_mc);this._arButtons=[];musicPlay("zloop2");var bgMenu=addObj("bgMenu",_W/2,_H/2,scG);this.bg_mc.addChild(bgMenu);var btnMenu=addButton("btnDefault",75,350,0.5);btnMenu.name="btnMenu";this.addChild(btnMenu);this._arButtons.push(btnMenu);var tfMenu=addText(getText("menu"),24,"#FFFFFF",undefined,undefined,100);tfMenu.y=-tfMenu.height/2;btnMenu.addChild(tfMenu);var btnStart=addButton("btnDefault",520,350,0.5);btnStart.name="btnStart";this.addChild(btnStart);this._arButtons.push(btnStart);var tfStart=addText(getText("play"),22,"#FFFFFF",undefined,undefined,100);tfStart.y=-tfStart.height/2;btnStart.addChild(tfStart);var realW=window.innerWidth;var realH=window.innerHeight;if(ScreenLock){if(realW<realH){options_pause=true;ScreenLock.visible=true;}}
btnStart.interactive=true;btnStart.buttonMode=true;btnMenu.interactive=true;btnMenu.buttonMode=true;this.interactive=true;this.on('mousedown',this.touchHandler);this.on('mousemove',this.touchHandler);this.on('touchstart',this.touchHandler);this.on('touchmove',this.touchHandler);this.on('touchend',this.touchHandler);}
ScrMenu.prototype.clickObj=function(item_mc){var name=item_mc.name
item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}
if(name=="btnStart"){this.removeAllListener();showInto1();}else if(name=="btnMenu"){this.removeAllListener();showMainMenu();}}
ScrMenu.prototype.checkButtons=function(evt){var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(hit_test_rec(item_mc,item_mc.w,item_mc.h,mouseX,mouseY)){if(item_mc.visible&&item_mc.alpha==1){if(item_mc._selected==false){item_mc._selected=true;if(item_mc.over){item_mc.over.visible=true;}else if(item_mc.overSc){item_mc.scale.x=1.1*item_mc.vX;item_mc.scale.y=1.1;}}}}else{if(item_mc._selected){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}}}}}
ScrMenu.prototype.touchHandler=function(evt){var phase=evt.type;if(phase=='mousemove'||phase=='touchmove'||phase=='touchstart'){this.checkButtons(evt);}else{var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(item_mc._selected){this.clickObj(item_mc);item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}
return;}}}}
ScrMenu.prototype.removeAllListener=function(){this.interactive=false;this.off('mousedown',this.touchHandler);this.off('mousemove',this.touchHandler);this.off('touchstart',this.touchHandler);this.off('touchmove',this.touchHandler);this.off('touchend',this.touchHandler);}