function ScrWin(){PIXI.Container.call(this);this.init();}
ScrWin.prototype=Object.create(PIXI.Container.prototype);ScrWin.prototype.constructor=ScrWin;ScrWin.prototype.init=function(){this._arButtons=[];if(g.score==undefined){g.score=0;}
if(g.waktu==undefined){g.waktu=0;}
if(g.energy1==undefined){g.energy1=0;}
var fr=g.level||1;if(fr>6){fr=6;}
var bgEnd=addObj("bg"+fr);bgEnd.setReg0();this.addChild(bgEnd);this.a=new PIXI.Container();this.a.x=_W/2;this.a.y=200*scG;this.addChild(this.a);this.a1=new PIXI.Container();this.a1.x=270*scG;this.a1.y=75*scG;this.addChild(this.a1);this.c1=new PIXI.Container();this.c1.x=270*scG;this.c1.y=300*scG;this.addChild(this.c1);this.state=1;this.x1=this.a.x;this.y1=this.a.y;this.x2=this.a1.x;this.y2=this.a1.y;this.x3=this.c1.x;this.y3=this.c1.y;this.a.x-=200*scG;this.a.y+=400*scG;this.a1.x-=200*scG;this.a1.y+=400*scG;this.c1.x-=200*scG;this.c1.y+=400*scG;this.timebonus=Math.round(g.waktu*10);this.energybonus=Math.round(g.energy1*150);this.totalscore=(g.score+this.timebonus+this.energybonus)||0;this.xpos=20*scG;var paper=addObj("paper3",-41*scG,14*scG,scG);this.a.addChild(paper);var lsp=addObj("lsppose4",158*scG,-16*scG);this.a.addChild(lsp);var tfTitle=addText(getText("party")+" "+g.level,30,"#000000");tfTitle.x=0;tfTitle.y=-15*scG-tfTitle.height/2;this.a1.addChild(tfTitle);var tfLSP=addText(getText("lsp_rules"),45,"#000000");tfLSP.x=0;tfLSP.y=25*scG-tfLSP.height/2;this.a1.addChild(tfLSP);this.b1=addText(getText("your_score"),20,"#000000",undefined,"right");this.b1.x=-25*scG;this.b1.y=-41*scG-this.b1.height/2;this.a.addChild(this.b1);this.b2=addText(getText("time_bonus"),20,"#000000",undefined,"right");this.b2.x=-19*scG;this.b2.y=-4*scG-this.b2.height/2;this.a.addChild(this.b2);this.b3=addText(getText("energy_bonus"),20,"#000000",undefined,"right");this.b3.x=0;this.b3.y=30*scG-this.b3.height/2;this.a.addChild(this.b3);var tfTS=addText(getText("total_score"),25,"#000000");tfTS.x=0;tfTS.y=-17*scG-tfTS.height/2;this.c1.addChild(tfTS);this.c1.b=addText(String(this.totalscore),50,"#000000");this.c1.b.x=0;this.c1.b.y=29*scG-this.c1.b.height/2;this.c1.addChild(this.c1.b);saveData();fox.waitpop(this.a1,0.3);this.delay=20;this.d=25;commonclass.say(g.winVO[g.level%2]);var btnNext=addButton("btnDefault",525,350,0.5);btnNext.name="btnNext";this.addChild(btnNext);this._arButtons.push(btnNext);var tfContinue=addText(getText("next"),24,"#FFFFFF",undefined,undefined,110);tfContinue.y=-tfContinue.height/2;btnNext.addChild(tfContinue);btnNext.interactive=true;btnNext.buttonMode=true;this.btnNext=btnNext;this.b1.visible=this.b2.visible=this.b3.visible=false;this.c1.visible=btnNext.visible=false;this.interactive=true;this.on('mousedown',this.touchHandler);this.on('mousemove',this.touchHandler);this.on('touchstart',this.touchHandler);this.on('touchmove',this.touchHandler);this.on('touchend',this.touchHandler);}
ScrWin.prototype.update=function(diffTime){if(options_pause){return;}
this.a.x=this.a.x+(this.x1-this.a.x)/3;this.a.y=this.a.y+(this.y1-this.a.y)/3;this.a1.x=this.a1.x+(this.x2-this.a1.x)/3;this.a1.y=this.a1.y+(this.y2-this.a1.y)/3;this.c1.x=this.c1.x+(this.x3-this.c1.x)/3;this.c1.y=this.c1.y+(this.y3-this.c1.y)/3;this.d--;if(!this.d){if(this.state==1){this.b1.visible=true;this.addcounter(g.score,this.xpos,this.b1.y,0);this.state=2;this.d=10;}else if(this.state==2){this.b2.visible=true;this.addcounter(this.timebonus,this.xpos,this.b2.y,15);this.state=3;this.d=this.delay;}else if(this.state==3){this.b3.visible=true;this.addcounter(this.energybonus,this.xpos,this.b3.y,15);this.state=4;this.d=this.delay;}else if(this.state==4){this.c1.visible=true;soundPlay("zpop");this.state=5;this.d=20;}else if(this.state==5){this.btnNext.visible=true;}}}
ScrWin.prototype.addcounter=function(num,xx,yy,time){var it=new numbercounter(0,num,time);it.x=xx;it.y=yy;this.a.addChild(it);}
ScrWin.prototype.clickObj=function(item_mc){var name=item_mc.name
if(name.indexOf("btn")==-1){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}}
if(name=="btnNext"){g.score=this.totalscore;g.level++;saveData();this.removeAllListener();showGame();}}
ScrWin.prototype.checkButtons=function(evt){var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(hit_test_rec(item_mc,item_mc.w,item_mc.h,mouseX,mouseY)){if(item_mc.visible&&item_mc.alpha==1){if(item_mc._selected==false){item_mc._selected=true;if(item_mc.over){item_mc.over.visible=true;}else if(item_mc.overSc){item_mc.scale.x=1.1*item_mc.vX;item_mc.scale.y=1.1;}}}}else{if(item_mc._selected){item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}}}}}
ScrWin.prototype.touchHandler=function(evt){var phase=evt.type;if(phase=='mousemove'||phase=='touchmove'||phase=='touchstart'){this.checkButtons(evt);}else{var mouseX=evt.data.global.x;var mouseY=evt.data.global.y;for(var i=0;i<this._arButtons.length;i++){var item_mc=this._arButtons[i];if(item_mc._selected){this.clickObj(item_mc);item_mc._selected=false;if(item_mc.over){item_mc.over.visible=false;}else if(item_mc.overSc){item_mc.scale.x=1*item_mc.vX;item_mc.scale.y=1;}
return;}}}}
ScrWin.prototype.removeAllListener=function(){clearClips();this.interactive=false;this.off('mousedown',this.touchHandler);this.off('mousemove',this.touchHandler);this.off('touchstart',this.touchHandler);this.off('touchmove',this.touchHandler);this.off('touchend',this.touchHandler);}