{
	"version": 1566564074,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/dragon-sheet0.png",
		"images/tile-sheet0.png",
		"images/gnashmeba-sheet0.png",
		"images/gnashimal-sheet0.png",
		"images/gnipper-sheet0.png",
		"images/sabretoothedgnasher-sheet0.png",
		"images/gnasher-sheet0.png",
		"images/egnormognash-sheet0.png",
		"images/gnashzilla-sheet0.png",
		"images/gnashizen-sheet0.png",
		"images/gnashraa-sheet0.png",
		"images/50stepsbutton-sheet0.png",
		"images/challengebutton-sheet0.png",
		"images/endlessbutton-sheet0.png",
		"images/clockicon-sheet0.png",
		"images/footicon-sheet0.png",
		"images/fbbutton-sheet0.png",
		"images/gnasherpediabutton-sheet0.png",
		"images/menubutton-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/soundbutton-sheet0.png",
		"images/soundbutton-sheet1.png",
		"images/twbutton-sheet0.png",
		"images/smoke-sheet0.png",
		"images/rotate-sheet0.png",
		"images/rotatebg.png",
		"images/foottext.png",
		"images/gameoverpanel-sheet0.png",
		"images/highscoretext-sheet0.png",
		"images/score-sheet0.png",
		"images/title-sheet0.png",
		"images/latesttext-sheet0.png",
		"images/flag-sheet0.png",
		"images/loadicon-sheet0.png",
		"images/gnasherpediasprite-sheet0.png",
		"images/gnasherpediasprite-sheet1.png",
		"images/gnasherpediasprite-sheet2.png",
		"images/speakericonsprite-sheet0.png",
		"images/upsprite-sheet0.png",
		"images/downsprite-sheet0.png",
		"images/arrowkeysprite-sheet0.png",
		"images/tutorialbackdropboxsprite-sheet0.png",
		"images/yesimsurebutton-sheet0.png",
		"images/noimnotsurebutton-sheet0.png",
		"images/bone-sheet0.png",
		"images/backgroundsheet-sheet0.png",
		"images/mutebutton-sheet0.png",
		"images/retrybutton-sheet0.png",
		"images/galactic-sheet0.png",
		"images/jglo-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/spritefont.png",
		"images/creditstxt-sheet0.png",
		"images/ulosenamefield2.png",
		"images/spritefont2.png",
		"images/maincard-sheet0.png",
		"images/maincard-sheet1.png",
		"images/maincard-sheet2.png",
		"images/maincard-sheet3.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/maincard2-sheet0.png",
		"images/maincard2-sheet1.png",
		"images/sprite9-sheet0.png",
		"images/fadeobject-sheet0.png",
		"media/win.m4a",
		"media/win.ogg",
		"media/plop1.m4a",
		"media/plop1.ogg",
		"media/plop7.m4a",
		"media/plop7.ogg",
		"media/soundtrack - es_the odyssey ahead - dream cave.m4a",
		"media/soundtrack - es_the odyssey ahead - dream cave.ogg",
		"media/game over sound.m4a",
		"media/game over sound.ogg",
		"media/gnizard 2.m4a",
		"media/gnizard 2.ogg",
		"media/es_laser sword hum - sfx producer.m4a",
		"media/es_laser sword hum - sfx producer.ogg",
		"media/es_magnet attract metal 2 - sfx producer.m4a",
		"media/es_magnet attract metal 2 - sfx producer.ogg",
		"media/es_mm chime 145 - sfx producer.m4a",
		"media/es_mm chime 145 - sfx producer.ogg",
		"media/es_mouth pop 1 - sfx producer.m4a",
		"media/es_mouth pop 1 - sfx producer.ogg",
		"media/es_mud bubbles 3 - sfx producer.m4a",
		"media/es_mud bubbles 3 - sfx producer.ogg",
		"media/es_prel logo shine rev - sfx producer.m4a",
		"media/es_prel logo shine rev - sfx producer.ogg",
		"media/es_prel shimmer swells 3 - sfx producer.m4a",
		"media/es_prel shimmer swells 3 - sfx producer.ogg",
		"media/es_rats! - jerry lacey.m4a",
		"media/es_rats! - jerry lacey.ogg",
		"media/es_splash water 16 - sfx producer.m4a",
		"media/es_splash water 16 - sfx producer.ogg",
		"media/es_splash water 5 - sfx producer.m4a",
		"media/es_splash water 5 - sfx producer.ogg",
		"media/es_trumpet charge - sfx producer.m4a",
		"media/es_trumpet charge - sfx producer.ogg",
		"media/es_trumpet muted - sfx producer.m4a",
		"media/es_trumpet muted - sfx producer.ogg",
		"media/es_trumpet sad - sfx producer.m4a",
		"media/es_trumpet sad - sfx producer.ogg",
		"media/es_voice clip male 203 - sfx producer.m4a",
		"media/es_voice clip male 203 - sfx producer.ogg",
		"media/es_cymbal swell eerie - sfx producer.m4a",
		"media/es_cymbal swell eerie - sfx producer.ogg",
		"media/es_ghost cry - sfx producer.m4a",
		"media/es_ghost cry - sfx producer.ogg",
		"media/es_horse clydesdale 13 - sfx producer.m4a",
		"media/es_horse clydesdale 13 - sfx producer.ogg",
		"media/es_impact metal 11 - sfx producer.m4a",
		"media/es_impact metal 11 - sfx producer.ogg",
		"media/claire masterpiece.m4a",
		"media/claires masterpiece.ogg",
		"media/lava.m4a",
		"media/lava.ogg",
		"media/lava2.m4a",
		"media/lava2.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/soundtrack.m4a",
		"media/soundtrack.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"config.json",
		"penumbra.png"
	]
}