{
	"version": 1571408604,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/soundbtn1-sheet0.png",
		"images/soundbtn1-sheet1.png",
		"images/soundbtn2-sheet0.png",
		"images/soundbtn2-sheet1.png",
		"images/soundbtn3-sheet0.png",
		"images/soundbtn3-sheet1.png",
		"images/soundbtn5-sheet0.png",
		"images/soundbtn5-sheet1.png",
		"images/soundbtn4-sheet0.png",
		"images/soundbtn4-sheet1.png",
		"images/toysprite-sheet0.png",
		"images/toysprite-sheet1.png",
		"images/toysprite-sheet2.png",
		"images/effectbtn1-sheet0.png",
		"images/effectbtn1-sheet1.png",
		"images/soundbtn6-sheet0.png",
		"images/soundbtn6-sheet1.png",
		"images/playbtn-sheet0.png",
		"images/playbtn-sheet1.png",
		"images/playbtn-sheet2.png",
		"images/consolesprite-sheet0.png",
		"images/trumpets-sheet0.png",
		"images/title-sheet0.png",
		"images/title-sheet1.png",
		"images/title-sheet2.png",
		"images/slidersprite-sheet0.png",
		"images/sliderobject-sheet0.png",
		"images/sundbtn7-sheet0.png",
		"images/sundbtn7-sheet1.png",
		"images/soundbtn8-sheet0.png",
		"images/soundbtn8-sheet1.png",
		"images/simonsaysfartsprite-sheet0.png",
		"images/speekersprite-sheet0.png",
		"images/ssftitle-sheet0.png",
		"images/redbtn-sheet0.png",
		"images/yellowbtn-sheet0.png",
		"images/bluebtn-sheet0.png",
		"images/greenbtn-sheet0.png",
		"images/metersprite-sheet0.png",
		"images/helpsprite-sheet0.png",
		"images/closebtn-sheet0.png",
		"images/helpbtn-sheet0.png",
		"images/helpfont1.png",
		"images/gamedial-sheet0.png",
		"images/helpbtn2-sheet0.png",
		"images/background-sheet0.png",
		"images/randombtn-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/cauldron demon.m4a",
		"media/cauldron demon.ogg",
		"media/cauldron harmony.m4a",
		"media/cauldron harmony.ogg",
		"media/cauldron reverb.m4a",
		"media/cauldron reverb.ogg",
		"media/cauldron slow.m4a",
		"media/cauldron slow.ogg",
		"media/crow demon.m4a",
		"media/crow demon.ogg",
		"media/crow harmony.m4a",
		"media/crow harmony.ogg",
		"media/crow reverb.m4a",
		"media/crow reverb.ogg",
		"media/crow slow.m4a",
		"media/crow slow.ogg",
		"media/es_cauldron large boil - sfx producer.m4a",
		"media/es_cauldron large boil - sfx producer.ogg",
		"media/es_crow caw 3 - sfx producer.m4a",
		"media/es_crow caw 3 - sfx producer.ogg",
		"media/es_evil laugh 3 - sfx producer.m4a",
		"media/es_evil laugh 3 - sfx producer.ogg",
		"media/es_frankenstein 2 - sfx producer.m4a",
		"media/es_frankenstein 2 - sfx producer.ogg",
		"media/es_human scream 14 - sfx producer.m4a",
		"media/es_human scream 14 - sfx producer.ogg",
		"media/es_lightning bolt 11 - sfx producer.m4a",
		"media/es_lightning bolt 11 - sfx producer.ogg",
		"media/es_mouse squeak 7 - sfx producer.m4a",
		"media/es_mouse squeak 7 - sfx producer.ogg",
		"media/es_zombie snarl 4 - sfx producer.m4a",
		"media/es_zombie snarl 4 - sfx producer.ogg",
		"media/laugh demon.m4a",
		"media/laugh demon.ogg",
		"media/laugh harmony.m4a",
		"media/laugh harmony.ogg",
		"media/laugh reverb.m4a",
		"media/laugh reverb.ogg",
		"media/laugh slow.m4a",
		"media/laugh slow.ogg",
		"media/lightning demon.m4a",
		"media/lightning demon.ogg",
		"media/lightning harmony.m4a",
		"media/lightning harmony.ogg",
		"media/lightning reverb.m4a",
		"media/lightning reverb.ogg",
		"media/lightning slow.m4a",
		"media/lightning slow.ogg",
		"media/monster demon.m4a",
		"media/monster demon.ogg",
		"media/monster harmony.m4a",
		"media/monster harmony.ogg",
		"media/monster reverb.m4a",
		"media/monster reverb.ogg",
		"media/monster slow.m4a",
		"media/monster slow.ogg",
		"media/scream demon.m4a",
		"media/scream demon.ogg",
		"media/scream harmony.m4a",
		"media/scream harmony.ogg",
		"media/scream reverb.m4a",
		"media/scream reverb.ogg",
		"media/scream slow.m4a",
		"media/scream slow.ogg",
		"media/squeak demon.m4a",
		"media/squeak demon.ogg",
		"media/squeak harmony.m4a",
		"media/squeak harmony.ogg",
		"media/squeak reverb.m4a",
		"media/squeak reverb.ogg",
		"media/squeak slow.m4a",
		"media/squeak slow.ogg",
		"media/zombie demon.m4a",
		"media/zombie demon.ogg",
		"media/zombie harmony.m4a",
		"media/zombie harmony.ogg",
		"media/zombie reverb.m4a",
		"media/zombie reverb.ogg",
		"media/zombie slow.m4a",
		"media/zombie slow.ogg",
		"media/click1.m4a",
		"media/click1.ogg",
		"media/click2.m4a",
		"media/click2.ogg",
		"media/click3.m4a",
		"media/click3.ogg",
		"media/click4.m4a",
		"media/click4.ogg",
		"media/click5.m4a",
		"media/click5.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}