function AISystem(engine,createEntity,removeEntity,onEntitiesOverlap,onEntityKilled,onEntityHurt,onItemPickup,onAttack){this.engine=engine;this.playerId=0;this.createEntity=createEntity;this.removeEntity=removeEntity;this.onEntitiesOverlap=onEntitiesOverlap;this.onEntityKilled=onEntityKilled;this.onEntityHurt=onEntityHurt;this.onItemPickup=onItemPickup;this.onAttack=onAttack;this.dtVec2=WONBATS.Vec2.create(0,0);this.tempVec2=WONBATS.Vec2.create(0,0);}
AISystem.prototype.dispose=function(){this.engine=null;this.createEntity=null;this.removeEntity=null;this.onEntitiesOverlap=null;this.onEntityKilled=null;this.onEntityHurt=null;this.onItemPickup=null;this.onAttack=null;};AISystem.prototype.playSound=function(data){if(data){var isSimple=false,i=0;for(i=0;i<data.length;i++){var subData=data[i];if(WONBATS.isArray(subData)){console.log("sound array: "+subData);var sound=WONBATS.getRandomFromArray(subData);game.soundManager.playSfx(sound);}else{isSimple=true;break;}}
if(isSimple){console.log("sound simple: "+data);var sound=WONBATS.getRandomFromArray(data);game.soundManager.playSfx(sound);}}};AISystem.prototype.updateState=function(dt,state,render){if(state.transition!==""){state.next=state.config[state.current][state.transition]||state.current;state.current="";state.transition="";}
if(state.current!==state.next){var entity=state.entity;var i=0;var component=null;if(!state.config[state.next]){console.log("Entity State",state.entity);}
for(i=0;i<state.config[state.next].enable.length;i++){this.engine.addComponentToEntity(components[state.config[state.next].enable[i]],entity);}
for(i=0;i<state.config[state.next].disable.length;i++){this.engine.removeComponentFromEntity(components[state.config[state.next].disable[i]],entity);}
if(state.config[state.next].anim&&state.config[state.next].anim!==""){render.play(state.config[state.next].anim,state.config[state.next].play);}
this.playSound(state.config[state.next].sound);state.current=state.next;}};AISystem.prototype.spawnEnemy=function(dt,state,enemy,render,transform){if(state.current!=="spawn")return;enemy.time-=dt;var multiplier=1;var playerTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);if(playerTransform){multiplier=Math.sign(playerTransform.position[0]-transform.position[0])||1;}
var scale=1-(Math.max(0,enemy.time)/enemy.maxTime);render.asset.scale.x=scale*multiplier;render.asset.scale.y=scale;if(enemy.time<0){state.transition="toIdle";}};AISystem.prototype.updatePlayerState=function(dt,state,player,launcher,info,collider,render){player.cooldown-=dt;if(!player.input)return;if(player.input.release&&player.cooldown<=0){var directionVector=player.input.getDirectionVector();player.attackVector[0]=directionVector[0];player.attackVector[1]=directionVector[1];var vectorDegree=WONBATS.Vec2.getAngle(player.attackVector)*180/Math.PI;var quad="";if(vectorDegree>157.5){quad="left";}else if(vectorDegree>112.5){quad="left_up";}else if(vectorDegree>67.5){quad="up";}else if(vectorDegree>22.5){quad="up_right";}else if(vectorDegree>-22.5){quad="right";}else if(vectorDegree>-67.5){quad="right_down";}else if(vectorDegree>-112.5){quad="down";}else if(vectorDegree>-157.5){quad="down_left";}else{quad="left";}
player.attack=true;player.quad=quad;player.attackInfo=info.data.swipes[quad];if(!(player.attackInfo.cancelOnTheFloor&&collider.isOnTheFloor())){state.transition="toAttack";this.onAttack();}}
player.input.release=false;};AISystem.prototype.updateLanderState=function(dt,state,lander,collider,render){if(collider.isOnTheFloor()&&!lander.wasOnTheFloor){state.transition="toLand";var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("idle");}}
if(state.current==="land"&&render.animationEnd()){state.transition="toIdle";}
lander.wasOnTheFloor=collider.isOnTheFloor();};AISystem.prototype.updateAttackState=function(dt,state,player,attack,launcher,render,collider,rigidbody,impulse){if(collider.isOnTheFloor()){attack.currentAerialAttacks=attack.maxAerialAttacks;}
if(player.quad==="left_up"||player.quad==="up"||player.quad==="up_right"){if(attack.currentAerialAttacks>0){attack.currentAerialAttacks--;}else{player.attack=false;}}
player.quad="";if(player.attack){player.attack=false;attack.info=player.attackInfo;player.cooldown=attack.info.cooldown||attack.info.projectileFireRate||0;attack.vector[0]=player.attackVector[0];attack.vector[1]=player.attackVector[1];if(!attack.info.addForce){rigidbody.velocity[0]=0;rigidbody.velocity[1]=0;}
if(attack.info.hasOwnProperty("degree")){var vectorLength=WONBATS.Vec2.getLength(attack.vector);var rad=attack.info.degree*Math.PI/180;attack.vector[0]=Math.cos(rad)*vectorLength;attack.vector[1]=Math.sin(rad)*vectorLength;}
var force=(collider.isOnTheFloor())?(attack.info.force):(attack.info.air||attack.info.force);attack.isRange=false;launcher.maxBurst=Number.MAX_VALUE;if(attack.info.hasOwnProperty("projectile")){launcher.bullets=attack.info.projectileBullets||1;launcher.randomAngle=(attack.info.randomAngle||0)*Math.PI/180;launcher.maxBurst=attack.info.projectileBurst;launcher.burst=attack.info.projectileBurst;launcher.projectile=attack.info.projectile;launcher.force=attack.info.projectileForce;launcher.degree=attack.info.projectileDegree;launcher.pushForce=-(attack.info.projectilePushForce||0);launcher.vector[0]=player.attackVector[0];launcher.vector[1]=player.attackVector[1];attack.isRange=true;}
this.playSound(attack.info.sound);render.play(attack.info.anim);var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("attack");}
if(attack.isRange){render.asset.children[0].update(0);render.asset.children[0].children[0].getChildByName("legs").gotoAndStop(collider.isOnTheFloor()?"floor":"air");}
impulse.force[0]=force*attack.vector[0];impulse.force[1]=-force*attack.vector[1];if(attack.info.hasOwnProperty("direction")){render.asset.scale.x=attack.info.direction;}else{render.asset.scale.x=attack.vector[0]>0?1:-1;}}else{if(attack.isRange){if(render.animationEnd()){if(collider.isOnTheFloor()){state.transition="toIdle";}else{state.transition="toAirIdle";}
var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("idle");}}}else{if(collider.isOnTheFloor()){if(attack.info.shakeTime){globalsignal.emit("shake",{time:attack.info.shakeTime,intensity:attack.info.shakeIntensity});this.playSound(attack.info.shakeSound);}
if(Math.abs(rigidbody.velocity[0])<200){state.transition="toIdle";var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("idle");}}}}}};AISystem.prototype.updateHurtState=function(dt,state,hurt,render,collider,rigidbody){hurt.time-=dt;if(hurt.time<0){hurt.time=hurt.delay;if(collider.isOnTheFloor()){state.transition="toIdle";}else{state.transition="toAirIdle";}
var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("idle");}}};AISystem.prototype.updateWaitState=function(dt,state,wait){wait.time-=dt;if(wait.time<=0){state.transition=wait.nextState;wait.time=wait.maxTime;}};AISystem.prototype.updateBouncerState=function(dt,state,bouncer,render,collider,rigidbody,transform){if(collider.isOnTheFloor()&&!bouncer.jumping){var playerTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);if(playerTransform&&bouncer.targetPlayer){bouncer.multiplier=Math.sign(playerTransform.position[0]-transform.position[0]);}
rigidbody.velocity[0]=bouncer.force[0]*bouncer.multiplier;rigidbody.velocity[1]=bouncer.force[1];bouncer.jumping=true;}else if(collider.isNextToTheWall()){bouncer.multiplier*=-1;}else if(collider.isOnTheFloor()){bouncer.jumping=false;state.transition="toIdle";}
if(rigidbody.velocity[0]<0){render.asset.scale.x=-1;}else if(rigidbody.velocity[0]>0){render.asset.scale.x=1;}};AISystem.prototype.updateRunnerState=function(dt,state,runner,render,collider,rigidbody,transform){runner.time-=dt;if(!collider.isOnTheFloor()||runner.time<0){runner.time=runner.maxTime+runner.waitTime;}
if(collider.isOnTheFloor()&&runner.time<=runner.maxTime){rigidbody.velocity[0]+=runner.force[0]*dt*runner.multiplier;rigidbody.velocity[1]+=runner.force[1]*dt;}
var playerTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);if(playerTransform&&runner.targetPlayer){runner.multiplier=Math.sign(playerTransform.position[0]-transform.position[0]);}
if(rigidbody.velocity[0]<0){render.asset.scale.x=-1;}else if(rigidbody.velocity[0]>0){render.asset.scale.x=1;}
if(collider.isNextToTheWall()||Math.random()<runner.randomDirectionChance){runner.multiplier*=-1;state.transition="toIdle";}};AISystem.prototype.updateFlyerState=function(dt,state,flyer,render,collider,rigidbody,transform){rigidbody.velocity[0]+=flyer.force[0]*dt*flyer.multiplier;if(transform.position[1]>(transform.spawnPosition[1]+(flyer.minHeight/2))){rigidbody.velocity[1]+=flyer.force[1]*dt;}
var multiplier=flyer.multiplier;var playerTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);if(playerTransform&&flyer.targetPlayer){multiplier=Math.sign(playerTransform.position[0]-transform.position[0]);}
if(rigidbody.velocity[0]<0){render.asset.scale.x=-1;}else if(rigidbody.velocity[0]>0){render.asset.scale.x=1;}
if(collider.isNextToTheWall()||Math.random()<flyer.randomDirectionChance){multiplier=flyer.multiplier*-1;}
if(flyer.multiplier!==multiplier){flyer.multiplier=multiplier;}};AISystem.prototype.resolveInterception=function(dt,state,render,collider,rigidbody,life,transform){life.time-=dt;if(collider.interceptions.length===0)return;for(var i=0;i<collider.interceptions.length;i++){var otherId=collider.interceptions[i];var otherCollider=this.engine.getComponentFromEntity(components.AABBCollider,otherId);if(otherCollider.category===components.AABBCollider.PRIZE){var otherInfo=this.engine.getComponentFromEntity(components.Info,otherId);this.playSound(otherInfo.data.sound.collide);this.onItemPickup(otherId);}else{if(!life.isInmune()){var getDamage=true;var otherLife=this.engine.getComponentFromEntity(components.Life,otherId);var otherRigidBody=this.engine.getComponentFromEntity(components.RigidBody,otherId);var otherTransform=this.engine.getComponentFromEntity(components.Transform,otherId);if(!otherRigidBody||(otherLife&&otherLife.isInmune())){getDamage=false;}
if(getDamage){var otherDamage=this.engine.getComponentFromEntity(components.Damage,otherId);var previousLives=life.points;life.points-=otherDamage.points;life.time=life.inmunity;if(otherDamage.soundOnHit){this.playSound(otherDamage.soundOnHit);}
this.onEntitiesOverlap(otherDamage.hitStunTime);this.onEntityHurt(life,previousLives);var massImpulse=Math.round(Math.min(otherRigidBody.mass/(otherRigidBody.mass+rigidbody.mass),2)*100)/100;rigidbody.velocity[0]=otherRigidBody.velocity[0]*massImpulse;rigidbody.velocity[1]=otherRigidBody.velocity[1]*massImpulse;globalsignal.emit("hitsparkParticle",{x:transform.position[0]+(otherTransform.position[0]-transform.position[0])/2,y:transform.position[1]+(otherTransform.position[1]-transform.position[1])/2});if(life.points<=0){state.transition="toDie";if(render.asset.children[0].labels.hasOwnProperty(otherDamage.dieAnimation)){state.config.die.anim=otherDamage.dieAnimation;}else{state.config.die.anim="hurt";}}else{state.transition="toHurt";}
var sword=this.engine.getComponentFromEntity(components.Sword,state.entity);if(sword){sword.asset.children[0].gotoAndPlay("idle");}
break;}}}}
collider.interceptions.length=0;};AISystem.prototype.spawnHitBox=function(dt,attack,render,damage,rigidbody,transform){if(render.asset.children[0].layers[0]&&render.asset.children[0].layers[0].getChildByName("hitbox")){var hitbox=render.asset.children[0].layers[0].getChildByName("hitbox");hitbox.visible=false;var hitboxid=this.createEntity(entities.PLAYER_HITBOX);var hbTransform=this.engine.getComponentFromEntity(components.Transform,hitboxid);hbTransform.position[0]=transform.position[0]+(hitbox.parent.parent.x+hitbox.parent.x+hitbox.x+(100*hitbox.scale.x/2))*render.asset.scale.x*render.asset.children[0].scale.x+rigidbody.velocity[0]*dt;hbTransform.position[1]=transform.position[1]+(hitbox.parent.parent.y+hitbox.parent.y+hitbox.y+(100*hitbox.scale.y/2))*render.asset.scale.y*render.asset.children[0].scale.y+rigidbody.velocity[1]*dt;var hbDamage=this.engine.getComponentFromEntity(components.Damage,hitboxid);hbDamage.points=damage.points;hbDamage.hitStunTime=attack.info.hitStunTime||damage.hitStunTime;hbDamage.dieAnimation=damage.dieAnimation;if(attack.info.soundsOnHit){hbDamage.soundOnHit=JSON.parse(JSON.stringify(attack.info.soundsOnHit));}
var hbCollider=this.engine.getComponentFromEntity(components.AABBCollider,hitboxid);var w=hbCollider.size[0]=100*hitbox.scale.x*render.asset.children[0].scale.x;var h=hbCollider.size[1]=100*hitbox.scale.y*render.asset.children[0].scale.y;var hbRigidbody=this.engine.getComponentFromEntity(components.RigidBody,hitboxid);hbRigidbody.velocity[0]=rigidbody.velocity[0];hbRigidbody.velocity[1]=rigidbody.velocity[1];if(game.config.DEBUG){var hbRender=this.engine.getComponentFromEntity(components.Render,hitboxid);var graphics=hbRender.asset.getChildByName("debughitbox");graphics.lineStyle(1,0xFFFFFF,0.25);graphics.beginFill(0xFF0000,0.25);graphics.drawRect(-w/2,-h/2,w,h);graphics.endFill();}}};AISystem.prototype.spawnProjectiles=function(dt,launcher,impulse,render,damage,transform){launcher.burst+=dt;if(render.asset.children[0].layers[0]&&render.asset.children[0].layers[0].getChildByName("launchbox")){var launchbox=render.asset.children[0].layers[0].getChildByName("launchbox");launchbox.visible=false;if(launcher.burst>launcher.maxBurst&&launcher.projectile){launcher.burst=0;impulse.force[0]=launcher.pushForce*launcher.vector[0];impulse.force[1]=-launcher.pushForce*launcher.vector[1];for(var i=0;i<launcher.bullets;i++){var projectileId=this.createEntity(entities[launcher.projectile]);var projectileTransform=this.engine.getComponentFromEntity(components.Transform,projectileId);projectileTransform.position[0]=transform.position[0]+(launchbox.parent.parent.x+launchbox.parent.x+launchbox.x+(100*launchbox.scale.x/2))*render.asset.scale.x*render.asset.children[0].scale.x;projectileTransform.position[1]=transform.position[1]+(launchbox.parent.parent.y+launchbox.parent.y+launchbox.y+(100*launchbox.scale.y/2))*render.asset.scale.y*render.asset.children[0].scale.y;if(launcher.degree!==undefined){var vectorLength=WONBATS.Vec2.getLength(launcher.vector);var rad=launcher.degree*Math.PI/180;launcher.vector[0]=Math.cos(rad)*vectorLength;launcher.vector[1]=Math.sin(rad)*vectorLength;}
WONBATS.Vec2.rotate(launcher.vector,(-launcher.randomAngle/2+Math.random()*launcher.randomAngle),this.tempVec2);var projectileRigidBody=this.engine.getComponentFromEntity(components.RigidBody,projectileId);var projectileProjectile=this.engine.getComponentFromEntity(components.Projectile,projectileId);if(WONBATS.Vec2.getLength(this.tempVec2)<projectileProjectile.minRatio){WONBATS.Vec2.normalize(this.tempVec2,this.tempVec2);WONBATS.Vec2.scale(this.tempVec2,projectileProjectile.minRatio,this.tempVec2);}
projectileRigidBody.velocity[0]=this.tempVec2[0]*launcher.force;projectileRigidBody.velocity[1]=-this.tempVec2[1]*launcher.force;var info=this.engine.getComponentFromEntity(components.Info,projectileId);if(info&&info.data.sound&&info.data.sound.shot){this.playSound(info.data.sound.shot);}}}}};AISystem.prototype.aimProjectile=function(dt,state,aim,launcher,render,transform){if(state.current==="shoot"){if(render.animationEnd()){state.transition="toIdle";}}else{var otherTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);if(otherTransform){aim.time-=dt;if(aim.time<=0&&WONBATS.Vec2.getDistance(transform.position,otherTransform.position)<aim.distance){aim.time=aim.maxTime;if(aim.aimPlayer){launcher.vector[0]=otherTransform.position[0]-transform.position[0];launcher.vector[1]=900;}else{launcher.vector[0]=Math.sign(otherTransform.position[0]-transform.position[0])*aim.forceX;launcher.vector[1]=aim.forceY;}
launcher.force=1;launcher.pushForce=0;state.transition="toShoot";}}}};AISystem.prototype.jumpWhenNear=function(dt,state,jump,collider,rigidbody,transform,render){if(state.current==="jump"){if(collider.isOnTheFloor()){if(!jump.landing){jump.landing=true;render.play("stomp");}else if(render.animationEnd()){state.transition="toIdle";}}else{if(!jump.falling&&rigidbody.velocity[1]>0){jump.falling=true;jump.landing=false;render.play("goingdown");}}}else{var otherTransform=this.engine.getComponentFromEntity(components.Transform,this.playerId);var otherCollider=this.engine.getComponentFromEntity(components.AABBCollider,this.playerId);if(otherTransform){jump.time-=dt;if(jump.time<=0&&collider.isOnTheFloor()&&Math.abs(transform.position[0]-otherTransform.position[0])<jump.distance){jump.time=jump.maxTime;if(Math.abs(rigidbody.velocity[0])<jump.forceX){rigidbody.velocity[0]=Math.sign(otherTransform.position[0]-transform.position[0])*jump.forceX;}
rigidbody.velocity[1]=jump.forceY;jump.falling=false;state.transition="toJump";}}}};AISystem.prototype.consumeLifespan=function(dt,lifespan){lifespan.time-=dt;if(lifespan.time<=0){this.removeEntity(lifespan.entity);}};AISystem.prototype.removeAfterDie=function(dt,die,render,rigidbody,transform,gravity){if(!die.dying){this.onEntityKilled(die.entity);die.dying=true;render.asset.parent.addChildAt(render.asset,render.asset.parent.children.length);rigidbody.velocity[0]=-100+Math.random()*200;rigidbody.velocity[1]=-1000;die.finalRotation=Math.round(-1+Math.random()*2);die.finalAlpha=1;render.asset.alpha=die.finalAlpha;gravity.force[1]=2000;}else{render.asset.alpha=die.finalAlpha;render.asset.rotation+=die.finalRotation*dt;if(transform.position[1]>1080){this.removeEntity(die.entity);}}};AISystem.prototype.removeProjectileOnTouch=function(dt,projectile,collider,render){if(projectile.dying){if(render.asset.children[0].currentFrame===render.asset.children[0].totalFrames-1){this.removeEntity(projectile.entity);}}else{var mustDie=false;if(collider.interceptions.length>0){for(var i=0;i<collider.interceptions.length;i++){var interceptedLife=this.engine.getComponentFromEntity(components.Life,collider.interceptions[i]);if(interceptedLife&&(!interceptedLife.isInmune()||interceptedLife.time===interceptedLife.inmunity)){mustDie=true;break;}}}
if(!mustDie){for(var i=0;i<collider.ids.length;i++){if(collider.ids[i]!==-1){mustDie=true;break;}}}
if(mustDie){projectile.dying=true;render.asset.children[0].gotoAndPlay("out");var rigidbody=this.engine.getComponentFromEntity(components.RigidBody,projectile.entity);rigidbody.enable=false;var info=this.engine.getComponentFromEntity(components.Info,projectile.entity);if(info&&info.data.sound&&info.data.sound.collide){this.playSound(info.data.sound.collide);}}}};AISystem.prototype.updateProjectile=function(dt,projectile,rigidbody,transform){if(projectile.targetComponent){var targetComps=this.engine.getComponents(projectile.targetComponent);var maxDistance=Number.MAX_VALUE;var targetPosition=null;for(var i=0;i<targetComps.length;i++){if(targetComps[i].enable){var otherTransform=this.engine.getComponentFromEntity(components.Transform,i);var otherLife=this.engine.getComponentFromEntity(components.Life,i);var distance=WONBATS.Vec2.getDistance(transform.position,otherTransform.position);if(otherLife&&!otherLife.isInmune()&&distance<projectile.radius&&distance<maxDistance){maxDistance=distance;targetPosition=otherTransform.position;}}}
if(targetPosition){WONBATS.Vec2.subtract(transform.position,targetPosition,this.tempVec2);var currAngle=WONBATS.Vec2.getAngle(rigidbody.velocity);var targetAngle=WONBATS.Vec2.getAngle(this.tempVec2);var diffAngle=targetAngle-currAngle+Math.PI;if(diffAngle<-Math.PI)diffAngle+=Math.PI*2;if(diffAngle>Math.PI)diffAngle-=Math.PI*2;var dircAngle=Math.sign(diffAngle);WONBATS.Vec2.rotate(rigidbody.velocity,Math.PI*2*dt*dircAngle,rigidbody.velocity);}}};