var components=components||{};(function(){function State(){this.config={};this.current="";this.next="";this.transition="";}
State.prototype.initialize=function(config,initialState){this.config=config;this.next=initialState;this.current="";this.transition="";};components.State=State;components.State.name="State";function Transform(){this.position=WONBATS.Vec2.create(0,0);this.spawnPosition=WONBATS.Vec2.create(0,0);}
Transform.prototype.initialize=function(x,y){this.position[0]=x||0;this.position[1]=y||0;this.spawnPosition[0]=x||0;this.spawnPosition[1]=y||0;};components.Transform=Transform;components.Transform.name="Transform";function RigidBody(){this.velocity=WONBATS.Vec2.create(0,0);this.force=WONBATS.Vec2.create(0,0);this.drag=0;}
RigidBody.prototype.initialize=function(drag,velX,velY,mass){this.velocity[0]=velX||0;this.velocity[1]=velY||0;this.force[0]=0;this.force[1]=0;this.drag=drag||0;this.mass=mass||1;};components.RigidBody=RigidBody;components.RigidBody.name="RigidBody";function Gravity(){this.force=WONBATS.Vec2.create(0,0);}
Gravity.prototype.initialize=function(x,y){this.force[0]=x||0;this.force[1]=y||2000;};components.Gravity=Gravity;components.Gravity.name="Gravity";function AABBCollider(){this.size=WONBATS.Vec2.create(0,0);this.offset=WONBATS.Vec2.create(0,0);this.friction=0;this.bounciness=1;this.category=1;this.mask=256;this.fixes=[0,0,0,0];this.ids=[-1,-1,-1,-1];this.interceptions=[];}
AABBCollider.NONE=0;AABBCollider.GROUND=1;AABBCollider.PLAYER=2;AABBCollider.ENEMY=4;AABBCollider.PLAYER_PROJECTILE=8;AABBCollider.ENEMY_PROJECTILE=16;AABBCollider.ENEMY_GROUND=32;AABBCollider.PRIZE=64;AABBCollider.prototype.initialize=function(width,height,offsetX,offsetY,friction,bounciness,category,colliderMask,interceptionMask){this.size[0]=width||0;this.size[1]=height||0;this.offset[0]=offsetX||0;this.offset[1]=offsetY||0;this.friction=friction||0;this.bounciness=bounciness||0;this.category=category||1;this.mask=colliderMask||256;this.interceptionMask=interceptionMask||256;this.fixes[0]=this.fixes[1]=this.fixes[2]=this.fixes[3]=0;this.ids[0]=this.ids[1]=this.ids[2]=this.ids[3]=-1;this.interceptions.length=0;};AABBCollider.prototype.isOnTheFloor=function(){return this.ids[0]!==-1;};AABBCollider.prototype.isNextToTheWall=function(){return this.ids[1]!==-1||this.ids[3]!==-1;};components.AABBCollider=AABBCollider;components.AABBCollider.name="AABBCollider";function Shadow(){this.asset=null;this.scale=0;}
Shadow.prototype.initialize=function(asset,scale){this.asset=asset;this.scale=scale||0;};components.Shadow=Shadow;components.Shadow.name="Shadow";function Render(){this.asset=null;this.newAnimation=false;}
Render.prototype.initialize=function(asset){this.asset=asset;};Render.prototype.play=function(name,play){if(this.asset&&this.asset.children[0]){if(play){this.asset.children[0].gotoAndPlay(name);}else{this.asset.children[0].gotoAndStop(name);}
this.asset.children[0].update(0);if(this.asset.children[0].children[0]){this.asset.children[0].children[0].time=0;}
this.newAnimation=true;}};Render.prototype.animationEnd=function(){if(this.asset.children[0]){var currentAnimation=this.asset.children[0].children[0];if(currentAnimation&&currentAnimation.currentFrame===(currentAnimation.totalFrames-1)){return true;}}
return false;};components.Render=Render;components.Render.name="Render";function Impulse(){this.force=WONBATS.Vec2.create(0,0);}
Impulse.prototype.initialize=function(x,y){this.force[0]=x||0;this.force[1]=y||0;};components.Impulse=Impulse;components.Impulse.name="Impulse";function Info(){this.data={};}
Info.prototype.initialize=function(data){this.data=data;};components.Info=Info;components.Info.name="Info";function Player(){this.input={};this.attack=false;this.attackInfo={};this.attackVector=WONBATS.Vec2.create(0,0);this.quad="";this.wasOnTheFloor=false;this.cooldown=0;}
Player.prototype.initialize=function(input){this.input=input;this.addForce=false;this.attack=false;this.quad="";this.cooldown=0;};components.Player=Player;components.Player.name="Player";function Sword(){this.asset=null;this.id="";}
Sword.prototype.initialize=function(id,scale){this.asset=new WONBATS.MovieClip(swords,"sword");this.asset.gotoAndStop(id);this.asset.scale.x=this.asset.scale.y=scale||1;this.id=id;};components.Sword=Sword;components.Sword.name="Sword";function Lander(){this.wasOnTheFloor=false;}
Lander.prototype.initialize=function(){this.wasOnTheFloor=false;};components.Lander=Lander;components.Lander.name="Lander";function Enemy(){this.time=0;}
Enemy.prototype.initialize=function(){this.time=0.8;this.maxTime=this.time;};components.Enemy=Enemy;components.Enemy.name="Enemy";function Projectile(){this.dying=false;this.rotate=false;this.minRatio=0;this.targetComponent=null;}
Projectile.prototype.initialize=function(rotate,minRatio,targetComponent,radius){this.dying=false;this.rotate=rotate===undefined?false:rotate;this.minRatio=minRatio||0;this.targetComponent=targetComponent||null;this.radius=radius||0;};components.Projectile=Projectile;components.Projectile.name="Projectile";function Wait(){this.time=0;this.nextState="";}
Wait.prototype.initialize=function(time,nextState){this.time=time;this.maxTime=time;this.nextState=nextState;};components.Wait=Wait;components.Wait.name="Wait";function Bouncer(){this.force=WONBATS.Vec2.create(0,0);this.targetPlayer=false;this.multiplier=1;this.jumping=false;}
Bouncer.prototype.initialize=function(x,y,targetPlayer){this.force[0]=x;this.force[1]=y;this.targetPlayer=targetPlayer;this.multiplier=1;this.jumping=true;};components.Bouncer=Bouncer;components.Bouncer.name="Bouncer";function Runner(){this.force=WONBATS.Vec2.create(0,0);this.targetPlayer=false;this.multiplier=1;this.randomDirectionChance=0;this.time=0;this.maxTime=0;this.waitTime=0;}
Runner.prototype.initialize=function(x,y,targetPlayer,randomDirectionChance,time,wait){this.force[0]=x;this.force[1]=y;this.targetPlayer=targetPlayer;this.multiplier=1;this.randomDirectionChance=randomDirectionChance||0;this.maxTime=time||0;this.waitTime=wait||0;this.time=0;};components.Runner=Runner;components.Runner.name="Runner";function Flyer(){this.force=WONBATS.Vec2.create(0,0);this.targetPlayer=false;this.multiplier=1;this.randomDirectionChance=0;this.minHeight=0;}
Flyer.prototype.initialize=function(x,y,minHeight,targetPlayer,randomDirectionChance){this.force[0]=x;this.force[1]=y;this.minHeight=minHeight||0;this.targetPlayer=targetPlayer;this.multiplier=1;this.randomDirectionChance=randomDirectionChance||0;};components.Flyer=Flyer;components.Flyer.name="Flyer";function Life(){this.points=0;this.time=0;this.inmunity=0;this.hitStunTime=0;}
Life.prototype.initialize=function(points,inmunity){this.points=points||1;this.inmunity=inmunity||1;this.time=-1;this.hitStunTime=0;};Life.prototype.isInmune=function(){return this.time>0;};Life.prototype.isStunned=function(){return this.hitStunTime>0;};components.Life=Life;components.Life.name="Life";function Damage(){this.points=0;this.hitStunTime=0;this.soundOnHit="";}
Damage.prototype.initialize=function(points,hitStunTime,soundOnHit,dieAnimation){this.points=points;this.hitStunTime=hitStunTime||0;this.soundOnHit=soundOnHit||"";this.dieAnimation=dieAnimation||"hurt";};components.Damage=Damage;components.Damage.name="Damage";function Hurt(){this.time=0;this.delay=0;}
Hurt.prototype.initialize=function(delay){this.delay=delay||0;this.time=this.delay;};components.Hurt=Hurt;components.Hurt.name="Hurt";function Attack(){this.maxAerialAttacks=0;this.currentAerialAttacks=0;this.vector=WONBATS.Vec2.create(0,0);this.fireRate=0;this.info={};this.isRange=false;}
Attack.prototype.initialize=function(maxAerialAttacks){this.maxAerialAttacks=maxAerialAttacks||0;this.currentAerialAttacks=this.maxAerialAttacks;this.projectileFireRate=0;this.isRange=false;};components.Attack=Attack;components.Attack.name="Attack";function Launcher(){this.projectile="";this.fireRate=0;this.maxFireRate=0;this.burst=0;this.maxBurst=0;this.bullets=0;this.randomAngle=0;this.degree=0;this.force=0;this.vector=WONBATS.Vec2.create(0,0);this.pushForce=0;this.canBeCancelled=true;}
Launcher.prototype.initialize=function(projectile,maxBurst,bullets,randomAngle,vectorX,vectorY,force){this.projectile=projectile||"";this.fireRate=0;this.maxFireRate=0;this.burst=0;this.maxBurst=maxBurst||0;this.bullets=bullets||0;this.randomAngle=(randomAngle||0)*Math.PI/180;this.vector[0]=vectorX||0;this.vector[1]=vectorY||0;this.degree=undefined;this.force=force||0;this.canBeCancelled=true;};components.Launcher=Launcher;components.Launcher.name="Launcher";function Aim(){this.distance=0;this.time=0;this.maxTime=0;this.aimPlayer=false;this.forceX=0;this.forceY=0;}
Aim.prototype.initialize=function(distance,maxTime,aimPlayer,forceX,forceY){this.distance=distance;this.time=0;this.maxTime=maxTime;this.aimPlayer=aimPlayer||false;this.forceX=forceX||0;this.forceY=forceY||0;};components.Aim=Aim;components.Aim.name="Aim";function Jump(){this.distance=0;this.forceY=0;this.time=0;this.maxDelay=0;this.falling=false;this.landing=false;}
Jump.prototype.initialize=function(distance,forceX,forceY,time){this.distance=distance;this.forceX=forceX||0;this.forceY=forceY||0;this.time=time;this.maxTime=time;this.falling=false;this.landing=false;};components.Jump=Jump;components.Jump.name="Jump";function Lifespan(){this.time=0;}
Lifespan.prototype.initialize=function(time){this.time=time;};components.Lifespan=Lifespan;components.Lifespan.name="Lifespan";function Die(){this.dying=false;this.finalScale=0;this.finalRotation=0;this.finalAlpha=1;this.finalGravity=2000;}
Die.prototype.initialize=function(){this.dying=false;this.finalScale=0;this.finalRotation=0;this.finalAlpha=1;this.finalGravity=2000;};components.Die=Die;components.Die.name="Die";function Item(){this.type=0;this.fx=null;this.condig=null;}
Item.HEART=1;Item.CLOCK=2;Item.SWORD=4;Item.prototype.initialize=function(type,config,namespace,assetName,label,scale,rotation,offset){this.type=type;this.config=config;this.asset=new WONBATS.MovieClip(namespace,assetName);if(label){this.asset.gotoAndStop(label);}
if(scale){this.asset.scale.x=this.asset.scale.y=scale;}
if(rotation){this.asset.rotation=rotation;}
if(offset){this.asset.x=offset[0];this.asset.y=offset[1];}};components.Item=Item;components.Item.name="Item";function NoFlip(){}
NoFlip.prototype.initialize=function(){};components.NoFlip=NoFlip;components.NoFlip.name="NoFlip";function NoDrop(){}
NoDrop.prototype.initialize=function(){};components.NoDrop=NoDrop;components.NoDrop.name="NoDrop";}());