var version="2.1.8";console.log("HTMLGameContainer loaded version "+version);var vUrl=window.gameProps.gameLink,gameProps=window.gameProps;PORTRAIT=1;window.fbAsyncInit=function(){console.log("Initializing FB");FB.init({appId:"1540365052898331",xfbml:true,version:'v2.1'});};(function(d,s,id){console.log("Part 2 FB Initialize");var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}
js=d.createElement(s);js.id=id;js.src="http://connect.facebook.net/en_US/sdk.js";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));console.log("HTML5 Container Is window fired?  ["+window.loadFired+"]  containerLoaded ["+window.containerLoaded+"]");var HTML5GameContainer=function(){if(window.loadFired){console.log("Page is completely loaded according to HTML5GameContainer.js");window.continue();}
window.containerLoaded=true;var allowTrace=true;var hudContainer="HUDcanvas",age,nextStep=function(){},minAge=13,elem,active=false,left=0,top=0,message=0,parent,gameHUDLocation,name="HTML5GameContainer",x,y,canvasElem,elemLeft,elemTop,context,elements=[],initialized=false,age=_checkCookie();icons={'f':{top:152,left:10,callBack:'facebook',color:'#3C5A9A'},'t':{top:152,left:130,callBack:'twitter',color:'#60A9DE'},'p':{top:152,left:70,callBack:'pinterest',color:'#CB2028'}};function clickedRating(rate){var args={"action":"Rated","message":rate};window.DIBIGameTracking(args);};function _removeEndGameHUD(){publicAPI.closeAgeGate();};function _initializeGameCanvas(){console.log("creating HUD canvas   parent ["+parent+"]");if(!initialized){$("<canvas id='"+hudContainer+"' name='"+hudContainer+"' class='hudCANVAS'></canvas>").insertAfter(parent);canvasElem=document.getElementById(hudContainer);_addCanvasAttributes();context=canvasElem.getContext('2d');trace("Canvas element is ["+canvasElem+"]");initialized=true;parent.parentNode.addEventListener("mouseup",socialListener);parent.parentNode.addEventListener("touchend",touch);if(window.innerHeight>window.innerWidth){trace("Portrait  gameProps["+gameProps.orientation+"]");if(gameProps.orientation==(PORTRAIT||2))publicAPI.goodRotation();else publicAPI.badRotation();}else{trace("Landscape gameProps["+gameProps.orientation+"]");if(gameProps.orientation!=(PORTRAIT||2))publicAPI.goodRotation();else publicAPI.badRotation();}
window.addEventListener("resize",function(){console.log("resize");_addCanvasAttributes();if(window.innerHeight>window.innerWidth){trace("Portrait  gameProps["+gameProps.orientation+"]");if(gameProps.orientation==(PORTRAIT||2))publicAPI.goodRotation();else publicAPI.badRotation();}else{trace("Landscape gameProps["+gameProps.orientation+"]");if(gameProps.orientation!=(PORTRAIT||2))publicAPI.goodRotation();else publicAPI.badRotation();}
drawIcons();});}}
function touch(event){trace("Called touch event");var rect=canvasElem.getBoundingClientRect();var first=event.changedTouches[0];x=Math.round((first.pageX-rect.left)/(rect.right-rect.left)*canvasElem.width);y=Math.round((first.pageY-rect.top)/(rect.bottom-rect.top)*canvasElem.height);testHit(x,y);}
function socialListener(event)
{trace("Called SocialListener");var rect=canvasElem.getBoundingClientRect();x=Math.round((event.clientX-rect.left)/(rect.right-rect.left)*canvasElem.width);y=Math.round((event.clientY-rect.top)/(rect.bottom-rect.top)*canvasElem.height);testHit(x,y);}
function testHit(x,y){elements.forEach(function(element){if(y>element.top&&y<element.top+_shareIconSize&&x>element.left&&x<element.left+_shareIconSize)
{element.callback();}});}
function _addCanvasAttributes(){trace("adding canvas attributes    parent ["+parent.id+"]  parent style["+parent.style+"]");parent.style.position="absolute";var attr=parent.attributes;for(var i=0;i<attr.length;i++){trace("Styles ["+attr[i].name+"]  value ["+attr[i].value+"]");if(attr[i].name!="name"&&attr[i].name!="id"&&attr[i].name!="moz-opaque")canvasElem.setAttribute(attr[i].name,attr[i].value);}
canvasElem.style.backgroundColor="transparent";}
function drawIcons(){if(active){elements=[];trace("draw canvasElem ["+canvasElem+"]  parent ["+parent.width+"] parent style["+parent.style+"]");_addCanvasAttributes();context.fillStyle=_shareTextColor;context.font="bold "+_shareTextSize+"px "+_shareFont;context.fillText(_shareCaption,left,top);addIcons();}}
function addIcons()
{var vy=top+10;var vx=left;var margin=10;var textWidth=context.measureText(_shareCaption).width;vx+=(textWidth-((_shareIconSize*activeIcons.length)+(margin*activeIcons.length-1)))/2;for(var i=0;i<activeIcons.length;i++){addIcon(activeIcons[i],vx+(i*(_shareIconSize+margin)),vy);}}
function addIcon(icon,whereX,whereY){trace("Adding ICON ["+icon+"]");var img=new Image();img.vx=whereX;img.vy=whereY;img.onload=function(){context.fillStyle=icons[icon].color;context.fillRect(this.vx,this.vy,_shareIconSize,_shareIconSize);var left=icons[icon].left
var top=icons[icon].top
context.drawImage(img,left,top,50,50,this.vx,this.vy,_shareIconSize,_shareIconSize);};img.src='../gameContainer/img/social_modal_sprite.png';elements.push({top:img.vy,left:img.vx,callback:function(){console.log("Clicked event");publicAPI.share(icons[icon].callBack);}});}
function _createAgeGateHUD(){trace("_createAgeGateHUD  parent["+parent+"]");if(!$('#endgameHUD').length){$("<div id='endgameHUD'></div>").insertAfter(parent.parentNode);var tempHud=document.getElementById('endgameHUD');var attr=parent.attributes
for(var i=0;i<attr.length;i++){if(attr[i].name!="name"&&attr[i].name!="id")tempHud.setAttribute(attr[i].name,attr[i].value);}
$('#endgameHUD').css("height","100%");$('#endgameHUD').css("background-color","transparent");$('#endgameHUD').css("display","none");$('#endgameHUD').css("position","absolute");$('#endgameHUD').css("z-index","4444444");$('#endgameHUD').load("HUD.html",function(){HUDLoaded();});}}
function HUDLoaded(){trace("HUD LOADED");$('#hidden-div').css("display","none");$("#endgameHUD").css("top","10%");$("#outer-age-gate").css("display","none");$("#outer-age-gate-sorry").css("display","none");var dd=new DateDropDown("M:D:Y",$("#age-gate"));$('<center><button value="Submit" type="button" onclick="javascript:gameObj.submitAge();">Submit</button></center>').appendTo($("#age-gate"));}
function redirect(){var str="https://www.facebook.com/dialog/feed?";str+="app_id=145634995501895";str+="&display=popup&caption=Here is what I am sharing";str+="&link=games.disney.com";str+="&redirect_uri=https://developers.facebook.com/tools/explorer";var myWindow=window.open("","Share","width=200, height=100");myWindow.location.href=str;};function _faceBookShare(){FB.ui({method:'feed',name:gameProps.facebookCaption,link:gameProps.gameLink,href:gameProps.gameLink,picture:gameProps.facebookImg,caption:document.title,description:_changeVerbiage(gameProps.facebookVerbiage),message:'Sharing My Score!'},function(response){if(response&&response.post_id){alert('Post was published.');}else{alert('Post was not published.');}});window.DIBIGameTracking({action:"Sharing to Facebook"});}
function _twitterShare(){window.DIBIGameTracking({action:"Sharing to Twitter"});var myWindow=window.open("","Share","width=650, height=441");var vLink="https://twitter.com/intent/tweet?url="+vUrl+"&text="+_changeVerbiage(gameProps.twitterVerbiage);myWindow.location.href=vLink;}
function _pinterestShare(){window.DIBIGameTracking({action:"Sharing to Pinterest"});var myWindow=window.open("","Share","width=650, height=441");var vLink="http://www.pinterest.com/pin/create/button/?url="+vUrl+"&media="+gameProps.pinterestImg+"&amp;description="+_changeVerbiage(gameProps.pinterestVerbiage);myWindow.location.href=vLink;}
function _changeVerbiage(verbiage){if(verbiage.indexOf("@SCORE@")>-1){var tempStr=verbiage.split("@SCORE@");return(tempStr[0]+message+tempStr[1]);}
if(verbiage.indexOf("@placeholder@")>-1){var tempStr=verbiage.split("@placeholder@");return(tempStr[0]+message+tempStr[1]);}}
function _respondToAge(){trace("responding to age");$("#outer-age-gate").css("display","none");$("#outer-age-gate-sorry").css("display","block");}
function _adjustPosition(){$(hudContainer).css("left",parent.style.left);$(hudContainer).css("width",parent.style.width);}
function _ageGate(){_openAgeDiv();}
function _openAgeDiv(){console.log("opening age div");$("#endgameHUD").css("display","block");$("#outer-age-gate").css("display","block");$("#outer-age-gate-sorry").css("display","none");};function _checkCookie(){var name="age=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];trace("Cookie ==> "+c+" is c=name ["+name+"]");if(c.indexOf(name)!=-1)
{var temp=c.split("=");trace("age ["+temp[1]+"]");return temp[1];}}
trace("CheckCookie == undefined");return undefined;};function _storeCookie(cvalue){var d=new Date();var cname="age";var exdays=1;d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+"; "+expires;};function _submitAge(){trace("Submitting age");var date=new Date();var age=new Date($("#Year").val(),$("#Month").val(),$("#Day").val(),date.getHours(),date.getMinutes(),date.getSeconds(),date.getMilliseconds());var testAge=new Date(date.getFullYear()-minAge,date.getMonth(),date.getDay(),date.getHours(),date.getMinutes(),date.getSeconds(),date.getMilliseconds());_storeCookie(age<testAge);if(age<testAge){publicAPI.closeAgeGate();nextStep();}
else{_respondToAge();}}
function trace(msg){if(allowTrace)console.log(msg);}
var publicAPI={name:'HTML5GameContainer',displayIconsFor:function(icons){activeIcons=icons.split(":");},set shareIconSize(size){trace("Setting shareIconSize Size to ["+size+"]");_shareIconSize=size},set shareTextSize(size){trace("Setting shareText Size to ["+size+"]");_shareTextSize=size;},set shareFont(fontFace){_shareFont=fontFace;},set shareCaption(caption){_shareCaption=caption;},set shareTextColor(color){_shareTextColor=color;},setUpShareText:function(caption,color,size,fontFace)
{shareCaption(caption);shareTextColor(color);shareTextSize(size);shareFont(fontFace);},startGame:function(){trace("startGame in HTML5GameContainer");publicAPI.closeSharing();},endGame:function(parnt,gameHUD,scr,x,y){publicAPI.initializeGameCanvas(parnt);publicAPI.displaySharing(scr,x,y);},displaySharing:function(){showSharing(scr,x,y);},showScoreSharing:function(msg,x,y){publicAPI.showSharing(msg,x,y);},showSharing:function(msg,x,y,icons){if(icons!=undefined&&icons!="")activeIcons=icons.split(":");message=msg;left=x;top=y;_createAgeGateHUD();active=true;drawIcons();},closeHUD:function(){publicAPI.closeAgeGate();},closeSharing:function(){if(canvasElem!=undefined){active=false;_removeEndGameHUD();elements=[];var context=canvasElem.getContext('2d');context.clearRect(0,0,canvasElem.width,canvasElem.height);}},submitAge:function(){_submitAge();},initializeGameCanvas:function(canvas){console.log(" Canvas type of ["+canvas.tagName+"]");if(canvas.tagName=="CANVAS"){console.log("Canvas was HTMLCanvasElement");parent=canvas;}else{parent=window.document.getElementById(canvas);}
if(!initialized)_initializeGameCanvas();},share:function(where){age=_checkCookie();$("#fbLink").val(vUrl);$("#endgameHUD").css("display","block");$('#hidden-div').css("display","block");switch(where.toLowerCase()){case "facebook":nextStep=_faceBookShare;break;case "twitter":nextStep=_twitterShare;break;case "pinterest":nextStep=_pinterestShare;break;}
if(age==undefined)
{_ageGate();}else{if(age=="true"){this.closeAgeGate();nextStep();}else{_respondToAge();}}},closeAgeGate:function(){trace("closeAgeGate");$("#endgameHUD").css("display","none");$('#hidden-div').css("display","none");$("#outer-age-gate").css("display","none");$("#outer-age-gate-sorry").css("display","none");},goodRotation:function(){$("#"+hudContainer).css("display","block");$("#endgameHUD").css("display","block");},badRotation:function(){$("#"+hudContainer).css("display","none");$("#endgameHUD").css("display","none");}}
return publicAPI;};