var RESIZER;var BlitWindow=function(options){var options=options||{};var me=this;this.doInitResizer=function(callback){RESIZER={};RESIZER.id="resizer";RESIZER.w=null;RESIZER.h=null;RESIZER.scroll=null;RESIZER.keep=true;RESIZER.was_fullscreen=false;RESIZER.is_fullscreen=false;RESIZER.repeat_frame=0;RESIZER.doUpdate=function(){if(this.repeat_frame>0||this.w!=window.innerWidth||this.h!=window.innerHeight||this.scroll!=document.documentElement.scrollTop){this.repeat_frame=Math.max(0,this.repeat_frame-1);this.w=window.innerWidth;this.h=window.innerHeight;this.is_fullscreen=me.doCheckFullScreen();this.scroll=document.documentElement.scrollTop;window.scrollTo(0,0);if(this.was_fullscreen!=this.is_fullscreen){if(CONTROLS){CONTROLS.doUpdateFullScreen();this.was_fullscreen=this.is_fullscreen;oSTAGE.is_fullscreen=this.is_fullscreen;}}
callback();}}
actives.push(RESIZER);window.addEventListener("fullscreenchange",function(){RESIZER.w=0;RESIZER.h=0;RESIZER.repeat_frame=60;});window.addEventListener("orientationchange",function(){RESIZER.w=0;RESIZER.h=0;RESIZER.repeat_frame=60;});setInterval(function(){var refresh=true;try{if(GAME.is_playing){refresh=false;}}catch(e){};try{if(SCREENS.stage.activeTweens.length>0){refresh=false;}}catch(e){};if(refresh){RESIZER.w=0;RESIZER.h=0;}},1000);}
this.doInitFocusManager=function(callback_lose_focus,callback_get_focus){var document_blurred=false;var doBlur=function(){if(document_blurred){return;}
if(callback_lose_focus){callback_lose_focus();}
document_blurred=true;__snds.stopSound("music");}
var doFocus=function(){if(!document_blurred){return;}
if(callback_get_focus){callback_get_focus();}
document_blurred=false;RESIZER.w=0;RESIZER.h=0;RESIZER.repeat_frame=60;doPlayMusic();}
var visProp=me.doGetHiddenProp();if(visProp){var evtname=visProp.replace(/[H|h]idden/,'')+'visibilitychange';document.addEventListener(evtname,function(evt){if(document[visProp]){doBlur();}else{doFocus();}});}
window.addEventListener("blur",doBlur);window.addEventListener("focus",doFocus);}
this.doGetHiddenProp=function(){var prefixes=['webkit','moz','ms','o'];if('hidden'in document){return 'hidden'};for(var i=0;i<prefixes.length;i++){if((prefixes[i]+'Hidden')in document){return prefixes[i]+'Hidden';}}
return null;}
this.doWindowResize=function(){var wrapper=document.getElementById("wrapper");var footer=document.getElementById("footer");var native_height=lib.properties.height;var native_width=lib.properties.width;oSTAGE.is_landscape=(window.innerWidth>=window.innerHeight)?true:false;oSTAGE.pixel_ratio=__utils.getPixelRatio();var orientation_overlay=document.getElementById("orientation_overlay");if(orientation_overlay){if(platform.isMobile&&oCONFIG.game_orientation=="portrait"&&oSTAGE.is_landscape){orientation_overlay.style.backgroundImage="url('media/images/portrait_only.gif')";orientation_overlay.style.display="block";__snds.forceMute();if(GAME){GAME.doPause();}}else{orientation_overlay.style.display="none";__snds.unforceMute();}}
var footer_scale=Math.min(1,(window.innerWidth/footer.clientWidth),(window.innerHeight/800));footer.my_scale=footer_scale;var footer_space=footer.getBoundingClientRect().height;oSTAGE.window_width=oSTAGE.screen_width=window.innerWidth;oSTAGE.window_height=oSTAGE.screen_height=(window.innerHeight-footer_space);var screen_ratio=oSTAGE.screen_width/oSTAGE.screen_height;var game_ratio=native_width/native_height;var adj_ratio=Math.min(Math.max(screen_ratio,oCONFIG.game_ratio.min),oCONFIG.game_ratio.max);if(adj_ratio>screen_ratio){oSTAGE.wrapper_width=Math.ceil(oSTAGE.window_width)+1;oSTAGE.wrapper_height=Math.ceil(oSTAGE.window_width/adj_ratio);}else{oSTAGE.wrapper_height=Math.ceil(oSTAGE.window_height);oSTAGE.wrapper_width=Math.ceil(oSTAGE.window_height*adj_ratio)+1;}
oSTAGE.scale=Math.min(oSTAGE.wrapper_height/native_height,oSTAGE.wrapper_width/native_width);oSTAGE.scale_inv=1/oSTAGE.scale;oSTAGE.cache_scale=(oSTAGE.scale*oSTAGE.pixel_ratio);oSTAGE.game_width=Math.ceil(oSTAGE.wrapper_width*oSTAGE.scale_inv);oSTAGE.game_height=Math.ceil(oSTAGE.wrapper_height*oSTAGE.scale_inv);oSTAGE.game_native_width=native_width;oSTAGE.game_native_height=native_height;oSTAGE.game_width_margins=((oSTAGE.game_width-native_width)*0.5)|0;oSTAGE.game_height_margins=((oSTAGE.game_height-native_height)*0.5)|0;oSTAGE.game_top=-oSTAGE.game_height_margins;oSTAGE.game_bottom=oSTAGE.game_height-oSTAGE.game_height_margins;oSTAGE.game_left=-oSTAGE.game_width_margins;oSTAGE.game_right=oSTAGE.game_width-oSTAGE.game_width_margins;oSTAGE.game_size={left:-oSTAGE.game_width_margins,top:-oSTAGE.game_height_margins,width:oSTAGE.game_width,height:oSTAGE.game_height,right:oSTAGE.game_width-oSTAGE.game_width_margins,bottom:oSTAGE.game_height-oSTAGE.game_height_margins,center_x:native_width*0.5,center_y:native_height*0.5,native_height:lib.properties.height,native_width:lib.properties.width};wrapper.style.width=oSTAGE.wrapper_width+"px";wrapper.style.height=oSTAGE.wrapper_height+"px";wrapper.style.top="0px";wrapper.style.left=Math.floor((window.innerWidth-wrapper.clientWidth)*0.5)+"px";if(options.force_mobile_top&&platform.isMobile){wrapper.style.top="0px";}else{wrapper.style.top=Math.floor((window.innerHeight-footer_space-wrapper.clientHeight)*0.5)+"px";}
footer.style.width=(oSTAGE.wrapper_width)+"px";footer.style.top=wrapper.offsetTop+oSTAGE.wrapper_height+"px";footer.style.left=wrapper.style.left;for(var i=update_queue.length-1;i>=0;i--){if(update_queue[i].forget){update_queue.splice(i,1);}else if(update_queue[i].doResizeUpdate){update_queue[i].doResizeUpdate();}else{update_queue.splice(i,1);}}}
this.doCheckFullScreen=function(){var isFullScreen=(document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen||document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement);return isFullScreen;}
this.doFullScreenOn=function(){if(oSTAGE.is_fullscreen){return;}
var elem=document.documentElement;if(elem.requestFullscreen){elem.requestFullscreen();}else if(elem.msRequestFullscreen){elem.msRequestFullscreen();}else if(elem.mozRequestFullScreen){elem.mozRequestFullScreen();}else if(elem.webkitRequestFullscreen){elem.webkitRequestFullscreen();}
RESIZER.w=0;}
this.doFullScreenOff=function(){trace("doFullScreenOff()");if(!oSTAGE.is_fullscreen){return;}
var elem=document;trace(elem);if(elem.exitFullscreen){elem.exitFullscreen();}else if(elem.cancelFullScreen){elem.cancelFullScreen();}else if(elem.mozCancelFullScreen){elem.mozCancelFullScreen();}else if(elem.msExitFullscreen){elem.msExitFullscreen();}else if(elem.webkitExitFullscreen){elem.webkitExitFullscreen();}
RESIZER.w=0;}}