var delta,frame_delta;var oGAME;var oTABLE;var PHYSICS;var TRAP;var pl=planck,Vec2=pl.Vec2;var m_world;var ball;var P2M=(1/30)*(1/0.992611);var M2P=3;var physics_queue;var multiply_pending;var mc_hud;var last_multiply;var has_multiply;var skillshot_timeout;var countdown_timeout;var alert_timeout,msgs_timeout;var last_tilt;var tilt_down;var tilt_timeout;var has_tiltlock;var mc_alert,mc_msg;var last_hud_mouse_x=0;var last_hud_mouse_y=0;var mc_msg;var Game=function(){var me=this;__game=this;var resize_updater,frame_updater;me.score=0;me.balls_remaining=oCONFIG.balls;me.is_started=false;me.is_finished=false;me.balls_in_launch_zone=0;me.mallet_hits=0;me.snack_pickups=[false,false,false];me.animation_frame=0;me.actives=[];physics_queue=[];last_multiply=0;last_tilt=0;multiply_pending=false;has_multiply=false;has_tiltlock=false;tilt_down=false;oGAME=new Object();oGAME.balls=[];oGAME.launching=false;oGAME.is_orientationchange=false;oGAME.active_balls=0;oGAME.table=oCONFIG.table;oGAME.tube_count=0;oGAME.is_landscape=oSTAGE.is_landscape;oGAME.shake_adj=0;oGAME.tilts_remaining=3;oTABLE=new Object();oTABLE.actives=[];oTABLE.lights=[];oTABLE.magnets=[];oTABLE.skillshots=[];oTABLE.magnet;oTABLE.trigger_groups={};oTABLE.bonus_groups={};oTABLE.items={};var canvas=document.getElementById("canvas_game");canvas.renderer=canvas.renderer||new THREE.WebGLRenderer({canvas:canvas,antialias:true});canvas.renderer.shadowMap.enabled=false;canvas.renderer.shadowMap.autoUpdate=false;canvas.renderer.autoClear=true;this.doResizeUpdate=function(){me.camera.aspect=oSTAGE.wrapper_width/oSTAGE.wrapper_height;me.camera.updateProjectionMatrix();me.renderer.setSize(oSTAGE.wrapper_width,oSTAGE.wrapper_height);me.renderer.setPixelRatio(__utils.getPixelRatio());var wrapper_ratio=(oSTAGE.wrapper_width/oSTAGE.wrapper_height);var renderer_size=new THREE.Vector2();me.renderer.getSize(renderer_size);var renderer_ratio=renderer_size.width/renderer_size.height;var vFOV=me.camera.fov*Math.PI/180;var visible_height=2*Math.tan(vFOV/2)*1;var visible_width=visible_height*renderer_ratio;var width_pixel_ratio=visible_width/renderer_size.width;var height_pixel_ratio=visible_height/renderer_size.height;GUI.doResize();var table_width=16;var table_height=24;var cam_dist=13;var fov=2*Math.atan(Math.max(table_height,(table_width/renderer_ratio))/(2*cam_dist))*(180/Math.PI);me.camera.fov=fov;me.camera.updateProjectionMatrix();if(me.is_paused){me.renderer.render(me.scene,GAME.camera);}}
this.doNewGame=function(){trace("doNewGame()");me.is_playing=false;me.is_finished=false;TRAP={captured_ball:null,can_trap:true,grace:0};PHYSICS={};PHYSICS.queue=[];PHYSICS.items=[];if(oCONFIG.physics_debug){planck.testbed(function(testbed){PHYSICS.world=pl.World(Vec2(0,15));return PHYSICS.world;});test_canvas=document.body.firstChild;if(test_canvas){test_canvas.style.zIndex=1000;test_canvas.style.pointerEvents="none";}}else{PHYSICS.world=pl.World(Vec2(0,15));}
PHYSICS.world.on('begin-contact',me.BeginContact);PHYSICS.world.on('end-contact',me.EndContact);PHYSICS.world.on('pre-solve',me.PreSolve);PHYSICS.world.on('post-solve',me.PostSolve);m_world=PHYSICS.world;physics_queue=PHYSICS.queue;GAME.score=0;GAME.balls_remaining=oCONFIG.balls;me.is_started=false;me.is_finished=false;me.mallet_hits=0;me.trap_grace=0;me.trap_active=false;me.ball_in_trap=false;me.balls_in_launch_zone=0;me.launcher_active=false;me.launcher_speed=0;me.last_launcher_y=0;me.animation_frame=0;me.actives=[];physics_queue=[];last_multiply=0;last_tilt=0;multiply_pending=false;has_multiply=false;has_tiltlock=false;tilt_down=false;me.sparks_material=null;me.sparks_active=0;me.sparks_frame=0;me.spark_bumpers=[];oGAME=new Object();oGAME.balls=[];oGAME.launching=false;oGAME.is_orientationchange=false;oGAME.active_balls=0;oGAME.table=oCONFIG.table;oGAME.tube_count=0;oGAME.is_landscape=oSTAGE.is_landscape;oGAME.shake_adj=0;oGAME.tilts_remaining=3;oTABLE=new Object();oTABLE.actives=[];oTABLE.lights=[];oTABLE.magnets=[];oTABLE.traps=[];oTABLE.skillshots=[];oTABLE.magnet;oTABLE.trigger_groups={};oTABLE.bonus_groups={};oTABLE.items={};me.doNewLevel();}
this.doNewLevel=function(){me.is_started=false;me.is_finished=false;me.actives=[];me.doInitLevel();}
this.doInit3d=function(){oASSETS.UnlitItemsMaterial=new THREE.MeshBasicMaterial({map:oASSETS.unlit_items,fog:false,side:THREE.FrontSide});oASSETS.LitItemsMaterial=new THREE.MeshBasicMaterial({map:oASSETS.lit_items,fog:false,side:THREE.FrontSide});var table=oASSETS.TableNode.clone();GAME.table=table;me.scene.add(table);table.scale.set(1,1,1);table.position.set(0,0,0);var MovieLogoPlane=GAME.table.getObjectByName("MovieLogoPlane");MovieLogoPlane.material.map.wrapS=THREE.ClampToEdgeWrapping;MovieLogoPlane.material.map.wrapT=THREE.ClampToEdgeWrapping;MovieLogoPlane.material=new THREE.MeshBasicMaterial({map:MovieLogoPlane.material.map,fog:false,side:THREE.FrontSide,transparent:true});GAME.LauncherArrow=oASSETS.arrow.clone();GAME.LauncherArrow.scale.set(1,1,1);GAME.LauncherArrow.position.set(44,1,80);GAME.LauncherArrow.rotateX(__utils.radFromDeg(-40));table.add(GAME.LauncherArrow);GAME.LauncherArrow.doUpdate=function(){if(this.visible){this.rotateY(.1);}}
GAME.actives.push(GAME.LauncherArrow);var pickup1=GAME.table.getObjectByName("cake");pickup1.has=false;pickup1.points=100;pickup1.doUpdate=GAME.doPickups;GAME.actives.push(pickup1);var pickup2=GAME.table.getObjectByName("pie");pickup2.has=false;pickup2.points=200;pickup2.doUpdate=GAME.doPickups;GAME.actives.push(pickup2);var pickup3=GAME.table.getObjectByName("icecream");pickup3.has=false;pickup3.points=300;pickup3.doUpdate=GAME.doPickups;GAME.actives.push(pickup3);var cake=GAME.table.getObjectByName("pCylinder1");cake.is_active=false;cake.rotateX(0.02);cake.points=300;cake.doUpdate=function(){if(this.is_active){this.rotateY(.1);}}
GAME.cake=cake;GAME.actives.push(cake);var kicker1=GAME.table.getObjectByName("plunger_02");kicker1.position.z+=.85;var kicker2=GAME.table.getObjectByName("plunger_03");kicker2.position.z+=.85;me.snack_pickups=[pickup1,pickup2,pickup3];}
this.doInitLevel=function(){trace("doInitLevel()");__snds.stopSound("music");music_playing=null;window.focus();me.is_playing=false;me.actives=[];me.renderer=canvas.renderer;me.scene=new THREE.Scene();me.camera=new THREE.PerspectiveCamera(80,oSTAGE.screen_width/oSTAGE.screen_height,0.1,100);me.scene.add(me.camera);me.scene.background=oASSETS.GeneralBackground;me.doInit3d();me.doGenerateTable(oGAME.table);var group_array=oTABLE.trigger_groups['group_'+4];for(var i=0;i<group_array.length;i++){var body=group_array[i];PHYSICS.queue.push({me:body,action:GAME.doDeactivateBody});if(body.getUserData().object){body.getUserData().object.visible=false;}}
GUI=new GameGUI();GUI.doUpdateScore();GUI.doUpdateBalls();GAME.camera.position.set(23,45,88);GAME.camera.lookAt(23,0,60);GAME.camera.position.set(23,45,76);GAME.camera.lookAt(23,0,57);me.doResizeUpdate();resize_updater={doResizeUpdate:me.doResizeUpdate};update_queue.push(resize_updater);frame_updater={doUpdate:me.doFrameUpdate};actives.push(frame_updater);me.renderer.render(me.scene,me.camera);canvas.style.display="block";me.doResizeUpdate();setTimeout(me.doGo,1000);}
this.doGo=function(){trace("doGo()");music_playing="music_game_loop";doPlayMusic();CONTROLS.doShowPause();me.is_started=true;me.is_playing=true;me.is_finished=false;__input.click_pending=false;__input.release_pending=false;clock.start();frame_delta=0;GAME.doNewBall();GUI.doFadeIn();}
this.doQuit=function(){trace("doQuit()");__snds.stopSound("music");music_playing=null;me.doDestroy();me.is_playing=false;me.is_paused=false;me.is_finished=false;canvas.style.display="none";createjs.Ticker.paused=false;CONTROLS.doHidePause();SCENE=new TitleScreen();}
this.doGotoRecap=function(){trace("doGotoRecap()");__snds.stopSound("music");music_playing=null;oUSER.best_score=Math.max(oUSER.best_score,me.score);__localsaver.doSaveData("user",oUSER);me.doDestroy();SCENE=new RecapScreen({});}
this.doPause=function(){if(!me.is_playing){return;}
if(!me.is_paused){me.is_paused=true;OVERLAY=new PauseMenu("canvas_overlay");}}
this.doResume=function(){me.is_paused=false;resume_grace=10;}
this.doWin=function(){trace("doWin()");__snds.playSound("end_music","music");me.is_playing=false;me.is_paused=false;me.is_finished=true;me.has_won=true;CONTROLS.doHidePause();GUI.doFadeOut();setTimeout(me.doGotoRecap,1250);}
this.doGameOver=function(){trace("doGameOver()");__snds.stopSound("music");music_playing=null;me.is_playing=false;me.is_paused=false;me.is_finished=false;CONTROLS.doHidePause();GUI.doFadeOut();setTimeout(me.doGotoRecap,1250);}
this.doDestroy=function(){trace("--> doDestroy()");canvas.style.display="none";me.forget=true;me.actives=[];resize_updater.forget=true;frame_updater.forget=true;clock.stop();me.doDestroyPhysicsWorld();if(me.scene){while(me.scene.children.length>0){me.scene.remove(me.scene.children[0]);}}
me.scene=null;}
this.doHide=function(){canvas.style.display="none";}
var br_mouse=new THREE.Vector2();var bl_mouse=new THREE.Vector2();var left_is_over=false;var right_is_over=false;var launcher_is_over=false;var using_pointer=false;var launcher_down=false;var launcher_dragging=false;var launcher_down_pending=false;var launcher_release_pending=false;var dist=0;this.doFrameUpdate=function(){frame_delta=clock.getDelta();var adj_scale=1;var left_over=false;var left_down=false;var left_clicked=false;var right_over=false;var right_down=false;var right_clicked=false;var launcher_over=false;var launcher_down=false;var launcher_clicked=false;if(!me.is_paused){me.animation_frame++;PHYSICS.world.step(frame_delta,3,3);PHYSICS.world.clearForces();for(var i=0;i<PHYSICS.queue.length;i++){PHYSICS.queue[i].action(PHYSICS.queue[i].me);}
PHYSICS.queue=[];var highest_y=0;var balls=0;if(!platform.isTouchDevice||__input.mouse_is_down){var touches;if(platform.isTouchDevice){touches=__input.doGetTouches();}else{touches=[{id:0,mouse_is_down:__input.mouse_is_down,click_pending:__input.click_pending,my_x:__input.mouse_x,my_y:__input.mouse_y,speed_x:__input.speed_x,speed_y:__input.speed_y}];}
for(var i=0;i<touches.length;i++){var touch=touches[i];var target_size=oSTAGE.game_width*0.5;bl_mouse.x=(touch.my_x)*(adj_scale);bl_mouse.y=(oSTAGE.game_height-touch.my_y)*(adj_scale);if(bl_mouse.x<target_size&&bl_mouse.y<target_size){left_over=true;left_down=touch.mouse_is_down;left_clicked=touch.click_pending;}
br_mouse.x=(oSTAGE.game_width-touch.my_x)*(adj_scale);br_mouse.y=(oSTAGE.game_height-touch.my_y)*(adj_scale);if(br_mouse.x<target_size&&br_mouse.y<target_size){right_over=true;right_down=touch.mouse_is_down;right_clicked=touch.click_pending;}
br_mouse.x=(oSTAGE.game_width-touch.my_x)*(adj_scale);br_mouse.y=(oSTAGE.game_height-touch.my_y)*(adj_scale);if(br_mouse.x<target_size&&br_mouse.y>target_size){launcher_over=true;launcher_down=touch.mouse_is_down;launcher_clicked=touch.click_pending;}
if(GAME.balls_in_launch_zone>0){if(touch.mouse_is_down){if(!GAME.launcher_active){GAME.launcher_active=true;GAME.last_launcher_y=touch.my_y;}
GAME.launcher_speed=(touch.my_y-GAME.last_launcher_y)*0.5;GAME.last_launcher_y=touch.my_y;}else{GAME.launcher_active=false;}}else{GAME.launcher_active=false;}}
touch.click_pending=false;if(__input.left||(left_over&&left_down)){__input.want_left=true;}else{__input.want_left=false;}
if(__input.right||(right_over&&right_down)){__input.want_right=true;}else{__input.want_right=false;}
if(__input.dn){__input.want_key_launcher=true;}else{__input.want_key_launcher=false;}}else{__input.want_left=false;__input.want_right=false;__input.want_key_launcher=false;__input.want_touch_launcher=false;GAME.launcher_active=false;}
if(GAME.sparks_active>0){GAME.sparks_frame++;if(GAME.sparks_frame>1){GAME.sparks_frame=0;GAME.sparks_material.map.offset.x+=(1/6);if(GAME.sparks_material.map.offset.x>=1){GAME.sparks_material.map.offset.x=0;}}}
for(var i=me.actives.length-1;i>=0;i--){if(me.actives[i]){me.actives[i].doUpdate(me.actives[i]);if(me.actives[i].forget){me.actives.splice(i,1);}
if(me.actives[i].need_destroy){if(me.actives[i].rb){PHYSICS.world.destroyBody(me.actives[i].rb);}
GAME.scene.remove(me.actives[i]);me.actives.splice(i,1);continue;}}else{me.actives.splice(i,1);}}
me.renderer.render(me.scene,me.camera);}}}