function trace(msg){if(oCONFIG.debug_trace){try{console.log(msg);}catch(e){}
if(oCONFIG.debug_panel){var panel=document.getElementById("debug");if(panel){panel.style.display="block";panel.innerHTML=msg+"<br>"+panel.innerHTML;}}}}
var myNav=navigator.userAgent.toLowerCase();function doGetBrowser(){var ua=navigator.userAgent,tem,M=ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(M[1])){tem=/\brv[ :]+(\d+)/g.exec(ua)||[];return{name:'IE',version:(tem[1]||'')};}
if(M[1]==='Chrome'){tem=ua.match(/\bOPR|Edge\/(\d+)/)
if(tem!=null){return{name:'Opera',version:tem[1]};}}
M=M[2]?[M[1],M[2]]:[navigator.appName,navigator.appVersion,'-?'];if((tem=ua.match(/version\/(\d+)/i))!=null){M.splice(1,1,tem[1]);}
return{name:M[0],version:M[1]};}
function is_touch_device(){return(('ontouchstart'in window)||(navigator.MaxTouchPoints>0)||(navigator.msMaxTouchPoints>0));}
var platform={isAndroid:navigator.userAgent.match(/Android/i),isBlackBerry:navigator.userAgent.match(/BlackBerry/i),isiOS:navigator.userAgent.match(/iPhone|iPad|iPod/i),isMobileOpera:navigator.userAgent.match(/Opera Mini/i),isMobileWindows:navigator.userAgent.match(/IEMobile/i),isTouchDevice:is_touch_device(),isMobile:(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/iPhone|iPad|iPod/i)||navigator.userAgent.match(/Opera Mini/i)||navigator.userAgent.match(/IEMobile/i)),isIE:((myNav.indexOf("msie")!=-1)||(navigator.appName=="Microsoft Internet Explorer")||((navigator.appName=="Netscape")&&(new RegExp("Trident/.*rv:([0-9]{1,}[\.0-9]{0,})").exec(navigator.userAgent)!=null))),isFirefox:navigator.userAgent.match(/Firefox/i),isChrome:navigator.userAgent.match(/Chrome/i),isWindows:(window.navigator.platform.indexOf("Win")!=-1),isIE11:(!!window.MSInputMethodContext&&!!document.documentMode)}
var support={gzip:false,canvas:!!window.CanvasRenderingContext2D,webgl:(function(){try{var canvas=document.createElement('canvas');return!!(window.WebGLRenderingContext&&(canvas.getContext('webgl')||canvas.getContext('experimental-webgl')));}catch(e){return false;}})(),workers:!!window.Worker,fileapi:window.File&&window.FileReader&&window.FileList&&window.Blob,clamped_array:window.Uint8ClampedArray,zoom:document.createElement("detect").style.zoom===""};function doPrep(){trace("doPrep()");if("console"in window==false){console={log:function(){},error:function(){}};}
Math.log2=Math.log2||function(x){return Math.log(x)*Math.LOG2E;};var parseXml;if(window.DOMParser){parseXml=function(xmlStr){var parser=new window.DOMParser();var xmlDoc=parser.parseFromString(xmlStr,"text/xml");return xmlDoc;};}else if(typeof window.ActiveXObject!="undefined"&&new window.ActiveXObject("Microsoft.XMLDOM")){parseXml=function(xmlStr){var xmlDoc=new window.ActiveXObject("Microsoft.XMLDOM");xmlDoc.async="false";xmlDoc.loadXML(xmlStr);return xmlDoc;};}else{parseXml=function(){return null;}}
if(!String.prototype.includes){String.prototype.includes=function(search,start){if(typeof start!=='number'){start=0;}
if(start+search.length>this.length){return false;}else{return this.indexOf(search,start)!==-1;}};}
Date.now=(Date.now||function(){return new Date().getTime();});if("performance"in window==false){window.performance={offset:Date.now(),now:function now(){return Date.now()-this.offset;}};}
my_performance={offset:Date.now(),now:function now(){return Date.now()-this.offset;}};if(!window.requestAnimationFrame){window.requestAnimationFrame=function(callback,element){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};}
doLoadLanguage();}
function doLoadLanguage(){trace("doLoadLanguage()");var http=new XMLHttpRequest();var url=oCONFIG.language_file;http.open("GET",url,true);http.onreadystatechange=function(){if(http.readyState==4&&http.status==200){var myxml=http.responseXML||parseXml(http.responseText);var root=myxml.documentElement;oLANG={};oLANG_IMAGES={};oLANG_FONTS={};var textnodes=root.getElementsByTagName("txt");if(textnodes){for(var i=0;i<textnodes.length;i++){var my_node=textnodes[i];var o={};o.id=my_node.getAttribute('id');for(var ii=0;ii<my_node.attributes.length;ii++){var attrib=my_node.attributes[ii];if(attrib.specified){o[attrib.name]=attrib.value;}}
if(my_node.childNodes[0]){o.value=my_node.childNodes[0].nodeValue;}else{o.value="";}
oLANG[o.id]=o;}}
var imagenodes=root.getElementsByTagName("img");if(imagenodes){for(var i=0;i<imagenodes.length;i++){var my_node=imagenodes[i];var my_id=my_node.getAttribute('id');var my_value=my_node.childNodes[0].nodeValue;oLANG_IMAGES[my_id]=my_value;}}
var confignodes=root.getElementsByTagName("config");if(confignodes){for(var i=0;i<confignodes.length;i++){var my_node=confignodes[i];var my_id=my_node.getAttribute('id');var my_value=my_node.childNodes[0].nodeValue;if(my_value=="true"){my_value=true;}
if(my_value=="false"){my_value=false;}
oCONFIG[my_id]=my_value;}}
var browser_ok=true;if(!support.clamped_array){browser_ok=false;}
if(platform.isIE11&&oCONFIG.blockIE11){browser_ok=false;}
if(oCONFIG.support_checks){if(oCONFIG.support_checks.canvas&&!support.canvas){browser_ok=false;}
if(oCONFIG.support_checks.webgl&&!support.webgl){browser_ok=false;}}
if(!support.canvas||!support.webgl||!support.clamped_array){browser_ok=false;}
if(browser_ok){doInit();}else{doBrowserAlert();}}}
http.send(null);}
var legal_links,legal_images,legal_copyrights,main_site_url,more_games_url,instructions_mobile,instructions_desktop,legal_special_1,legal_special_2;var billing_block_version=-1;var legal_block_scale=1;function doProcessData(){legal_images=[];legal_links=[];legal_copyrights=[];instructions_mobile=[];instructions_desktop=[];legal_special_1=[];legal_special_2=[];for(var s in oLANG){var o=oLANG[s];if(o.phase){if(parseInt(o.phase)!=current_phase){continue;}}
if(o.active=="true"){switch(o.type){case "legal_special_1":if(o.after=="break"){o.after="<BR>";}
legal_special_1.push({msg:o.id,after:o.after||null});break;case "legal_special_2":if(o.after=="break"){o.after="<BR>";}
legal_special_2.push({msg:o.id,after:o.after||null});break;case "legal_image":legal_images.push({src:o.value,alt:o.alt});break;case "legal_link":if(o.after=="break"){o.after="<BR>";}
legal_links.push({msg:o.id,link:o.link||null,action:o.action||null,after:o.after||null,classAdd:o.classAdd||null});break;case "legal_copyright":if(o.after=="break"){o.after="<BR>";}
legal_copyrights.push({msg:o.id,after:o.after||null});break;case "instruction_mobile":instructions_mobile.push({msg:o.id,img:o.img,w:o.w,h:o.h});break;case "instruction_desktop":instructions_desktop.push({msg:o.id,img:o.img,w:o.w,h:o.h});break;case "main_site_url":main_site_url=o.link;break;case "more_games_url":more_games_url=o.link;break;}}}}
function doBrowserAlert(){trace("doBrowserAlert()");var date_release=new Date(oCONFIG.date_playing);var date_tomorrow=new Date(oCONFIG.date_day_before);var date_friday=new Date(oCONFIG.date_week_before);var today_date=new Date();var date_msg;if(today_date>=date_release){date_msg=oLANG.date_msg_4;}else if(today_date>=date_tomorrow){date_msg=oLANG.date_msg_3;}else if(today_date>=date_friday){date_msg=oLANG.date_msg_2;}else{date_msg=oLANG.date_msg_1;}
var overlay=document.getElementById("div_errors");var my_html="";my_html+='<table border="0" width="100%" height="100%" cellpadding="40"><tr><td align="center" valign="middle">';my_html+='<img border="0" width="245" src="'+oLANG_IMAGES.MovieLogo+'"/>'+'<p>';my_html+=oLANG.browser_alert.value+'<p>';my_html+='<a href="https://www.google.com/chrome/browser/"><img border="0" src="media/browser_icons/icon_chrome.png" width="64" height="64" alt="Chrome"/></a>';my_html+='<a href="http://www.mozilla.org/firefox/new/"><img border="0" src="media/browser_icons/icon_firefox.png" width="64" height="64" alt="Firefox"/></a>';my_html+='<a href="https://www.microsoft.com/microsoft-edge"><img border="0" src="media/browser_icons/icon_edge.png" width="64" height="64" alt="Edge"/></a>';my_html+='<a href="http://www.apple.com/safari/"><img border="0" src="media/browser_icons/icon_safari.png" width="64" height="64" alt="Safari"/></a>';my_html+='<a href="http://www.opera.com/"><img border="0" src="media/browser_icons/icon_opera.png" width="64" height="64" alt="Opera"/></a>';my_html+='</td></tr></table>';overlay.innerHTML=my_html;overlay.style.display="inline-block";}