{
	"version": 1595509593,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/die1-sheet0.png",
		"images/die1-sheet1.png",
		"images/die1-sheet2.png",
		"images/rollbtn-sheet0.png",
		"images/rollbtn-sheet1.png",
		"images/board-sheet0.png",
		"images/helpbtn-sheet0.png",
		"images/helpbtn-sheet1.png",
		"images/help-sheet0.png",
		"images/menusprt-sheet0.png",
		"images/menubtn-sheet0.png",
		"images/menubtn-sheet1.png",
		"images/flip-sheet0.png",
		"images/flip-sheet1.png",
		"images/flip-sheet2.png",
		"images/flip-sheet3.png",
		"images/flip-sheet4.png",
		"media/beep_ 1.m4a",
		"media/beep_ 1.ogg",
		"media/beep_ 10.m4a",
		"media/beep_ 10.ogg",
		"media/beep_ 11.m4a",
		"media/beep_ 11.ogg",
		"media/beep_ 12.m4a",
		"media/beep_ 12.ogg",
		"media/beep_ 2.m4a",
		"media/beep_ 2.ogg",
		"media/beep_ 3.m4a",
		"media/beep_ 3.ogg",
		"media/beep_ 4.m4a",
		"media/beep_ 4.ogg",
		"media/beep_ 5.m4a",
		"media/beep_ 5.ogg",
		"media/beep_ 6.m4a",
		"media/beep_ 6.ogg",
		"media/beep_ 7.m4a",
		"media/beep_ 7.ogg",
		"media/beep_ 8.m4a",
		"media/beep_ 8.ogg",
		"media/beep_ 9.m4a",
		"media/beep_ 9.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buzz.m4a",
		"media/buzz.ogg",
		"media/computer.m4a",
		"media/computer.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}