AvalancheSnowboarding.Slope=function(game,gameScene,parent){Phaser.Group.call(this,game,parent);this.gameScene=gameScene;this.endObject=null;this.endFrontObject=null;this.avalanche=new AvalancheSnowboarding.Avalanche(this.game,gameScene);this.add(this.avalanche);this.snowTiles=[];for(i=0;i<2;i++){var snowTile=this.game.add.image(i*968.8,-110+i*473.1,'snowTile');this.add(snowTile);this.snowTiles.push(snowTile);}
this.jumpFrame=this.create(this.game.world.width/2,-this.game.world.height*1.28,'jumpFrame');this.jumpFrameIn=this.jumpFrame.animations.add('in',Phaser.Animation.generateFrameNames('jumpFrameIn',1,11,'.png',4),30,false);this.jumpFrameIn.onStart.add(function(){this.jumpFrame.visible=true;if(!this.game.sound.mute)
this.audioArrowFramePop.play();},this);this.jumpFrameIn.onComplete.add(function(){this.createArrows(AvalancheSnowboarding.Model.numJumpsFromPlatform+1);if(!this.game.device.desktop){this.createArrowButtons();}
this.jumpCircle.visible=true;this.jumpCircle.play('idle');this.jumpCircle.bringToTop();this.isArrowGameWon=null;},this);this.jumpFrameOut=this.jumpFrame.animations.add('out',Phaser.Animation.generateFrameNames('jumpFrameOut',1,10,'.png',4),30,false);this.jumpFrameOut.onStart.add(function(){this.jumpCircle.visible=false;if(!this.game.sound.mute)
this.audioArrowFrameUnpop.play();},this);this.jumpFrameOut.onComplete.add(function(){this.jumpFrameOut.visible=false;},this);this.jumpFrame.anchor.setTo(0.5,0.5);this.jumpFrame.visible=false;this.jumpCircle=this.create(0,0,'jumpCircle');this.jumpCircleIdle=this.jumpCircle.animations.add('idle',Phaser.Animation.generateFrameNames('jumpCircleActive',1,19,'.png',4),30,true);this.jumpCircleCorrect=this.jumpCircle.animations.add('correct',Phaser.Animation.generateFrameNames('jumpCircleCorrect',1,19,'.png',4),30,false);this.jumpCircleCorrect.onComplete.add(function(){this.jumpCircle.play('idle');},this);this.jumpCircleIncorrect=this.jumpCircle.animations.add('incorrect',Phaser.Animation.generateFrameNames('jumpCircleIncorrect',1,20,'.png',4),30,false);this.jumpCircleIncorrect.onStart.add(function(){if(!this.game.sound.mute)
this.audioJolt.play();},this);this.jumpCircleIncorrect.onComplete.add(function(){this.jumpCircle.play('idle');},this);this.jumpCircle.anchor.setTo(0.5,0.5);this.jumpCircle.x=this.jumpFrame.x-this.jumpCircle.width*1.76;this.jumpCircle.y=this.jumpFrame.y+this.jumpCircle.height*0.65;this.jumpCircle.visible=false;this.allArrows=[];this.allArrowButtons=[];this.allArrowButtonsByCode={};this.objectsLayer=this.game.add.group();this.add(this.objectsLayer);this.levelData=this.game.cache.getJSON('levels');this.allObjectsData=this.levelData.objects;this.nextObjectIndex=0;this.allObjects=[];this.slopeAngle=Math.tan(AvalancheSnowboarding.C.snowTileShift.y/AvalancheSnowboarding.C.snowTileShift.x);this.bringToTop(this.avalanche);this.initialProperties={x:this.x,y:this.y,};this.audioArrowFramePop=this.game.add.audio('arrowFramePop');this.audioArrowFrameUnpop=this.game.add.audio('arrowFrameUnpop');this.audioArrowPop=this.game.add.audio('arrowPop');this.audioArrowThrow=this.game.add.audio('arrowThrow');this.audioJolt=this.game.add.audio('jolt');this.audioPickup=this.game.add.audio('pickup');this.audioTurbo=this.game.add.audio('turbo');};AvalancheSnowboarding.Slope.prototype=Object.create(Phaser.Group.prototype);AvalancheSnowboarding.Slope.constructor=AvalancheSnowboarding.Slope;AvalancheSnowboarding.Slope.prototype.update=function(){};AvalancheSnowboarding.Slope.prototype.move=function(currentSpeed,distance,distanceTotal){for(var i=0;i<this.allObjects.length;i++){var obj=this.allObjects[i];this.game.physics.arcade.overlap(this.gameScene.player.view,obj.view,this.playerCollisionHandler,null,this);}
if(this.slopeJumpUpTweenData!=null){AvalancheSnowboarding.C.processTween(this.slopeJumpUpTweenData);}else if(this.slopeJumpDownTweenData!=null){AvalancheSnowboarding.C.processTween(this.slopeJumpDownTweenData);}
var slopeStopped=false;for(i=0;i<this.snowTiles.length;i++){var tile=this.snowTiles[i];tile.x+=currentSpeed.x;tile.y+=currentSpeed.y;}
if(this.endObject!=null){this.endObject.x=this.endObject.x<=-217?-217:this.endObject.x+currentSpeed.x;this.endObject.y=this.endObject.y<=-226?-226:this.endObject.y+currentSpeed.y;this.endFrontObject.x=this.endObject.x;this.endFrontObject.y=this.endObject.y;slopeStopped=this.endObject.x==-217&&this.endObject.y==-226;}
if(this.endObject==null&&this.snowTiles[0].x<=-this.snowTiles[0].width){this.snowTiles[0].x+=AvalancheSnowboarding.C.snowTileShift.x*2;this.snowTiles[0].y+=AvalancheSnowboarding.C.snowTileShift.y*2;this.snowTiles.push(this.snowTiles.shift());}
if(!this.gameScene.player.isFinishLineCrossed&&this.endObject!=null&&this.gameScene.player.view.x>=this.endObject.x+217){this.gameScene.player.isFinishLineCrossed=true;this.gameScene.player.switchAnimation('goN');}else if(!this.gameScene.player.isWinAnimationStarted&&slopeStopped){this.gameScene.player.isWinAnimationStarted=true;this.gameScene.player.switchAnimation('arrive');}
this.avalanche.move(distance);while(this.nextObjectIndex<this.allObjectsData.length&&Number(this.allObjectsData[this.nextObjectIndex].x)-distance<=500){var objectData=this.allObjectsData[this.nextObjectIndex];if(objectData.type.toLowerCase()=='end'){this.avalanche.setSpeed(AvalancheSnowboarding.C.speedNone);var lastSnowTile=this.snowTiles[this.snowTiles.length-1];this.endObject=this.game.add.sprite(0,0,'backgroundEnd');this.add(this.endObject);this.endObject.x=lastSnowTile.x+lastSnowTile.width;this.endObject.y=lastSnowTile.y+345;this.gameScene.player.view.bringToTop();this.endFrontObject=this.game.add.sprite(0,0,'backgroundEndFront');this.add(this.endFrontObject);this.endObject.x=this.endObject.x;this.endObject.y=this.endObject.y;}else{this.createObjectSprite(this.allObjectsData[this.nextObjectIndex],distance);}
this.nextObjectIndex++;}
for(var i=this.allObjects.length-1;i>=0;i--){var obj=this.allObjects[i];if(obj.view.x<=-obj.view.width/2||obj.view.y<=-obj.view.height/2||obj.destroyOnTick){obj.destroy();this.allObjects.splice(i,1);}else if(obj.type!='star'||!obj.isOverlapped)
{obj.moveBy(currentSpeed.x,currentSpeed.y);}}
if(this.isArrowGameWon!=null){for(var i=this.allArrows.length-1;i>=0;i--){var arrow=this.allArrows[i];if(!arrow.correctKeyPressed||!arrow.correctKeyReleased){arrow.tweenVisibility.stop();arrow.tweenVisibility=null;arrow.tweenScale.stop();arrow.tweenScale=null;arrow.tweenMove.stop();arrow.tweenMove=null;arrow.tweenMove=this.game.add.tween(arrow.scale).to({x:0,y:0},200,Phaser.Easing.Linear.None);arrow.tweenMove.onComplete.addOnce(function(){this.destroyNow();},arrow);arrow.tweenMove.start();}}
AvalancheSnowboarding.Model.wasPreviousArrowGameWon=this.isArrowGameWon;if(this.isArrowGameWon==false){this.jumpCircle.play('incorrect');var scaleTween=this.game.add.tween(this.jumpCircle.scale).to({x:1.5,y:1.5},125,Phaser.Easing.Linear.None).to({x:1,y:1},125,Phaser.Easing.Linear.None).start();scaleTween.onComplete.addOnce(function(){this.gameScene.player.switchAnimation('badFall');this.jumpFrame.play('out');this.jumpFrameOut.onComplete.addOnce(function(){this.jumpDown();this.gameScene.player.jumpDown();},this);},this);}else if(this.isArrowGameWon==true){this.gameScene.player.switchAnimation('twister1');this.gameScene.player.playerTwister2.onStart.addOnce(function(){this.jumpFrame.play('out');},this);this.gameScene.player.playerTwister2.onComplete.addOnce(function(){this.jumpDown();this.gameScene.player.jumpDown();},this);}
if(!this.game.device.desktop&&this.isArrowGameWon!=null){this.destroyArrowButtons();}
this.isArrowGameWon=null;}}
AvalancheSnowboarding.Slope.prototype.jumpUp=function(){this.slopeJumpUpTweenData={target:this,xInitial:this.initialProperties.x,yInitial:this.initialProperties.y,xBy:0,yBy:this.game.world.height*1.4,ease:AvalancheSnowboarding.C.easeOut,framesTotal:0.4*60,context:this,onComplete:function(that){that.slopeJumpUpTweenData=null;that.jumpFrame.play('in');},};}
AvalancheSnowboarding.Slope.prototype.jumpDown=function(){this.slopeJumpDownTweenData={target:this,xInitial:this.x,yInitial:this.y,xBy:this.initialProperties.x-this.x,yBy:this.initialProperties.y-this.y,ease:AvalancheSnowboarding.C.easeIn,framesTotal:0.4*60,context:this,onComplete:function(that){that.slopeJumpDownTweenData=null;},};}
AvalancheSnowboarding.Slope.prototype.createObjectSprite=function(objectData,distance){var m=new PIXI.Matrix();m.tx=Number(objectData.x)-distance;m.ty=Number(objectData.y);m.rotate(this.slopeAngle);var type=objectData.type.toLowerCase();var obj=new AvalancheSnowboarding.CollideableObject();obj.init({game:this.game,type:type,name:type,rotation:0,x:m.tx+AvalancheSnowboarding.C.screenShiftForObjects.x,y:m.ty+AvalancheSnowboarding.C.screenShiftForObjects.y,layer:this.objectsLayer,xInitial:objectData.x,yInitial:objectData.y,})
this.allObjects.push(obj);return obj;}
AvalancheSnowboarding.Slope.prototype.playerCollisionHandler=function(playerView,objectView){var player=playerView.obj;if(player.isHitByAvalanche)
return;var obj=objectView.obj;if(!obj.isOverlapped){obj.isOverlapped=true;if(obj.type=='star'){obj.tweenTo(this.gameScene.hud.scoreContainer.x+this.gameScene.hud.scoreContainer.width/2,this.gameScene.hud.scoreContainer.y+this.gameScene.hud.scoreContainer.height/2,function(context){context.gameScene.hud.addScore(AvalancheSnowboarding.C.scoreStar);},this);if(!this.game.sound.mute)
this.audioPickup.play();}else if(obj.type=='rock'&&!player.isBlinking){player.switchAnimation('stumble');}else if(obj.type=='speed-up'){player.setSpeed(AvalancheSnowboarding.C.speedFast);if(!this.game.sound.mute)
this.audioTurbo.play();}else if(obj.type=='jump-platform'){AvalancheSnowboarding.Model.numJumpsFromPlatform++;player.switchAnimation('jumpWhenHitPlatform');this.jumpUp();player.jumpUp();}}};AvalancheSnowboarding.Slope.prototype.createArrows=function(numArrows){AvalancheSnowboarding.Model.numArrowsInPreviousArrowGame=Math.min(numArrows,AvalancheSnowboarding.C.maxArrowsInArrowGame);for(var i=0;i<numArrows;i++){var arrow=this.create(0,0,'arrow');var arrowWidth=arrow.width;var orientation=Math.floor(Math.random()*4);arrow.anchor.setTo(0.5,0.5);arrow.x=this.jumpFrame.x+this.jumpFrame.width/2-arrow.width;arrow.y=this.jumpCircle.y;arrow.visible=false;arrow.scale.setTo(0,0);arrow.rotation=orientation*Math.PI/2;arrow.correctKey=orientation==0?this.game.input.keyboard.addKey(Phaser.Keyboard.RIGHT):orientation==1?this.game.input.keyboard.addKey(Phaser.Keyboard.DOWN):orientation==2?this.game.input.keyboard.addKey(Phaser.Keyboard.LEFT):this.game.input.keyboard.addKey(Phaser.Keyboard.UP);arrow.correctKeyPressed=false;arrow.correctKeyReleased=false;arrow.correctButtonKeyCode=arrow.correctKey.keyCode;arrow.destroyNow=function(){var slope=this.parent;for(var i=0;i<slope.allArrows.length;i++){var arrow=slope.allArrows[i];if(arrow==this){slope.allArrows.splice(i,1);arrow.destroy();break;}}};arrow.tweenVisibility=this.game.add.tween(arrow).to({visible:true},1+500*i);arrow.tweenScale=this.game.add.tween(arrow.scale).to({x:1.5,y:1.5},150,Phaser.Easing.Quadratic.Out).to({x:1,y:1},100,Phaser.Easing.Quadratic.Out);arrow.tweenScale.onStart.addOnce(function(){if(!this.game.sound.mute)
this.audioArrowPop.play();},this);arrow.tweenMove=this.game.add.tween(arrow).to({x:this.jumpCircle.x-this.jumpCircle.width*0.4},1500,Phaser.Easing.Linear.None);arrow.tweenMove.onUpdateCallback(function(tween){var arrow=tween.target;var xLeft=tween.properties.x;var xRight=this.jumpCircle.x+this.jumpCircle.width/2;if(arrow.x>=xLeft&&arrow.x<=xRight){var isDown=(this.game.device.desktop&&arrow.correctKey.isDown)||(!this.game.device.desktop&&this.allArrowButtonsByCode[arrow.correctButtonKeyCode].input.pointerDown(this.game.input.activePointer.id));var isUp=(this.game.device.desktop&&arrow.correctKey.isUp)||(!this.game.device.desktop&&this.allArrowButtonsByCode[arrow.correctButtonKeyCode].input.pointerDown(this.game.input.activePointer.id));if(!arrow.correctKeyPressed&&!arrow.correctKeyReleased&&isDown){arrow.correctKeyPressed=true;}else if(arrow.correctKeyPressed&&!arrow.correctKeyReleased&&isUp){arrow.correctKeyReleased=true;tween.onUpdateCallback(null);tween.stop();this.jumpCircle.play('correct');var scaleTween=this.game.add.tween(this.jumpCircle.scale).to({x:1.2,y:1.2},125,Phaser.Easing.Linear.None).to({x:1,y:1},125,Phaser.Easing.Linear.None).start();arrow.tweenMove=this.game.add.tween(arrow).to({x:arrow.x+Utils.getRand(100,200)*Utils.getRandomSign(),y:arrow.y+Utils.getRand(50,150),alpha:0,rotation:2*Math.PI*Utils.getRandomSign(),},1000,Phaser.Easing.Quadratic.Out);arrow.tweenMove.onStart.addOnce(function(sprite){this.game.add.tween(sprite.scale).to({x:2,y:2},1000,Phaser.Easing.Quadratic.Out).start();if(!this.game.sound.mute)
this.audioArrowThrow.play();},this);arrow.tweenMove.start();arrow.tweenMove.onComplete.addOnce(function(sprite){sprite.destroyNow();},this);if(this.allArrows[this.allArrows.length-1]==arrow){this.isArrowGameWon=true;}}}},this);arrow.tweenMove.onComplete.addOnce(function(sprite){this.isArrowGameWon=false;},this);arrow.tweenVisibility.chain(arrow.tweenScale,arrow.tweenMove);arrow.tweenVisibility.start();this.allArrows.push(arrow);}}
AvalancheSnowboarding.Slope.prototype.createArrowButtons=function(){for(var i=0;i<4;i++){var btn=this.create(0,0,'arrow');btn.anchor.setTo(0.5,0.5);btn.scale.setTo(2,2);btn.inputEnabled=true;btn.x=this.game.world.width/5*(i+1);btn.y=this.jumpCircle.y+this.game.world.height*0.4;this.allArrowButtons.push(btn);}
this.allArrowButtons[0].keyCode=Phaser.Keyboard.RIGHT;this.allArrowButtons[1].keyCode=Phaser.Keyboard.UP;this.allArrowButtons[1].rotation=3*Math.PI/2;this.allArrowButtons[2].keyCode=Phaser.Keyboard.DOWN;this.allArrowButtons[2].rotation=Math.PI/2;this.allArrowButtons[3].keyCode=Phaser.Keyboard.LEFT;this.allArrowButtons[3].rotation=Math.PI;for(var i=0;i<this.allArrowButtons.length;i++){this.allArrowButtonsByCode[this.allArrowButtons[i].keyCode]=this.allArrowButtons[i];}}
AvalancheSnowboarding.Slope.prototype.destroyArrowButtons=function(){for(var i=0;i<this.allArrowButtons.length;i++){var btn=this.allArrowButtons[i];btn.destroy();}
this.allArrowButtons=[];this.allArrowButtonsByCode={};}
AvalancheSnowboarding.Slope.prototype.destroy=function(){if(this.audioArrowFramePop!=null){this.audioArrowFramePop.stop();this.audioArrowFramePop=null;}
if(this.audioArrowFrameUnpop!=null){this.audioArrowFrameUnpop.stop();this.audioArrowFrameUnpop=null;}
if(this.audioArrowPop!=null){this.audioArrowPop.stop();this.audioArrowPop=null;}
if(this.audioArrowThrow!=null){this.audioArrowThrow.stop();this.audioArrowThrow=null;}
if(this.audioJolt!=null){this.audioJolt.stop();this.audioJolt=null;}
if(this.audioPickup!=null){this.audioPickup.stop();this.audioPickup=null;}
if(this.audioTurbo!=null){this.audioTurbo.stop();this.audioTurbo=null;}};