var LevelData = {
    getPushNotifsData: {
        50   :  { msg: "What a beary furfect bear tower!        "},
        100  :  { msg: "Get your claws on the latest bear tower news!       "},
        150  :  { msg: "Awesome! I'm looking furward at how fur it goes!        "},
        200  :  { msg: "I can bearly wait fur it to finish!     "},
        250  :  { msg: "Hey, the maul's selling beary good bear merch!      "},
        300  :  { msg: "The sight of them is unbearable. They might fall!       "},
        350  :  { msg: "Naked bears? How embearrassing!     "},
        400  :  { msg: "How long are they gonna keep clawing up?        "},
        450  :  { msg: "When will the bear puns end? It's unbearable! Oops.     "},
        500  :  { msg: "Bear in mind that puns will be there fur awhile, Honey.     "},
        550  :  { msg: "At least they're not causing PANDAmonium in the city.       "},
        600  :  { msg: "Don't hibernate and embearce their awesomeness!     "},
        650  :  { msg: "A black market of bear merch in the maul?!      "},
        700  :  { msg: "Women are so bi-POLAR with their bear merch.        "},
        750  :  { msg: "We roarly have decent news these days.      "},
        800  :  { msg: "The reporters are so grizzy with bear news.     "},
        850  :  { msg: "Are they seriously buying those pawful bear shirts?     "},
        900  :  { msg: "Paww~ They're so aroarable, don't you agree?        "},
        950  :  { msg: "Stack fur world record, they said. Like, really?        "},
        1000 :  { msg: "Befur the pawe, take note that they're in danger!       "},
        1100 :  { msg: "Whose bearrific idea is it to build a bear tower?       "},
        1200 :  { msg: "Like dude, take a chill pill. They're fur from harm.        "},
        1300 :  { msg: "They're so close! C'mon guys, be pawsitive!     "},
        1400 :  { msg: "Wow! So it's actually pawsitively pawsible?!        "},
        1500 :  { msg: "Welcome to the Grizzness Book of Records!       "}
    },
    getData: {
        1:     { ground: 10,aerial:  0 ,  pigeon: 0 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 4   },
        7:     { ground: 0, aerial:  6 ,  pigeon: 4 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 4   },
        21:    { ground: 0, aerial:  5 ,  pigeon: 5 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 4   },
        31:    { ground: 0, aerial:  7 ,  pigeon: 5 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 4   },
        41:    { ground: 0, aerial:  5 ,  pigeon: 7 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 4   },
        51:    { ground: 0, aerial:  9 ,  pigeon: 6 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 3.5 },
        66:    { ground: 0, aerial:  10,  pigeon: 5 , gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 3.5 },
        81:    { ground: 0, aerial:  5 ,  pigeon: 10, gSpeed: 2   ,  pSpeed: 2.5 , loadTime: 3.5 },
        101:   { ground: 0, aerial:  11,  pigeon: 4 , gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 3.5 },
        121:   { ground: 0, aerial:  4 ,  pigeon: 11, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 3.5 },
        141:   { ground: 0, aerial:  12,  pigeon: 6 , gSpeed: 2   ,  pSpeed: 3   , loadTime: 3   },
        161:   { ground: 0, aerial:  6 ,  pigeon: 12, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 3   },
        181:   { ground: 0, aerial:  11,  pigeon: 7 , gSpeed: 2   ,  pSpeed: 3   , loadTime: 3   },
        201:   { ground: 0, aerial:  7 ,  pigeon: 11, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 3   },
        226:   { ground: 0, aerial:  10,  pigeon: 8 , gSpeed: 2   ,  pSpeed: 3   , loadTime: 3   },
        251:   { ground: 0, aerial:  8 ,  pigeon: 10, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 3   },
        276:   { ground: 0, aerial:  10,  pigeon: 10, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 3   },
        301:   { ground: 0, aerial:  11,  pigeon: 9 , gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 3   },
        331:   { ground: 0, aerial:  12,  pigeon: 8 , gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 3   },
        361:   { ground: 0, aerial:  13,  pigeon: 7 , gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 3   },
        391:   { ground: 0, aerial:  7 ,  pigeon: 13, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 2.5 },
        421:   { ground: 0, aerial:  16,  pigeon: 9 , gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 2.5 },
        451:   { ground: 0, aerial:  15,  pigeon: 10, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 2.5 },
        481:   { ground: 0, aerial:  14,  pigeon: 11, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 2.5 },
        511:   { ground: 0, aerial:  13,  pigeon: 12, gSpeed: 3   ,  pSpeed: 3.5 , loadTime: 2.5 },
        541:   { ground: 0, aerial:  12,  pigeon: 13, gSpeed: 3   ,  pSpeed: 3.5 , loadTime: 2   },
        571:   { ground: 0, aerial:  20,  pigeon: 10, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 2   },
        601:   { ground: 0, aerial:  19,  pigeon: 11, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 2   },
        631:   { ground: 0, aerial:  18,  pigeon: 12, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 2   },
        661:   { ground: 0, aerial:  17,  pigeon: 13, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 2   },
        691:   { ground: 0, aerial:  13,  pigeon: 17, gSpeed: 3   ,  pSpeed: 3   , loadTime: 2   },
        721:   { ground: 0, aerial:  25,  pigeon: 10, gSpeed: 2   ,  pSpeed: 3.5 , loadTime: 2   },
        751:   { ground: 0, aerial:  23,  pigeon: 12, gSpeed: 2   ,  pSpeed: 3.5 , loadTime: 2   },
        781:   { ground: 0, aerial:  20,  pigeon: 15, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 2   },
        811:   { ground: 0, aerial:  18,  pigeon: 17, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 2   },
        841:   { ground: 0, aerial:  17,  pigeon: 18, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1.5 },
        871:   { ground: 0, aerial:  25,  pigeon: 15, gSpeed: 2   ,  pSpeed: 3.5 , loadTime: 1.5 },
        901:   { ground: 0, aerial:  23,  pigeon: 17, gSpeed: 2   ,  pSpeed: 3   , loadTime: 1.5 },
        931:   { ground: 0, aerial:  20,  pigeon: 20, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1.5 },
        961:   { ground: 0, aerial:  20,  pigeon: 20, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1.5 },
        991:   { ground: 0, aerial:  17,  pigeon: 23, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1   },
        1021:  { ground: 0, aerial:  25,  pigeon: 20, gSpeed: 2   ,  pSpeed: 3.5 , loadTime: 1   },
        1051:  { ground: 0, aerial:  24,  pigeon: 21, gSpeed: 2   ,  pSpeed: 3.5 , loadTime: 1   },
        1081:  { ground: 0, aerial:  23,  pigeon: 22, gSpeed: 3   ,  pSpeed: 3.5 , loadTime: 1   },
        1111:  { ground: 0, aerial:  22,  pigeon: 23, gSpeed: 3   ,  pSpeed: 3   , loadTime: 1   },
        1141:  { ground: 0, aerial:  21,  pigeon: 24, gSpeed: 3   ,  pSpeed: 3   , loadTime: 1   },
        1171:  { ground: 0, aerial:  25,  pigeon: 25, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 1   },
        1201:  { ground: 0, aerial:  26,  pigeon: 24, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1   },
        1231:  { ground: 0, aerial:  27,  pigeon: 23, gSpeed: 2.5 ,  pSpeed: 3   , loadTime: 1   },
        1261:  { ground: 0, aerial:  28,  pigeon: 22, gSpeed: 2.5 ,  pSpeed: 3.5 , loadTime: 1   },
        1291:  { ground: 0, aerial:  22,  pigeon: 28, gSpeed: 3   ,  pSpeed: 2.5 , loadTime: 1   },
        1321:  { ground: 0, aerial:  23,  pigeon: 27, gSpeed: 3   ,  pSpeed: 2.5 , loadTime: 1   },
        1351:  { ground: 0, aerial:  24,  pigeon: 26, gSpeed: 2.5 ,  pSpeed: 2.5 , loadTime: 1   },
        1381:  { ground: 0, aerial:  25,  pigeon: 25, gSpeed: 3   ,  pSpeed: 2.5 , loadTime: 1   },
        1411:  { ground: 0, aerial:  25,  pigeon: 25, gSpeed: 3   ,  pSpeed: 3   , loadTime: 1   },
        1441:  { ground: 0, aerial:  25,  pigeon: 25, gSpeed: 3   ,  pSpeed: 3   , loadTime: 1   },
        1471:  { ground: 0, aerial:  25,  pigeon: 25, gSpeed: 3   ,  pSpeed: 3   , loadTime: 1   }
    }   
};