var WONBATS=WONBATS||{};(function(){'use strict';function CESEntity(){this.alive=false;}
function CESEngine(entitiesQty,componentsClasses){var i;this.components={};componentsClasses=componentsClasses||[];componentsClasses.push(CESEntity);for(i=0;i<componentsClasses.length;i+=1){this.createComponents(componentsClasses[i],entitiesQty);}
this.paused=true;this.systems=[];this.updateMethods=[];this.updateArguments=[];}
CESEngine.prototype.update=function(dt){var i;if(this.paused){return;}
for(i=0;i<this.updateMethods.length;i+=1){this.executeUpdate(dt,this.updateMethods[i].method,this.updateMethods[i].requiredComponentsClasses);}};CESEngine.prototype.executeUpdate=function(dt,method,requiredComponentsClasses){var components=this.getComponents(CESEntity),component,entity,processEntity,i,j;this.updateArguments[0]=dt;for(i=0;i<components.length;i+=1){if(components[i].alive){processEntity=true;for(j=0;j<requiredComponentsClasses.length;j+=1){component=this.getComponentFromEntity(requiredComponentsClasses[j],i);if(component){this.updateArguments[j+1]=component;}else{processEntity=false;break;}}
if(processEntity){method.apply(null,this.updateArguments);}}}};CESEngine.prototype.createEntity=function(){var i;for(i=0;i<this.components[CESEntity.name].length;i+=1){if(!this.components[CESEntity.name][i].alive){this.components[CESEntity.name][i].alive=true;return i;}}
return-1;};CESEngine.prototype.isEntityAlive=function(entity){return this.components[CESEntity.name][entity].alive;};CESEngine.prototype.createComponents=function(ComponentClass,qty){var i,component;this.components[ComponentClass.name]=[];for(i=0;i<qty;i+=1){component=new ComponentClass();component.entity=i;component.enable=false;this.components[ComponentClass.name][i]=component;}};CESEngine.prototype.getComponents=function(ComponentClass){return this.components[ComponentClass.name];};CESEngine.prototype.addComponentToEntity=function(ComponentClass,entity){var component=this.components[ComponentClass.name][entity];component.enable=true;return component;};CESEngine.prototype.getComponentFromEntity=function(ComponentClass,entity){var component=this.components[ComponentClass.name][entity];if(component.enable){return component;}
return undefined;};CESEngine.prototype.removeComponentFromEntity=function(componentClass,entity){var component=this.components[componentClass.name][entity];component.enable=false;};CESEngine.prototype.removeEntity=function(entity){var componentClassName;for(componentClassName in this.components){if(this.components.hasOwnProperty(componentClassName)){this.components[componentClassName][entity].enable=false;}}
this.components[CESEntity.name][entity].alive=false;};CESEngine.prototype.addUpdate=function(method,requiredComponentsClasses){this.updateMethods.push({method:method,requiredComponentsClasses:requiredComponentsClasses});};CESEngine.prototype.start=function(){this.paused=false;};CESEngine.prototype.stop=function(){this.paused=true;};CESEngine.prototype.dispose=function(){var i=0,key="";for(i=0;i<this.updateMethods.length;i+=1){this.updateMethods[i].method=null;this.updateMethods[i].requiredComponentsClasses=null;this.updateMethods[i]=null;}
this.updateMethods.length=0;for(key in this.components){if(this.components.hasOwnProperty(key)){this.components[key].length=0;this.components[key]=null;}}
this.components=null;};WONBATS.CESEngine=CESEngine;}());