{
	"version": 1574771575,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/keys-sheet0.png",
		"images/dial-sheet0.png",
		"images/dial-sheet1.png",
		"images/playalong-sheet0.png",
		"images/playalong-sheet1.png",
		"images/playalong-sheet2.png",
		"images/restartbtn-sheet0.png",
		"images/restartbtn-sheet1.png",
		"images/board-sheet0.png",
		"images/chicken-sheet0.png",
		"images/helpbtn-sheet0.png",
		"images/helpbtn-sheet1.png",
		"images/helpscreen-sheet0.png",
		"media/rubber chicken 1b.m4a",
		"media/rubber chicken 1b.ogg",
		"media/rubber chicken 2b.m4a",
		"media/rubber chicken 2b.ogg",
		"media/rubber chicken 3b.m4a",
		"media/rubber chicken 3b.ogg",
		"media/rubber chicken 4b.m4a",
		"media/rubber chicken 4b.ogg",
		"media/rubber chicken 5b.m4a",
		"media/rubber chicken 5b.ogg",
		"media/rubber chicken 6b.m4a",
		"media/rubber chicken 6b.ogg",
		"media/rubber chicken 7b.m4a",
		"media/rubber chicken 7b.ogg",
		"media/rubber chicken 8b.m4a",
		"media/rubber chicken 8b.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}